//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.Filters {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class FiltersStrings {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal FiltersStrings() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.Filters.FiltersStrings", typeof(FiltersStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error == {0}.
		/// </summary>
		internal static string ksErrorMsg {
			get {
				return ResourceManager.GetString("ksErrorMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The match string is too long, and will be trimmed to the first {0} characters..
		/// </summary>
		internal static string ksMatchStringToLongLength0 {
			get {
				return ResourceManager.GetString("ksMatchStringToLongLength0", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Error..
		/// </summary>
		internal static string ksNoError {
			get {
				return ResourceManager.GetString("ksNoError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No Filter.
		/// </summary>
		internal static string ksNoFilter {
			get {
				return ResourceManager.GetString("ksNoFilter", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized backslash escape sequence in regular expression..
		/// </summary>
		internal static string ksRegexBadEscapeSequence {
			get {
				return ResourceManager.GetString("ksRegexBadEscapeSequence", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error in {min,max} interval..
		/// </summary>
		internal static string ksRegexBadInterval {
			get {
				return ResourceManager.GetString("ksRegexBadInterval", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This must always be the last value to indicate the limit for regular expression errors..
		/// </summary>
		internal static string ksRegexErrorLimit {
			get {
				return ResourceManager.GetString("ksRegexErrorLimit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Start of codes indicating Regexp failures..
		/// </summary>
		internal static string ksRegexErrorStart {
			get {
				return ResourceManager.GetString("ksRegexErrorStart", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An internal error (bug) was detected..
		/// </summary>
		internal static string ksRegexInternalError {
			get {
				return ResourceManager.GetString("ksRegexInternalError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Back-reference to a non-existent capture group..
		/// </summary>
		internal static string ksRegexInvalidBackRef {
			get {
				return ResourceManager.GetString("ksRegexInvalidBackRef", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid value for match mode flags..
		/// </summary>
		internal static string ksRegexInvalidFlag {
			get {
				return ResourceManager.GetString("ksRegexInvalidFlag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to RegexMatcher in invalid state for requested operation..
		/// </summary>
		internal static string ksRegexInvalidState {
			get {
				return ResourceManager.GetString("ksRegexInvalidState", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Look-Behind pattern matches must have a bounded maximum length..
		/// </summary>
		internal static string ksRegexLookBehindLimit {
			get {
				return ResourceManager.GetString("ksRegexLookBehindLimit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In {min,max}, max is less than min..
		/// </summary>
		internal static string ksRegexMaxLtMin {
			get {
				return ResourceManager.GetString("ksRegexMaxLtMin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Incorrectly nested parentheses in regular expression..
		/// </summary>
		internal static string ksRegexMismatchedParen {
			get {
				return ResourceManager.GetString("ksRegexMismatchedParen", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Decimal number is too large..
		/// </summary>
		internal static string ksRegexNumberTooBig {
			get {
				return ResourceManager.GetString("ksRegexNumberTooBig", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Incorrect Unicode property..
		/// </summary>
		internal static string ksRegexPropertySyntax {
			get {
				return ResourceManager.GetString("ksRegexPropertySyntax", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid regular expression (syntax error)..
		/// </summary>
		internal static string ksRegexRuleSyntax {
			get {
				return ResourceManager.GetString("ksRegexRuleSyntax", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Regular expressions cannot have UnicodeSets containing strings..
		/// </summary>
		internal static string ksRegexSetContainsString {
			get {
				return ResourceManager.GetString("ksRegexSetContainsString", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Use of a regular expression feature that is not yet implemented..
		/// </summary>
		internal static string ksRegexUnimplemented {
			get {
				return ResourceManager.GetString("ksRegexUnimplemented", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Uncheck all.
		/// </summary>
		internal static string ksUncheckAll {
			get {
				return ResourceManager.GetString("ksUncheckAll", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unknown.
		/// </summary>
		internal static string ksUnknown {
			get {
				return ResourceManager.GetString("ksUnknown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unknown error({0})..
		/// </summary>
		internal static string ksUnknownError {
			get {
				return ResourceManager.GetString("ksUnknownError", resourceCulture);
			}
		}
	}
}
