/*----------------------------------------------------------------------------------------------
Copyright 2002, SIL International. All rights reserved.

File: RnImportRes.h
Responsibility: Steve McConnel
Last reviewed: Not yet.

Description:
	Resource definitions for RnImportDlg and the related data import wizard.  Note that these
	must be in the range given by kridRnImportMin and kridRnImportLim in RNCoreRes.h
	(2600-2900).
----------------------------------------------------------------------------------------------*/

#define kstidImportWizTitle                   2600
#define kstidImportMsgCaption                 2601
#define kstidImportEditList1Fmt               2602
#define kstidImportEditList2Fmt               2603
#define kstidImportEditListsFmt               2604
#define kridImportWizOverviewDlg              2605
#define kcidImportWizOverviewHdr              2606
#define kridImportWizSettingsDlg              2607
#define kcidImportWizSettingsHdr              2608
#define kctidImportWizSettingsFrom            2609
#define kctidImportWizSettingsTo              2610
#define kstidImportWizSettingsClean           2611
#define kstidImportWizSettingsDefault         2612
#define kstidImportWizSettingsDefMod          2613
#define kstidImportWizSettingsDefModFmt       2614
#define kstidImportWizSettingsNew             2615
#define kridImportWizSfmDbDlg                 2616
#define kcidImportWizSfmDbHdr                 2617
#define kctidImportWizSfmDbFile               2618
#define kctidImportWizSfmDbBrowse             2619
#define kstidImportWizSfmDbNotShoebox         2620
#define kctidImportWizSfmDbProjText1          2621
#define kctidImportWizSfmDbProjText2          2622
#define kctidImportWizSfmDbProjText3          2623
#define kctidImportWizSfmDbProjFile           2624
#define kctidImportWizSfmDbProjBrowse         2625
#define kridImportWizRecMarkerDlg             2626
#define kcidImportWizRecMarkerHdr             2627
#define kctidImportWizRecMarkerCode           2628
#define kctidImportWizRecMarkerView           2629
#define kridImportWizRecTypesDlg              2630
#define kcidImportWizRecTypesHdr              2631
#define kcidImportWizRecTypesList             2632
#define kctidImportWizRecTypesAdd             2633
#define kctidImportWizRecTypesModify          2634
#define kctidImportWizRecTypesDelete          2635
#define kstidImportWizRecTypesEvent           2636
#define kstidImportWizRecTypesHypo            2637
#define kstidImportWizRecTypesEventLev        2638
#define kstidImportWizRecTypesHypoLev         2639
#define kstidImportWizRecTypesLevelOneFmt     2640
#define kstidImportWizRecTypesCannotDelFmt    2641
#define kstidImportWizRecTypesDelFmt          2642
#define kstidImportWizRecTypesAlreadyFmt      2643
#define kridImportWizFldMappingsDlg           2644
#define kcidImportWizFldMappingsHdr           2645
#define kctidImportWizFldMapModify            2646
#define kctidImportWizFldMapDiscard           2647
#define kcidImportWizFldMappingsList          2648
#define kridImportWizChrMappingsDlg           2649
#define kcidImportWizChrMappingsHdr           2650
#define kctidImportWizChrMapAdd               2651
#define kctidImportWizChrMapModify            2652
#define kctidImportWizChrMapDelete            2653
#define kcidImportWizChrMappingsList          2654
#define kstidImportWizChrMapBeginMkr          2655
#define kstidImportWizChrMapEndMkr            2656
#define kstidImportWizChrMapDestin            2657
#define kstidImportWizChrMapDirFmtBold        2658
#define kstidImportWizChrMapDirFmtItalic      2659
#define kstidImportWizChrMapWrtSystemFmt      2660
#define kstidImportWizChrMapStyleFmt          2661
#define kstidImportWizChrMapIgnored           2662
#define kstidImportWizChrMapAlreadyFmt        2663
#define kstidImportWizChrMapMissingFmt        2664
#define kstidImportWizChrMapDelFmt            2665
#define kridImportWizSaveSetDlg               2666
#define kcidImportWizSaveSetHdr               2667
#define kctidImportWizSaveSetOverwrite        2668
#define kctidImportWizSaveSetAppend           2669
#define kctidImportWizSaveSetMerge            2670
#define kridImportWizFinalDlg                 2671
#define kcidImportWizFinalHdr                 2672
#define kridImportRecTypeDlg                  2673
#define kctidImportFldMarker                  2674
#define kctidImportRecType                    2675
#define kridImportFldMappingDlg               2676
#define kctidImportFldDest                    2677
#define kcidImportDataLabel                   2678
#define kcidImportDataDivider                 2679
#define kcidImportDataSummary                 2680
#define kctidImportFldContentList             2681
#define kstidImportDataLabelFmt               2682
#define kstidImportDataSummaryFmt             2683
#define kcidImportFldOptionLabel              2684
#define kstidImportListRefFldOptionLabel      2685
#define kstidImportTextFldOptionLabel         2686
#define kstidImportStringFldOptionLabel       2687
#define kstidImportDateFldOptionLabel         2688
#define kstidImportTimeFldOptionLabel         2689
#define kstidImportLinkFldOptionLabel         2690
#define kstidImportGenDateFldOptionLabel      2691
#define kstidImportIntegerFldOptionLabel      2692
#define kstidImportFldMapDelFmt               2693
#define kstidImportWizFldMappingAlreadyFmt    2694
#define kstidImportWizFldMappingDiscard       2695
#define kstidImportDiscardedOptionLabel       2696
#define kstidImportWizFldMapMarker            2697
#define kstidImportWizFldMapDescription       2698
#define kstidImportWizFldMapDestination       2699
#define kridImportTopicsListFldOptionSubDlg   2700
#define kctidImportTLFDelimMultiEnb           2701
#define kctidImportTLFDelimMulti              2702
#define kctidImportTLFDelimSubEnb             2703
#define kctidImportTLFDelimSub                2704
#define kctidImportTLFBetweenEnb              2705
#define kctidImportTLFBetweenAfter            2706
#define kctidImportTLFBetweenBefore           2707
#define kctidImportTLFOnlyBeforeEnb           2708
#define kctidImportTLFOnlyBefore              2709
#define kctidImportTLFDiscardNewEnb           2710
#define kctidImportTLFSubstList               2711
#define kctidImportTLFSubstListAdd            2712
#define kctidImportTLFSubstListModify         2713
#define kctidImportTLFSubstListDelete         2714
#define kstidImportTLFSubstListDelFmt         2715
#define kstidImportTLFSubstLabelOld           2716
#define kstidImportTLFSubstLabelNew           2717
#define kctidImportTLFDiscardEmptyEnb         2718
#define kctidImportTLFEmptyDefault            2719
#define kctidImportTLFMatchAbbr               2720
#define kctidImportTLFMatchName               2721
#define kridImportTextFldOptionSubDlg         2722
#define kctidImportTFPara                     2723
#define kctidImportTFStyles                   2724
#define kctidImportTFDiscardEmptyEnb          2725
#define kctidImportTFNewParaEachLineEnb       2726
#define kctidImportTFNewParaAfterBlankEnb     2727
#define kctidImportTFNewParaIndentedEnb       2728
#define kctidImportTFNewParaShortLineEnb      2729
#define kctidImportTFShortLineLength          2730
#define kctidImportTFDefaultWrtSys            2731
#define kridImportDateFldOptionSubDlg         2732
#define kctidImportDFFormatList               2733
#define kctidImportDFDiscardEmptyEnb          2734
#define kctidImportDFFormatAdd                2735
#define kctidImportDFFormatModify             2736
#define kctidImportDFFormatDelete             2737
#define kstidImportDFFormatLabel              2738
#define kstidImportDFLongDateFmt              2739
#define kstidImportDFFormatDelFmt             2740
#define kridImportNoFldOptionSubDlg           2741
#define kcidImportNoOptionsString             2742
#define kstidImportNoStringOptions            2743
#define kstidImportNoTimeOptions              2744
#define kstidImportNoLinkOptions              2745
#define kstidImportNoDateOptions              2746
#define kstidImportNoIntegerOptions           2747
#define kstidImportNoDiscardOptions           2748
#define kctidImportNoOptDiscardEmptyEnb       2749
#define kridImportTLFNewDiscardDlg            2750
#define kctidImportTLFDiscard                 2751
#define kstidImportTLFDiscardAlreadyFmt       2752
#define kstidImportTLFDiscardDelFmt           2753
#define kridImportTLFNewSubstitutionDlg       2754
#define kctidImportTLFSubstMatch              2755
#define kctidImportTLFSubstReplace            2756
#define kstidImportTLFSubstAlreadyFmt         2757
#define kstidImportTLFSubstDelFmt             2758
#define kridImportCharMappingDlg              2759
#define kctidImportCharMapBeginMkr            2760
#define kctidImportCharMapEndMkr              2761
#define kctidImportCharMapWrtSystemEnb        2762
#define kctidImportCharMapWrtSystemSelect     2763
#define kctidImportCharMapWrtSystems          2764
#define kctidImportCharMapStyleEnb            2765
#define kctidImportCharMapStyleSelect         2766
#define kctidImportCharMapStyles              2767
#define kctidImportCharMapDirFmtEnb           2768
#define kctidImportCharMapDirFmtSelect        2769
#define kctidImportCharMapIgnoreEnb           2770
#define kctidImportWizSaveSetDecision         2771
#define kridImportDateFormatDlg               2772
#define kctidImportDateFormat                 2773
#define kctidImportDateFormatApply            2774
#define kctidImportFormattedDate              2775
#define kstidImportDateFormatError            2776
#define kstidImportDateFormatErrorMsg         2777
#define kstidImportTitleError                 2778
#define kstidImportDateCreatedError           2779
#define kstidImportDateModifiedError          2780
#define kstidImportVersionHistoryError        2781
#define kstidImportDateOfEventError           2782
#define kstidImportExternalMaterialsError     2783
#define kstidImportPersonalNotesError         2784
#define kstidImportDescriptionError           2785
#define kstidImportResearchPlanError          2786
#define kstidImportDiscussionError            2787
#define kstidImportFurtherQuestionsError      2788
#define kstidImportConclusionsError           2789
#define kstidImportHypothesisError            2790
#define kstidImportGeneralCOMLoadError        2791
#define kstidImportGeneralLoadError           2792
#define kstidImportStoreErrorFmt              2793
#define kridRnImportProgress                  2794
#define kctidImportProgAction                 2795
#define kctidImportProgProgress               2796
#define kstidImportFromTitleFmt               2797
#define kstidImportCannotMaster               2798
#define kstidImportPhaseOne                   2799
#define kctidImportWizSaveSetFinalDecision    2800
// unused value:                              2801
// unused value:                              2802
// unused value:                              2803
#define kstidImportPhaseTwo                   2804
#define kstidImportPhaseTwo1                  2805
#define kstidImportOnlyPhase                  2806
#define kstidImportOnlyPhase1                 2807
#define kctidImportProgStatus                 2808
#define kstidImportStatus                     2809
#define kstidImportShortStatus                2810
#define kstidImportEntryError                 2811
#define kstidImportEntriesError               2812
#define kridImportSFWizOverviewPicture        2813
#define kridImportSFWizSettingsPicture        2814
#define kridImportSFWizSfmDbPicture           2815
#define kridImportSFWizRecMarkerPicture       2816
#define kridImportSFWizRecTypesPicture        2817
#define kridImportSFWizFldMappingsPicture     2818
#define kridImportSFWizChrMappingsPicture     2819
#define kridImportSFWizSaveSetPicture         2820
#define kridImportSFWizFinalPicture           2821
#define kcidImportWizOverviewStep             2822
#define kcidImportWizSettingsStep             2823
#define kcidImportWizSfmDbStep                2824
#define kcidImportWizRecMarkerStep            2825
#define kcidImportWizRecTypesStep             2826
#define kcidImportWizFldMappingsStep          2827
#define kcidImportWizChrMappingsStep          2828
#define kcidImportWizSaveSetStep              2829
#define kcidImportWizFinalStep                2830
#define kstidImportWizOverviewStep            2831
#define kstidImportWizSettingsStep            2832
#define kstidImportWizSfmDbStep               2833
#define kstidImportWizRecMarkerStep           2834
#define kstidImportWizRecTypesStep            2835
#define kstidImportWizFldMappingsStep         2836
#define kstidImportWizChrMappingsStep         2837
#define kstidImportWizSaveSetStep             2838
#define kstidImportWizFinalStep               2839
#define kstidImportWizSfmDbNotStdFmt          2840
#define kridImportMultiLingualFldOptionSubDlg 2841
#define kctidImportMLWrtSys                   2842
#define kctidImportMLDiscardEmptyEnb          2843
#define kridImportWizEncodeConvDlg            2844
#define kridImportSFWizEncodeConvPicture      2845
#define kcidImportWizEncodeConvHdr            2846
#define kcidImportWizEncodeConvList           2847
#define kctidImportWizEncodeConvModify        2848
#define kctidImportWizEncodeConvPreview       2849
#define kcidImportWizEncodeConvStep           2850
#define kstidImportWizEncodeConvStep          2851
#define kctidImportFieldAdd                   2852
#define kctidImportTFAddWrtSys                2853
#define kctidImportMLAddWrtSys                2854
#define kstidImportEncConvWrtSys              2855
#define kstidImportEncConvFont                2856
#define kstidImportEncConvConvrtr             2857
#define kstidImportEncConvDesc                2858
#define kstidImportWizUnknownEncodingConv     2859
#define kstidImportWizNoEncodingConvDesc      2860

#define kridRnImportListEditProgress          2861
#define kstidImportListEditCaption            2862
#define kstidImportListEditList               2863
#define kstidImportListEditStatus             2864
#define kctidImportListEditCancel             2865
#define kstidImportDelOneFilter               2866
#define kstidImportDelMultipleFilters         2867
