//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageExplorer.Areas.TextsAndWords.Tools.ComplexConcordance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComplexConcordanceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplexConcordanceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageExplorer.Areas.TextsAndWords.Tools.ComplexConcordance.ComplexConcordanceR" +
                            "esources", typeof(ComplexConcordanceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string ksComplexConcCategory {
            get {
                return ResourceManager.GetString("ksComplexConcCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string ksComplexConcEntry {
            get {
                return ResourceManager.GetString("ksComplexConcEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string ksComplexConcForm {
            get {
                return ResourceManager.GetString("ksComplexConcForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloss.
        /// </summary>
        internal static string ksComplexConcGloss {
            get {
                return ResourceManager.GetString("ksComplexConcGloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Any&gt;.
        /// </summary>
        internal static string ksComplexConcInflFeatAny {
            get {
                return ResourceManager.GetString("ksComplexConcInflFeatAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infl.
        /// </summary>
        internal static string ksComplexConcInflFeatures {
            get {
                return ResourceManager.GetString("ksComplexConcInflFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morph.
        /// </summary>
        internal static string ksComplexConcMorph {
            get {
                return ResourceManager.GetString("ksComplexConcMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string ksComplexConcTag {
            get {
                return ResourceManager.GetString("ksComplexConcTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ksComplexConcType {
            get {
                return ResourceManager.GetString("ksComplexConcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string ksComplexConcWord {
            get {
                return ResourceManager.GetString("ksComplexConcWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Boundary.
        /// </summary>
        internal static string ksComplexConcWordBoundary {
            get {
                return ResourceManager.GetString("ksComplexConcWordBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid tag must be selected..
        /// </summary>
        internal static string ksInvalidTagMsg {
            get {
                return ResourceManager.GetString("ksInvalidTagMsg", resourceCulture);
            }
        }
    }
}
