## --------------------------------------------------------------------------------------------
## --------------------------------------------------------------------------------------------
## Copyright (c) 2006-2013 SIL International
## This software is licensed under the LGPL, version 2.1 or later
## (http://www.gnu.org/licenses/lgpl-2.1.html)
##
## NVelocity template file
## This file is used by the LcmGenerate task to generate the source code from the XMI
## database model.
## --------------------------------------------------------------------------------------------
//This is automatically generated by LcmGenerate task.  ****Do not edit****
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace SIL.LCModel.DomainImpl
{
#foreach($module in $lcmgenerate.Modules)
#foreach($class in $module.Classes)
#if(!$class.IsAbstract)
#parse("factory.vm.cs")
#end
#end
#end
}