// This file was previously generated by the Nant target 'GenerateFilesFromModel-build' from
// FDO/CmTypes.txt.  We chose not to reimplement this process using MSBuild.
// In the unlikely event of changes to this file, consistent changes should be made to
// Common/CoreImpl/CellarPropertyType.cs, which is the C# version in the new model.
#ifdef _MSC_VER
#pragma once
#endif
#ifndef CELLARBASECONSTANTS_H
#define CELLARBASECONSTANTS_H 1
typedef enum CellarModuleDefns
{
	kcptNil = 0,
	kcptMin = 1,
	kcptBoolean = 1,
	kcptInteger = 2,
	kcptNumeric = 3,
	kcptFloat = 4,
	kcptTime = 5,
	kcptGuid = 6,
	kcptImage = 7,
	kcptGenDate = 8,
	kcptBinary = 9,
	kcptString = 13,
	kcptMultiString = 14,
	kcptUnicode = 15,
	kcptMultiUnicode = 16,
	kcptMinObj = 23,
	kcptOwningAtom = 23,
	kcptReferenceAtom = 24,
	kcptOwningCollection = 25,
	kcptReferenceCollection = 26,
	kcptOwningSequence = 27,
	kcptReferenceSequence = 28,
	kcptLim = 29,
} CellarModuleDefns;
#endif
