/*-----------------------------------------------------------------------*//*:Ignore in Surveyor
Copyright (c) 1999-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: TextServTlb.idl
Responsibility: Jeff Gayle
Last reviewed:

	Defines Text Services Type Library.
-------------------------------------------------------------------------------*//*:End Ignore*/
import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";

#include "common.idh"

DeclareLibrary(FwKernelLib, 1.0, "FieldWorks Kernel", F1EF76E0-BE04-11d3-8D9A-005004DEFEC4)
{
	#include "FwKernel.idh"
	#include "TextServ.idh"
	#include "Render.idh"
	#include "Language.idh"
};
