#!/bin/sh

# Environment settings for packaging FW
#
# Source this file in a shell and then run make

export PATH=/opt/mono-sil/bin:$PATH
export LD_LIBRARY_PATH=/opt/mono-sil/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/opt/mono-sil/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
