// Copyright (c) 2026 SIL International
// This software is licensed under the LGPL, version 2.1 or later
// (http://www.gnu.org/licenses/lgpl-2.1.html)

using Avalonia.Controls;

namespace FwAvaloniaDialogs
{
	/// <summary>
	/// Body of the kit's reusable message / confirmation dialog (the Avalonia analog of WinForms MessageBox).
	/// XAML-authored UserControl bound to <see cref="MessageBoxViewModel"/> with compiled bindings, hosted inside
	/// a WinForms-owned modal Form during coexistence (dialog-ownership.md) via
	/// <see cref="SIL.FieldWorks.Common.FwAvalonia.AvaloniaDialogHost.ShowModal"/>. Shown through the
	/// <see cref="FwMessageBox.Show(System.Windows.Forms.IWin32Window,string,string,FwMessageBoxButtons,FwMessageBoxIcon)"/>
	/// entry point. <c>InitializeComponent()</c> is generated by the Avalonia XAML compiler.
	/// </summary>
	public partial class MessageBoxView : UserControl
	{
		public MessageBoxView()
		{
			DialogThemeBootstrap.Apply(this);
			InitializeComponent();
		}
	}
}
