// Copyright (c) 2026 SIL International
// This software is licensed under the LGPL, version 2.1 or later
// (http://www.gnu.org/licenses/lgpl-2.1.html)

using Avalonia.Controls;

namespace FwAvaloniaDialogs
{
	/// <summary>
	/// Tools → Options dialog body — the first dialog built with this kit's MVVM pattern. XAML-authored
	/// UserControl bound to <see cref="OptionsDialogViewModel"/> with compiled bindings. Hosted as
	/// Avalonia content inside a WinForms-owned modal Form during coexistence (dialog-ownership.md); a
	/// standalone Window owner comes at the shell phase. <c>InitializeComponent()</c> is generated by
	/// the Avalonia XAML compiler.
	/// </summary>
	public partial class OptionsDialogView : UserControl
	{
		public OptionsDialogView()
		{
			DialogThemeBootstrap.Apply(this);
			InitializeComponent();
		}
	}
}
