call ReplaceLinksGen Button.xml
call ReplaceLinksGen CheckBox.xml
call ReplaceLinksGen ColorPal.xml
call ReplaceLinksGen Cursor.xml
call ReplaceLinksGen DateDlg0.xml
call ReplaceLinksGen DatePicker.xml
call ReplaceLinksGen Dialog.xml
call ReplaceLinksGen ListBox.xml
call ReplaceLinksGen MenuBtn.xml
call ReplaceLinksGen MsgBox.xml
call ReplaceLinksGen PrintDlg.xml
call ReplaceLinksGen RadioBtn.xml
call ReplaceLinksGen ScrollBar.xml
call ReplaceLinksGen SpinCtrl.xml
call ReplaceLinksGen Splash.xml
call ReplaceLinksGen StdControls.xml
call ReplaceLinksGen TaskbarBtn.xml
call ReplaceLinksGen TextBox.xml
call ReplaceLinksGen TlbButton.xml
call ReplaceLinksGen Toggle.xml
call ReplaceLinksGen ToolBar.xml
call ReplaceLinksGen Tree.xml
call ReplaceLinksGen Window.xml
