//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSynthByGlossLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HCSynthByGlossStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HCSynthByGlossStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCSynthByGlossLib.HCSynthByGlossStrings", typeof(HCSynthByGlossStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCSynthByGloss locale -h HC.xml_file -g gloss_file -o output (-t (-s)).
        /// </summary>
        public static string ksCommandLineUsage {
            get {
                return ResourceManager.GetString("ksCommandLineUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find .
        /// </summary>
        public static string ksCouldNotFind {
            get {
                return ResourceManager.GetString("ksCouldNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;.
        /// </summary>
        public static string ksCouldNotFindFile {
            get {
                return ResourceManager.GetString("ksCouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Duplicate gloss(es) found for &apos;.
        /// </summary>
        public static string ksDuplicateGlossFoundFor {
            get {
                return ResourceManager.GetString("ksDuplicateGlossFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloss file.
        /// </summary>
        public static string ksGlossFile {
            get {
                return ResourceManager.GetString("ksGlossFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HC XML file.
        /// </summary>
        public static string ksHCXmlFile {
            get {
                return ResourceManager.GetString("ksHCXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  One or more glosses not found:.
        /// </summary>
        public static string ksOneOrMoreGlossesNotFound {
            get {
                return ResourceManager.GetString("ksOneOrMoreGlossesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing result: .
        /// </summary>
        public static string ksProcessingResult {
            get {
                return ResourceManager.GetString("ksProcessingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t-s = show the tracing result in the system default web browser; -s is only valid when also using -t.
        /// </summary>
        public static string ksShowTracing {
            get {
                return ResourceManager.GetString("ksShowTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string ksSuccess {
            get {
                return ResourceManager.GetString("ksSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  synthesis may not work..
        /// </summary>
        public static string ksSynthesisMayNotWork {
            get {
                return ResourceManager.GetString("ksSynthesisMayNotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t-t = turn on tracing.
        /// </summary>
        public static string ksTurnOnTracing {
            get {
                return ResourceManager.GetString("ksTurnOnTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        public static string ksUsage {
            get {
                return ResourceManager.GetString("ksUsage", resourceCulture);
            }
        }
    }
}
