//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.IText {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ITextStrings {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ITextStrings() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.IText.ITextStrings", typeof(ITextStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to For the category: .
		/// </summary>
		internal static string ConcordanceSearchCatLabel {
			get {
				return ResourceManager.GetString("ConcordanceSearchCatLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to For the tag: .
		/// </summary>
		internal static string ConcordanceSearchTagLabel {
			get {
				return ResourceManager.GetString("ConcordanceSearchTagLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to For the text: .
		/// </summary>
		internal static string ConcordanceSearchTextLabel {
			get {
				return ResourceManager.GetString("ConcordanceSearchTextLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleted object detected.
		/// </summary>
		internal static string DeletedObjectDetected {
			get {
				return ResourceManager.GetString("DeletedObjectDetected", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Accept entire analysis (Ctrl-TAB).
		/// </summary>
		internal static string ksAcceptEntireAnalysis {
			get {
				return ResourceManager.GetString("ksAcceptEntireAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add Line.
		/// </summary>
		internal static string ksAddLine {
			get {
				return ResourceManager.GetString("ksAddLine", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to     Add New Sense....
		/// </summary>
		internal static string ksAddNewSense_ {
			get {
				return ResourceManager.GetString("ksAddNewSense_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add New Sense for {0} ....
		/// </summary>
		internal static string ksAddNewSenseForX_ {
			get {
				return ResourceManager.GetString("ksAddNewSenseForX_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add Writing System.
		/// </summary>
		internal static string ksAddWS {
			get {
				return ResourceManager.GetString("ksAddWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Allomorph of....
		/// </summary>
		internal static string ksAllomorphOf_ {
			get {
				return ResourceManager.GetString("ksAllomorphOf_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to add the {0} allomorph ({1}) to this entry?.
		/// </summary>
		internal static string ksAreYouSureAddZtoX {
			get {
				return ResourceManager.GetString("ksAreYouSureAddZtoX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You already have this interlinear text in your project. Would you like to merge it?.
		/// </summary>
		internal static string ksAskMergeInterlinearText {
			get {
				return ResourceManager.GetString("ksAskMergeInterlinearText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Duplicate text found..
		/// </summary>
		internal static string ksAskMergeInterlinearTextTitle {
			get {
				return ResourceManager.GetString("ksAskMergeInterlinearTextTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Do you want to save your settings for future imports?.
		/// </summary>
		internal static string ksAskSaveSettings {
			get {
				return ResourceManager.GetString("ksAskSaveSettings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Back to concorded item....
		/// </summary>
		internal static string ksBackToConcordedItem {
			get {
				return ResourceManager.GetString("ksBackToConcordedItem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Baseline.
		/// </summary>
		internal static string ksBaseline {
			get {
				return ResourceManager.GetString("ksBaseline", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to base.
		/// </summary>
		internal static string ksBaselineAbbr {
			get {
				return ResourceManager.GetString("ksBaselineAbbr", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This tab shows the contents of the current text (editable only in the Texts Edit tool)..
		/// </summary>
		internal static string ksBaseLineNotEditable {
			get {
				return ResourceManager.GetString("ksBaseLineNotEditable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to bst. an.
		/// </summary>
		internal static string ksBstAn {
			get {
				return ResourceManager.GetString("ksBstAn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot add allomorph.
		/// </summary>
		internal static string ksCannotAddAllomorph {
			get {
				return ResourceManager.GetString("ksCannotAddAllomorph", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot add Variant.
		/// </summary>
		internal static string ksCannotAddVariant {
			get {
				return ResourceManager.GetString("ksCannotAddVariant", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot create new entry.
		/// </summary>
		internal static string ksCannotCreateNewEntry {
			get {
				return ResourceManager.GetString("ksCannotCreateNewEntry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In this tool, we do not allow deleting parts of Scripture sections. Please use Translation Editor to edit Scripture..
		/// </summary>
		internal static string ksCannotDeleteScripture {
			get {
				return ResourceManager.GetString("ksCannotDeleteScripture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This wordform cannot be deleted..
		/// </summary>
		internal static string ksCannotDeleteWordform {
			get {
				return ResourceManager.GetString("ksCannotDeleteWordform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot hide field.
		/// </summary>
		internal static string ksCannotHideField {
			get {
				return ResourceManager.GetString("ksCannotHideField", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sorry, could not launch {0}..
		/// </summary>
		internal static string ksCannotLaunchX {
			get {
				return ResourceManager.GetString("ksCannotLaunchX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Can&apos;t Redo Changes in this Analysis.
		/// </summary>
		internal static string ksCannotRedoChangesHere {
			get {
				return ResourceManager.GetString("ksCannotRedoChangesHere", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to concordance.
		/// </summary>
		internal static string ksConcordance {
			get {
				return ResourceManager.GetString("ksConcordance", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concorded on {0}.
		/// </summary>
		internal static string ksConcordedOn0 {
			get {
				return ResourceManager.GetString("ksConcordedOn0", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Configure Interlinear....
		/// </summary>
		internal static string ksConfigureLinkText {
			get {
				return ResourceManager.GetString("ksConfigureLinkText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Conversion map error.
		/// </summary>
		internal static string ksConvMapError {
			get {
				return ResourceManager.GetString("ksConvMapError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create New Entry....
		/// </summary>
		internal static string ksCreateNewEntry_ {
			get {
				return ResourceManager.GetString("ksCreateNewEntry_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete Free Translation.
		/// </summary>
		internal static string ksDeleteFreeTrans {
			get {
				return ResourceManager.GetString("ksDeleteFreeTrans", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete Literal Translation.
		/// </summary>
		internal static string ksDeleteLitTrans {
			get {
				return ResourceManager.GetString("ksDeleteLitTrans", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete Note.
		/// </summary>
		internal static string ksDeleteNote {
			get {
				return ResourceManager.GetString("ksDeleteNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete this Wordform.
		/// </summary>
		internal static string ksDeleteThisWordform {
			get {
				return ResourceManager.GetString("ksDeleteThisWordform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edit Morph Breaks....
		/// </summary>
		internal static string ksEditMorphBreaks_ {
			get {
				return ResourceManager.GetString("ksEditMorphBreaks_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edit this Wordform.
		/// </summary>
		internal static string ksEditThisWordform {
			get {
				return ResourceManager.GetString("ksEditThisWordform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;Empty&gt;.
		/// </summary>
		internal static string ksEmpty {
			get {
				return ResourceManager.GetString("ksEmpty", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Press Enter to copy in Word Glosses, or start typing..
		/// </summary>
		internal static string ksEmptyFreeTransPrompt {
			get {
				return ResourceManager.GetString("ksEmptyFreeTransPrompt", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An empty paragraph.
		/// </summary>
		internal static string ksEmptyPara {
			get {
				return ResourceManager.GetString("ksEmptyPara", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Encoding Converter &apos;{0}&apos; failed: &apos;{1}&apos;.
		/// </summary>
		internal static string ksEncConvFailed {
			get {
				return ResourceManager.GetString("ksEncConvFailed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ].
		/// </summary>
		internal static string ksEndTagSymbol {
			get {
				return ResourceManager.GetString("ksEndTagSymbol", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enter or paste your text here, then click &quot;Show Interlinear.&quot;.
		/// </summary>
		internal static string ksEnterOrPasteHere {
			get {
				return ResourceManager.GetString("ksEnterOrPasteHere", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error.
		/// </summary>
		internal static string ksError {
			get {
				return ResourceManager.GetString("ksError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error Acessing Encoding Converters.
		/// </summary>
		internal static string ksErrorAcessingEncodingConverters {
			get {
				return ResourceManager.GetString("ksErrorAcessingEncodingConverters", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not load your settings from {0}. The system reported that {1}..
		/// </summary>
		internal static string ksErrorReadingSettings {
			get {
				return ResourceManager.GetString("ksErrorReadingSettings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Could not save your settings to {0}. The system reported that {1}..
		/// </summary>
		internal static string ksErrorWritingSettings {
			get {
				return ResourceManager.GetString("ksErrorWritingSettings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Expected &quot;{0}&quot; but found &quot;{1}&quot;..
		/// </summary>
		internal static string ksExpectedXButGotY {
			get {
				return ResourceManager.GetString("ksExpectedXButGotY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error occurred while exporting your data.  This is probably a bug in the FieldWorks code. Details: {0}.
		/// </summary>
		internal static string ksExportErrorMsg {
			get {
				return ResourceManager.GetString("ksExportErrorMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Export Interlinear.
		/// </summary>
		internal static string ksExportInterlinear {
			get {
				return ResourceManager.GetString("ksExportInterlinear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Export interlinearized texts.
		/// </summary>
		internal static string ksExportInterlinearizedTexts {
			get {
				return ResourceManager.GetString("ksExportInterlinearizedTexts", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Extension.
		/// </summary>
		internal static string ksExtension {
			get {
				return ResourceManager.GetString("ksExtension", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading {0} into {1} failed.{2}Look at {3} for details..
		/// </summary>
		internal static string ksFailedLoadingLL {
			get {
				return ResourceManager.GetString("ksFailedLoadingLL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finish LinguaLinks texts problem (phase 5): {0}.
		/// </summary>
		internal static string ksFinishLLTextsProblem5 {
			get {
				return ResourceManager.GetString("ksFinishLLTextsProblem5", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Abbreviation (of text).
		/// </summary>
		internal static string ksFldAbbreviation {
			get {
				return ResourceManager.GetString("ksFldAbbreviation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Baseline.
		/// </summary>
		internal static string ksFldBaseline {
			get {
				return ResourceManager.GetString("ksFldBaseline", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Comment (of text).
		/// </summary>
		internal static string ksFldComment {
			get {
				return ResourceManager.GetString("ksFldComment", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Free Translation.
		/// </summary>
		internal static string ksFldFreeTranslation {
			get {
				return ResourceManager.GetString("ksFldFreeTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Text.
		/// </summary>
		internal static string ksFldId {
			get {
				return ResourceManager.GetString("ksFldId", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Don&apos;t Import.
		/// </summary>
		internal static string ksFldIgnored {
			get {
				return ResourceManager.GetString("ksFldIgnored", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Literal Translation.
		/// </summary>
		internal static string ksFldLiteralTranslation {
			get {
				return ResourceManager.GetString("ksFldLiteralTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Note.
		/// </summary>
		internal static string ksFldNote {
			get {
				return ResourceManager.GetString("ksFldNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Paragraph Break.
		/// </summary>
		internal static string ksFldParagraphBreak {
			get {
				return ResourceManager.GetString("ksFldParagraphBreak", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reference.
		/// </summary>
		internal static string ksFldReference {
			get {
				return ResourceManager.GetString("ksFldReference", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source (of text).
		/// </summary>
		internal static string ksFldSource {
			get {
				return ResourceManager.GetString("ksFldSource", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Title (of text).
		/// </summary>
		internal static string ksFldTitle {
			get {
				return ResourceManager.GetString("ksFldTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Break phrase into words.
		/// </summary>
		internal static string ksFocusBox_btnBreakPhrase {
			get {
				return ResourceManager.GetString("ksFocusBox_btnBreakPhrase", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirm and move next.
		/// </summary>
		internal static string ksFocusBox_btnConfirmChanges {
			get {
				return ResourceManager.GetString("ksFocusBox_btnConfirmChanges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Make phrase with next word.
		/// </summary>
		internal static string ksFocusBox_btnLinkNextWord {
			get {
				return ResourceManager.GetString("ksFocusBox_btnLinkNextWord", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo.
		/// </summary>
		internal static string ksFocusBox_btnUndoChanges {
			get {
				return ResourceManager.GetString("ksFocusBox_btnUndoChanges", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Format.
		/// </summary>
		internal static string ksFormat {
			get {
				return ResourceManager.GetString("ksFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Free .
		/// </summary>
		internal static string ksFree_ {
			get {
				return ResourceManager.GetString("ksFree_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Free Translation.
		/// </summary>
		internal static string ksFreeTranslation {
			get {
				return ResourceManager.GetString("ksFreeTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FT .
		/// </summary>
		internal static string ksFT {
			get {
				return ResourceManager.GetString("ksFT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex. Gloss.
		/// </summary>
		internal static string ksGloss {
			get {
				return ResourceManager.GetString("ksGloss", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex. Gram. Info..
		/// </summary>
		internal static string ksGramInfo {
			get {
				return ResourceManager.GetString("ksGramInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Hide {0}.
		/// </summary>
		internal static string ksHideLine {
			get {
				return ResourceManager.GetString("ksHideLine", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to If you hide this line, some dependent lines will also be hidden..
		/// </summary>
		internal static string ksHidesDependentLinesAlso {
			get {
				return ResourceManager.GetString("ksHidesDependentLinesAlso", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ignore.
		/// </summary>
		internal static string ksIgnore {
			get {
				return ResourceManager.GetString("ksIgnore", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Import.
		/// </summary>
		internal static string ksImport {
			get {
				return ResourceManager.GetString("ksImport", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  is used in this text as an analysis language, but it is not currently part of your FieldWorks project.  Would you like to add it?  Click &quot;OK&quot; to add it or &quot;Cancel&quot; to skip this text..
		/// </summary>
		internal static string ksImportAnalysisLangMissing {
			get {
				return ResourceManager.GetString("ksImportAnalysisLangMissing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Text has new analysis writing system.
		/// </summary>
		internal static string ksImportAnalysisLangMissingTitle {
			get {
				return ResourceManager.GetString("ksImportAnalysisLangMissingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Import Failed.
		/// </summary>
		internal static string ksImportFailed {
			get {
				return ResourceManager.GetString("ksImportFailed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This import is set to use the writing system {0} as an analysis writing system, but it is not in your FieldWorks project. Would you like to add it?.
		/// </summary>
		internal static string ksImportSFMInterlinNewAnalysis {
			get {
				return ResourceManager.GetString("ksImportSFMInterlinNewAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This import is set to use the writing system {0} as a vernacular writing system, but it is not in your FieldWorks project. Would you like to add it?.
		/// </summary>
		internal static string ksImportSFMInterlinNewVernac {
			get {
				return ResourceManager.GetString("ksImportSFMInterlinNewVernac", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add writing system {0} to your FieldWorks project?.
		/// </summary>
		internal static string ksImportSFMInterlinNewWSTitle {
			get {
				return ResourceManager.GetString("ksImportSFMInterlinNewWSTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} texts will be imported from this SFM file..
		/// </summary>
		internal static string ksImportSFMInterlinTextCount {
			get {
				return ResourceManager.GetString("ksImportSFMInterlinTextCount", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  is used in this text as a vernacular writing system, but it is not currently part of your FieldWorks project.  Would you like to add it?  Click &quot;OK&quot; to add it or &quot;Cancel&quot; to skip this text..
		/// </summary>
		internal static string ksImportVernacLangMissing {
			get {
				return ResourceManager.GetString("ksImportVernacLangMissing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Text has new vernacular writing system.
		/// </summary>
		internal static string ksImportVernacLangMissingTitle {
			get {
				return ResourceManager.GetString("ksImportVernacLangMissingTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Input file ({0}) not found..
		/// </summary>
		internal static string ksInputFileNotFound {
			get {
				return ResourceManager.GetString("ksInputFileNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Interlinear XML parsing problem (phase 1): {0}..
		/// </summary>
		internal static string ksInterlinImportErrorPhase1 {
			get {
				return ResourceManager.GetString("ksInterlinImportErrorPhase1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Problem finishing interlinear import (phase 2): {0}..
		/// </summary>
		internal static string ksInterlinImportErrorPhase2 {
			get {
				return ResourceManager.GetString("ksInterlinImportErrorPhase2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Interlinear Import failed. Are you sure you are importing a file in FLExText interlinear format? Word and Open Office/Libre Office docs cannot yet be imported:.
		/// </summary>
		internal static string ksInterlinImportFailed {
			get {
				return ResourceManager.GetString("ksInterlinImportFailed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 1 of 2: Loading interlinear XML data into FieldWorks.
		/// </summary>
		internal static string ksInterlinImportPhase1of2 {
			get {
				return ResourceManager.GetString("ksInterlinImportPhase1of2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 2 of 2: Finishing importing interlinear texts..
		/// </summary>
		internal static string ksInterlinImportPhase2of2 {
			get {
				return ResourceManager.GetString("ksInterlinImportPhase2of2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected file ({0}) may not be valid. Are you sure that you want to use it?.
		/// </summary>
		internal static string ksInvalidFileAreYouSure {
			get {
				return ResourceManager.GetString("ksInvalidFileAreYouSure", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Some of the selected file(s) ({0}) may not be valid SFM files. Are you sure that you want to use them?.
		/// </summary>
		internal static string ksInvalidInterlinearFiles {
			get {
				return ResourceManager.GetString("ksInvalidInterlinearFiles", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The file you selected ({0}) does not appear to be a valid LinguaLinks XML file. Please choose a valid LinguaLinks XML file..
		/// </summary>
		internal static string ksInvalidLLFile {
			get {
				return ResourceManager.GetString("ksInvalidLLFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex. Entries.
		/// </summary>
		internal static string ksLexEntries {
			get {
				return ResourceManager.GetString("ksLexEntries", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex. Entry.
		/// </summary>
		internal static string ksLexEntry {
			get {
				return ResourceManager.GetString("ksLexEntry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex. Gloss.
		/// </summary>
		internal static string ksLexGloss {
			get {
				return ResourceManager.GetString("ksLexGloss", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex./Word Cat..
		/// </summary>
		internal static string ksLexWordCat {
			get {
				return ResourceManager.GetString("ksLexWordCat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lex./Word Gloss.
		/// </summary>
		internal static string ksLexWordGloss {
			get {
				return ResourceManager.GetString("ksLexWordGloss", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lit. .
		/// </summary>
		internal static string ksLit_ {
			get {
				return ResourceManager.GetString("ksLit_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Literal Translation.
		/// </summary>
		internal static string ksLiteralTranslation {
			get {
				return ResourceManager.GetString("ksLiteralTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks Encoding Conversion.
		/// </summary>
		internal static string ksLLEncConv {
			get {
				return ResourceManager.GetString("ksLLEncConv", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks XML file ({0}) not found..
		/// </summary>
		internal static string ksLLFileNotFound {
			get {
				return ResourceManager.GetString("ksLLFileNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks Import.
		/// </summary>
		internal static string ksLLImport {
			get {
				return ResourceManager.GetString("ksLLImport", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks Import Failed.
		/// </summary>
		internal static string ksLLImportFailed {
			get {
				return ResourceManager.GetString("ksLLImportFailed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 1 of 5: character conversions.
		/// </summary>
		internal static string ksLLImportPhase1 {
			get {
				return ResourceManager.GetString("ksLLImportPhase1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 2 of 5: XML transformations.
		/// </summary>
		internal static string ksLLImportPhase2 {
			get {
				return ResourceManager.GetString("ksLLImportPhase2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 3 of 5: XML clean up.
		/// </summary>
		internal static string ksLLImportPhase3 {
			get {
				return ResourceManager.GetString("ksLLImportPhase3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 4 of 5: loading XML data into FieldWorks.
		/// </summary>
		internal static string ksLLImportPhase4 {
			get {
				return ResourceManager.GetString("ksLLImportPhase4", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phase 5 of 5: Finishing importing LinguaLinks texts.
		/// </summary>
		internal static string ksLLImportPhase5 {
			get {
				return ResourceManager.GetString("ksLLImportPhase5", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks Import Progress.
		/// </summary>
		internal static string ksLLImportProgress {
			get {
				return ResourceManager.GetString("ksLLImportProgress", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LinguaLinks Import Successful.
		/// </summary>
		internal static string ksLLImportSucceeded {
			get {
				return ResourceManager.GetString("ksLLImportSucceeded", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to LT .
		/// </summary>
		internal static string ksLT {
			get {
				return ResourceManager.GetString("ksLT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The match string is too long, and has been trimmed to the first 1000 characters..
		/// </summary>
		internal static string ksMatchStringTooLong {
			get {
				return ResourceManager.GetString("ksMatchStringTooLong", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Morphemes.
		/// </summary>
		internal static string ksMorphemes {
			get {
				return ResourceManager.GetString("ksMorphemes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Move Down.
		/// </summary>
		internal static string ksMoveDown {
			get {
				return ResourceManager.GetString("ksMoveDown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Move Up.
		/// </summary>
		internal static string ksMoveUp {
			get {
				return ResourceManager.GetString("ksMoveUp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to At least one field must be specified as containing Baseline text.
		/// </summary>
		internal static string ksMustHaveBaseline {
			get {
				return ResourceManager.GetString("ksMustHaveBaseline", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (Nameless text).
		/// </summary>
		internal static string ksNamelessText {
			get {
				return ResourceManager.GetString("ksNamelessText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You must have at least one field showing.
		/// </summary>
		internal static string ksNeedOneField {
			get {
				return ResourceManager.GetString("ksNeedOneField", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You cannot hide the Word line in this view.
		/// </summary>
		internal static string ksNeedWordLine {
			get {
				return ResourceManager.GetString("ksNeedWordLine", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New analysis.
		/// </summary>
		internal static string ksNewAnalysis {
			get {
				return ResourceManager.GetString("ksNewAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to    New word gloss.
		/// </summary>
		internal static string ksNewWordGloss {
			get {
				return ResourceManager.GetString("ksNewWordGloss", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New word gloss.
		/// </summary>
		internal static string ksNewWordGloss2 {
			get {
				return ResourceManager.GetString("ksNewWordGloss2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to there is no form!.
		/// </summary>
		internal static string ksNoForm {
			get {
				return ResourceManager.GetString("ksNoForm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to no morphemes.
		/// </summary>
		internal static string ksNoMorphemes {
			get {
				return ResourceManager.GetString("ksNoMorphemes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Note.
		/// </summary>
		internal static string ksNote {
			get {
				return ResourceManager.GetString("ksNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Note .
		/// </summary>
		internal static string ksNote_ {
			get {
				return ResourceManager.GetString("ksNote_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Notice.
		/// </summary>
		internal static string ksNotice {
			get {
				return ResourceManager.GetString("ksNotice", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nt .
		/// </summary>
		internal static string ksNt {
			get {
				return ResourceManager.GetString("ksNt", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Parsing.
		/// </summary>
		internal static string ksParsing {
			get {
				return ResourceManager.GetString("ksParsing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ph{0} {1}.
		/// </summary>
		internal static string ksPhaseButton {
			get {
				return ResourceManager.GetString("ksPhaseButton", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Possible Invalid File.
		/// </summary>
		internal static string ksPossibleInvalidFile {
			get {
				return ResourceManager.GetString("ksPossibleInvalidFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Interlinear (Step 1).
		/// </summary>
		internal static string ksPreparingInterlinear1 {
			get {
				return ResourceManager.GetString("ksPreparingInterlinear1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Interlinear (Step 2).
		/// </summary>
		internal static string ksPreparingInterlinear2 {
			get {
				return ResourceManager.GetString("ksPreparingInterlinear2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Interlinear (Step 3).
		/// </summary>
		internal static string ksPreparingInterlinear3 {
			get {
				return ResourceManager.GetString("ksPreparingInterlinear3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Interlinear (Step 4).
		/// </summary>
		internal static string ksPreparingInterlinear4 {
			get {
				return ResourceManager.GetString("ksPreparingInterlinear4", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Interlinear (Step 5).
		/// </summary>
		internal static string ksPreparingInterlinear5 {
			get {
				return ResourceManager.GetString("ksPreparingInterlinear5", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Problem.
		/// </summary>
		internal static string ksProblem {
			get {
				return ResourceManager.GetString("ksProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Process.
		/// </summary>
		internal static string ksProcess {
			get {
				return ResourceManager.GetString("ksProcess", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ???.
		/// </summary>
		internal static string ksQuestions {
			get {
				return ResourceManager.GetString("ksQuestions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo add allomorph.
		/// </summary>
		internal static string ksRedoAddAllomorph {
			get {
				return ResourceManager.GetString("ksRedoAddAllomorph", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to redo add allomorph to similar entry.
		/// </summary>
		internal static string ksRedoAddAllomorphToSimilarEntry {
			get {
				return ResourceManager.GetString("ksRedoAddAllomorphToSimilarEntry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo insert Freeform Translation.
		/// </summary>
		internal static string ksRedoAddFreeformTranslation {
			get {
				return ResourceManager.GetString("ksRedoAddFreeformTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo insert Literal Translation.
		/// </summary>
		internal static string ksRedoAddLiteralTranslation {
			get {
				return ResourceManager.GetString("ksRedoAddLiteralTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo insert Note.
		/// </summary>
		internal static string ksRedoAddNote {
			get {
				return ResourceManager.GetString("ksRedoAddNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Add Sense.
		/// </summary>
		internal static string ksRedoAddSense {
			get {
				return ResourceManager.GetString("ksRedoAddSense", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo add Text Tag.
		/// </summary>
		internal static string ksRedoAddTextTag {
			get {
				return ResourceManager.GetString("ksRedoAddTextTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Approve Analysis.
		/// </summary>
		internal static string ksRedoApproveAnalysis {
			get {
				return ResourceManager.GetString("ksRedoApproveAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Break Phrase into Words.
		/// </summary>
		internal static string ksRedoBreakPhrase {
			get {
				return ResourceManager.GetString("ksRedoBreakPhrase", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo {0}.
		/// </summary>
		internal static string ksRedoCommand {
			get {
				return ResourceManager.GetString("ksRedoCommand", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo remove Text Tag.
		/// </summary>
		internal static string ksRedoDeleteTextTag {
			get {
				return ResourceManager.GetString("ksRedoDeleteTextTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Guess Word Breaks.
		/// </summary>
		internal static string ksRedoGuessWordBreaks {
			get {
				return ResourceManager.GetString("ksRedoGuessWordBreaks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Insert Invisible Space.
		/// </summary>
		internal static string ksRedoInsertInvisibleSpace {
			get {
				return ResourceManager.GetString("ksRedoInsertInvisibleSpace", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Link Words into Phrase.
		/// </summary>
		internal static string ksRedoLinkWords {
			get {
				return ResourceManager.GetString("ksRedoLinkWords", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo insert Translation.
		/// </summary>
		internal static string ksRedoSetTransFromWordGlosses {
			get {
				return ResourceManager.GetString("ksRedoSetTransFromWordGlosses", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save Settings?.
		/// </summary>
		internal static string ksSaveSettingsCaption {
			get {
				return ResourceManager.GetString("ksSaveSettingsCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} (Heading).
		/// </summary>
		internal static string ksSectionHeading {
			get {
				return ResourceManager.GetString("ksSectionHeading", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected lexical entry ({0}) is a {1}..
		/// </summary>
		internal static string ksSelectedLexEntryXisaY {
			get {
				return ResourceManager.GetString("ksSelectedLexEntryXisaY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the SFM file to import.
		/// </summary>
		internal static string ksSelectInterlinFile {
			get {
				return ResourceManager.GetString("ksSelectInterlinFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the LinguaLinks/FieldWorks XML file to use.
		/// </summary>
		internal static string ksSelectLLFWXMLFile {
			get {
				return ResourceManager.GetString("ksSelectLLFWXMLFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the LinguaLinks XML file to use.
		/// </summary>
		internal static string ksSelectLLXMLFile {
			get {
				return ResourceManager.GetString("ksSelectLLXMLFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the mapping file with settings for this import operation.
		/// </summary>
		internal static string ksSelectMapFile {
			get {
				return ResourceManager.GetString("ksSelectMapFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the texts to be exported into a single document..
		/// </summary>
		internal static string ksSelectSectionsExported {
			get {
				return ResourceManager.GetString("ksSelectSectionsExported", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to There was a problem with the import. The system reported {0}..
		/// </summary>
		internal static string ksSfmImportProblem {
			get {
				return ResourceManager.GetString("ksSfmImportProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Showing only the first {0} matches, found in the first {1} of {2} paragraphs..
		/// </summary>
		internal static string ksShowingOnlyTheFirstXXXMatches {
			get {
				return ResourceManager.GetString("ksShowingOnlyTheFirstXXXMatches", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} of {1} Texts.
		/// </summary>
		internal static string ksSomeTexts {
			get {
				return ResourceManager.GetString("ksSomeTexts", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify Concordance Criteria.
		/// </summary>
		internal static string ksSpecifyConcordanceCriteria {
			get {
				return ResourceManager.GetString("ksSpecifyConcordanceCriteria", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify concordance criteria....
		/// </summary>
		internal static string ksSpecifyConcordanceCriteria_ {
			get {
				return ResourceManager.GetString("ksSpecifyConcordanceCriteria_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ***.
		/// </summary>
		internal static string ksStars {
			get {
				return ResourceManager.GetString("ksStars", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to [.
		/// </summary>
		internal static string ksStartTagSymbol {
			get {
				return ResourceManager.GetString("ksStartTagSymbol", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Texts &amp; Words Statistics (using chosen texts).
		/// </summary>
		internal static string ksStatisticsView_HeaderText {
			get {
				return ResourceManager.GetString("ksStatisticsView_HeaderText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Total number of sentences (segments):.
		/// </summary>
		internal static string ksStatisticsViewTotalSentencesText {
			get {
				return ResourceManager.GetString("ksStatisticsViewTotalSentencesText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Total word count (tokens):.
		/// </summary>
		internal static string ksStatisticsViewTotalWordTokensText {
			get {
				return ResourceManager.GetString("ksStatisticsViewTotalWordTokensText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Total number of unique words (types):.
		/// </summary>
		internal static string ksStatisticsViewTotalWordTypesText {
			get {
				return ResourceManager.GetString("ksStatisticsViewTotalWordTypesText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Successfully loaded {0} into {1}.{2}Look at {3} for details..
		/// </summary>
		internal static string ksSuccessLoadingLL {
			get {
				return ResourceManager.GetString("ksSuccessLoadingLL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Tagging.
		/// </summary>
		internal static string ksTagging {
			get {
				return ResourceManager.GetString("ksTagging", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Statistics.
		/// </summary>
		internal static string ksTextAreaStatisticsViewName {
			get {
				return ResourceManager.GetString("ksTextAreaStatisticsViewName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to texts.
		/// </summary>
		internal static string ksTexts {
			get {
				return ResourceManager.GetString("ksTexts", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Title.
		/// </summary>
		internal static string ksTitle {
			get {
				return ResourceManager.GetString("ksTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to To specify a Concordance, select a line in which to search and enter the text to search for..
		/// </summary>
		internal static string ksToSpecifyAConcordance_ {
			get {
				return ResourceManager.GetString("ksToSpecifyAConcordance_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem:  {0}.
		/// </summary>
		internal static string ksTransformProblem {
			get {
				return ResourceManager.GetString("ksTransformProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem (phase 1): {0}.
		/// </summary>
		internal static string ksTransformProblem1 {
			get {
				return ResourceManager.GetString("ksTransformProblem1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem (phase 2): {0}.
		/// </summary>
		internal static string ksTransformProblem2 {
			get {
				return ResourceManager.GetString("ksTransformProblem2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem (phase 3): {0}.
		/// </summary>
		internal static string ksTransformProblem3 {
			get {
				return ResourceManager.GetString("ksTransformProblem3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem (phase 3A): {0}.
		/// </summary>
		internal static string ksTransformProblem3A {
			get {
				return ResourceManager.GetString("ksTransformProblem3A", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Transformation problem (phase 3B): {0}.
		/// </summary>
		internal static string ksTransformProblem3B {
			get {
				return ResourceManager.GetString("ksTransformProblem3B", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The filter is being turned off so that you can see the new text..
		/// </summary>
		internal static string ksTurningOffFilter {
			get {
				return ResourceManager.GetString("ksTurningOffFilter", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo add allomorph.
		/// </summary>
		internal static string ksUndoAddAllomorph {
			get {
				return ResourceManager.GetString("ksUndoAddAllomorph", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to undo add allomorph to similar entry.
		/// </summary>
		internal static string ksUndoAddAllomorphToSimilarEntry {
			get {
				return ResourceManager.GetString("ksUndoAddAllomorphToSimilarEntry", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo insert Free Translation.
		/// </summary>
		internal static string ksUndoAddFreeformTranslation {
			get {
				return ResourceManager.GetString("ksUndoAddFreeformTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo insert Literal Translation.
		/// </summary>
		internal static string ksUndoAddLiteralTranslation {
			get {
				return ResourceManager.GetString("ksUndoAddLiteralTranslation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo insert Note.
		/// </summary>
		internal static string ksUndoAddNote {
			get {
				return ResourceManager.GetString("ksUndoAddNote", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Add Sense.
		/// </summary>
		internal static string ksUndoAddSense {
			get {
				return ResourceManager.GetString("ksUndoAddSense", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo add Text Tag.
		/// </summary>
		internal static string ksUndoAddTextTag {
			get {
				return ResourceManager.GetString("ksUndoAddTextTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo all changes in this Analysis.
		/// </summary>
		internal static string ksUndoAllChangesHere {
			get {
				return ResourceManager.GetString("ksUndoAllChangesHere", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Approve Analysis.
		/// </summary>
		internal static string ksUndoApproveAnalysis {
			get {
				return ResourceManager.GetString("ksUndoApproveAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Break Phrase into Words.
		/// </summary>
		internal static string ksUndoBreakPhrase {
			get {
				return ResourceManager.GetString("ksUndoBreakPhrase", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo {0}.
		/// </summary>
		internal static string ksUndoCommand {
			get {
				return ResourceManager.GetString("ksUndoCommand", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo remove Text Tag.
		/// </summary>
		internal static string ksUndoDeleteTextTag {
			get {
				return ResourceManager.GetString("ksUndoDeleteTextTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Guess Word Breaks.
		/// </summary>
		internal static string ksUndoGuessWordBreaks {
			get {
				return ResourceManager.GetString("ksUndoGuessWordBreaks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Insert Invisible Space.
		/// </summary>
		internal static string ksUndoInsertInvisibleSpace {
			get {
				return ResourceManager.GetString("ksUndoInsertInvisibleSpace", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Link Words into Phrase.
		/// </summary>
		internal static string ksUndoLinkWords {
			get {
				return ResourceManager.GetString("ksUndoLinkWords", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo insert Translation.
		/// </summary>
		internal static string ksUndoSetTransFromWordGlosses {
			get {
				return ResourceManager.GetString("ksUndoSetTransFromWordGlosses", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unhandled Error.
		/// </summary>
		internal static string ksUnhandledError {
			get {
				return ResourceManager.GetString("ksUnhandledError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unknown.
		/// </summary>
		internal static string ksUnknown {
			get {
				return ResourceManager.GetString("ksUnknown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Use default analysis.
		/// </summary>
		internal static string ksUseDefaultAnalysis {
			get {
				return ResourceManager.GetString("ksUseDefaultAnalysis", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Variant of....
		/// </summary>
		internal static string ksVariantOf_ {
			get {
				return ResourceManager.GetString("ksVariantOf_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning.
		/// </summary>
		internal static string ksWarning {
			get {
				return ResourceManager.GetString("ksWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Word.
		/// </summary>
		internal static string ksWord {
			get {
				return ResourceManager.GetString("ksWord", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Word Cat..
		/// </summary>
		internal static string ksWordCat {
			get {
				return ResourceManager.GetString("ksWordCat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Word Gloss.
		/// </summary>
		internal static string ksWordGloss {
			get {
				return ResourceManager.GetString("ksWordGloss", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to XML parsing problem (phase 4): {0}.
		/// </summary>
		internal static string ksXMLParsingProblem4 {
			get {
				return ResourceManager.GetString("ksXMLParsingProblem4", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected object has been deleted (possibly by another user on a networked computer). Refreshing..
		/// </summary>
		internal static string SelectedObjectHasBeenDeleted {
			get {
				return ResourceManager.GetString("SelectedObjectHasBeenDeleted", resourceCulture);
			}
		}
	}
}
