/*-----------------------------------------------------------------------*//*:Ignore in Surveyor
Copyright (C) 1999, 2001 SIL International. All rights reserved.

Distributable under the terms of either the Common Public License or the
GNU Lesser General Public License, as specified in the LICENSING.txt file.

File: AfDef.h
Responsibility: Shon Katzenberger
Last reviewed:

	Defines for the application framework. This should only contain preprocessor declarations
	so it can be used by .rc files.
-------------------------------------------------------------------------------*//*:End Ignore*/
#pragma once
#ifndef AfDef_H
#define AfDef_H 1


/***********************************************************************************************
	Command IDs

	Commands above 64K cannot be put on Win menus.

	Commands between 40000 and 50000 should be reserved for Visual Studio
	defined values (these are defined in .h files generated by Visual Studio).

	Commands between 50000 and 65535 are reserved for Windows menu list
	handling.
***********************************************************************************************/

#define kcidNil				0

// Windows MDI reserves ids 1-10, so start at 100

// command IDs
#define kwcidMinApp						100
#define kcidFileNew						100
#define kcidFileOpen					101
#define kcidFileClose					102
#define kcidFileSave					103
#define kcidFileSaveAs					104
#define kcidFileExit					105
#define kcidHelpAbout					106
#define kcidWndNew						107
#define kcidWndClose					108
#define kcidEditCut						109
#define kcidEditCopy					110
#define kcidEditPaste					111
#define kcidEditDel						112
#define kcidToolsShowClip				113
#define kcidEditUndo					114
#define kcidEditRedo					115
#define kcidFilePrint					116
#define kcidFilePrintSetup				117
#define kcidEditPasteSp					118
#define kcidEditSrch					119
#define kcidEditNextMatch				120
#define kcidEditPrevMatch				121
#define kcidEditRepl					122

// Bogus IDs that allow us to treat typing like commands:
#define kcidTyping						123
#define kcidDeleteKey					124

#define kcidFilePageSetup				125
#define kcidEditSelAll					126
#define kcidFmtFnt						127
#define kcidFmtWrtgSys					128
#define kcidFmtPara						129
#define kcidFmtBdr						130
#define kcidFmtBulNum					131
// Toolbar constants.
#define kcidFmttbStyle					132
#define kcidFmttbWrtgSys				133
#define kcidFmttbFnt					134
#define kcidFmttbFntSize				135
#define kcidFmttbBold                   136
#define kcidFmttbItal                   137
#define kcidFmttbAlignLeft              138
#define kcidFmttbAlignCntr              139
#define kcidFmttbAlignRight             140
#define kcidFmttbLstNum                 141
#define kcidFmttbLstBullet              142
#define kcidFmttbUnind                  143
#define kcidFmttbInd                    144
#define kcidFmttbApplyBdr               145
#define kcidFmttbApplyBgrndColor        146
#define kcidFmttbApplyFgrndColor        147
// New constants.
#define kcidInsPic                      148
#define kcidFmtStyles                   149
#define kcidEditSrchQuick				150
#define kcidToolsLists					151
#define kcidFmttbFocusStyleBox			152

#define kridShellDlg                    153 // Dialog
#define kridTBarFmtg                    154 // Bitmap

// Color defines.
#define kstidNinch                      1095
#define kstidBlack                      155
#define kstidBrown                      156
#define kstidDarkOliveGreen             157
#define kstidDarkGreen                  158
#define kstidDarkTeal                   159
#define kstidDarkBlue                   160
#define kstidIndigo                     161
#define kstidDarkGray                   162
#define kstidDarkRed                    163
#define kstidOrange                     164
#define kstidDarkYellow                 165
#define kstidGreen                      166
#define kstidTeal                       167
#define kstidBlue                       168
#define kstidBlueGray                   169
#define kstidGray40                     170
#define kstidRed                        171
#define kstidLightOrange                172
#define kstidLime                       173
#define kstidSeaGreen                   174
#define kstidAqua                       175
#define kstidLightBlue                  176
#define kstidViolet                     177
#define kstidGray50                     178
#define kstidPink                       179
#define kstidGold                       180
#define kstidYellow                     181
#define kstidBrightGreen                182
#define kstidTurquoise                  183
#define kstidSkyBlue                    184
#define kstidPlum                       185
#define kstidLightGray                  186
#define kstidRose                       187
#define kstidTan                        188
#define kstidLightYellow                189
#define kstidPaleGreen                  190
#define kstidPaleTurquoise              191
#define kstidPaleBlue                   192
#define kstidLavender                   193
#define kstidWhite                      194
#define kstidUnspecified                195
#define kstidUnknownColor				196
#define kcidFileNewLP					197
#define kcidFileBackup					198

#define kcidApplyNormalStyle			199
#define kcidViewRefresh					200
#define kridTBarStd                     201 // Bitmap
#define kstidMenu                       202
#define kstidTBarStd                    203
#define kstidTBarFmtg                   204
#define kstidTBarIns                    205
#define kstidTBarWnd                    206
#define kridTBarInvisible               207 // Bitmap
#define kridAccelStd                    208
#define kridTBarIns                     209 // Bitmap
#define kridTBarWnd                     210 // Bitmap
#define kcidHelpWhatsThis               211
#define kcidFilePrintPrevw              212
#define kcidWndSideBy                   213
#define kcidWndTile						214
#define kcidWndCascad					215

#define kridAppMenu                     216

// After the menu, we need to leave a gap to allow for our Menu Manager class to allocate
// accelerator IDs to the main menu top level items. The gap size has been decided at 20.
// Therefore, no IDs other than kridAppMenu should have a value less than 236.
#define kcidStats						237
#define kridNoHelpShellDlg              238		// Dialog

// DO NOT GO ABOVE 999 since applications use this range.

// Control IDs. According to WinUser.h, IDOK = 1 and IDCANCEL = 2.
#define kctidOk             IDOK
#define kctidCancel         IDCANCEL

#define kwcidListBase       50000 // For windows menu list handling.
#define kdwcidList          500 // Increment between list base values.
#define kwcidLimApp         0xF000 // Windows reserves larger values.


//:>********************************************************************************************
//:>	Non-menu, non-key invoked commands. These commands cannot be put on menus.
//:>********************************************************************************************
#define kcidMinNoMenu           100000

#define kcidIdle                100000

#define kcidColorChange         100001
#define kcidEndColorChange      100002
#define kcidSettingChange       100003
#define kcidEndSettingChange    100004

#define kcidSelIdle             100005

#endif // !AfDef_H
