//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.WordWorks.Parser {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ParserCoreStrings {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ParserCoreStrings() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.WordWorks.Parser.ParserCoreStrings", typeof(ParserCoreStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating {0}.
		/// </summary>
		internal static string ksCreatingX {
			get {
				return ResourceManager.GetString("ksCreatingX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to error encountered.
		/// </summary>
		internal static string ksErrorEncountered {
			get {
				return ResourceManager.GetString("ksErrorEncountered", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to finished.
		/// </summary>
		internal static string ksFinished {
			get {
				return ResourceManager.GetString("ksFinished", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The parser gave the following cryptic message (you may need to contact FieldWorks support to know what it means): {0}.
		/// </summary>
		internal static string ksHCDefaultErrorMsg {
			get {
				return ResourceManager.GetString("ksHCDefaultErrorMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The phoneme {0} of lexical entry {1} is not defined.  Please make sure all phonemes in all allomorphs of all entries have been defined..
		/// </summary>
		internal static string ksHCInvalidEntryShape {
			get {
				return ResourceManager.GetString("ksHCInvalidEntryShape", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The phoneme {0} of affix {1} is not defined.  Please make sure all phonemes in all allomorphs of all affixes have been defined..
		/// </summary>
		internal static string ksHCInvalidRuleShape {
			get {
				return ResourceManager.GetString("ksHCInvalidRuleShape", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to At least one of the phonemes in the word {0} is not defined.  Please make sure all phonemes in the word have been defined..
		/// </summary>
		internal static string ksHCInvalidWordform {
			get {
				return ResourceManager.GetString("ksHCInvalidWordform", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to A phonological rule is using a feature variable for feature {0}, but there is no corresponding feature variable in the environment..
		/// </summary>
		internal static string ksHCUninstFeature {
			get {
				return ResourceManager.GetString("ksHCUninstFeature", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string ksIdle_ {
			get {
				return ResourceManager.GetString("ksIdle_", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Making HC Files.
		/// </summary>
		internal static string ksMakingHCFiles {
			get {
				return ResourceManager.GetString("ksMakingHCFiles", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Making XAmple Files.
		/// </summary>
		internal static string ksMakingXAmpleFiles {
			get {
				return ResourceManager.GetString("ksMakingXAmpleFiles", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preparing Templates for XAmple Files.
		/// </summary>
		internal static string ksPreparingTemplatesForXAmple {
			get {
				return ResourceManager.GetString("ksPreparingTemplatesForXAmple", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ???.
		/// </summary>
		internal static string ksQuestions {
			get {
				return ResourceManager.GetString("ksQuestions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maximum permitted analyses ({0}) reached..
		/// </summary>
		internal static string ksReachedMaxAnalysesAllowed {
			get {
				return ResourceManager.GetString("ksReachedMaxAnalysesAllowed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Maximum internal buffer size ({0}) reached..
		/// </summary>
		internal static string ksReachedMaxInternalBufferSize {
			get {
				return ResourceManager.GetString("ksReachedMaxInternalBufferSize", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Grammar and Lexicon.
		/// </summary>
		internal static string ksRetrievingGrammarAndLexicon {
			get {
				return ResourceManager.GetString("ksRetrievingGrammarAndLexicon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Retrieving Template Information.
		/// </summary>
		internal static string ksRetrievingTemplateInformation {
			get {
				return ResourceManager.GetString("ksRetrievingTemplateInformation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to started.
		/// </summary>
		internal static string ksStarted {
			get {
				return ResourceManager.GetString("ksStarted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trying Wordform {0}.
		/// </summary>
		internal static string ksTraceWordformX {
			get {
				return ResourceManager.GetString("ksTraceWordformX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating: {0}.
		/// </summary>
		internal static string ksUpdateX {
			get {
				return ResourceManager.GetString("ksUpdateX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updating Grammar and Lexicon.
		/// </summary>
		internal static string ksUpdatingGrammarAndLexicon {
			get {
				return ResourceManager.GetString("ksUpdatingGrammarAndLexicon", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}: error.
		/// </summary>
		internal static string ksX_error {
			get {
				return ResourceManager.GetString("ksX_error", resourceCulture);
			}
		}
	}
}
