// PythonEC.idl : IDL source for PythonEC
//

// This file will be processed by the MIDL tool to
// produce the type library (PythonEC.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(28A1F0A9-82F2-4B95-A3A6-BB69DB118D9C),
	version(4.0),
	helpstring("Python IEncConverter implementation 4.0 Type Library")
]
library PythonECLib
{
	importlib("stdole2.tlb");
	importlib("ECInterfaces.tlb");

	[
		uuid(EE62A6CB-B2CA-4D1F-90BE-FFA6569E550C)
		, helpstring("Python Script IEncConverter implementation class")
		, hidden
	]
	coclass PyScriptEncConverter
	{
		[default] interface IEncConverter;
	};

	[
		uuid(025E6162-9B43-4725-A8B2-2BFD451079AD)
		, helpstring("Python Script IEncConverterConfig implementation class")
		, hidden
	]
	coclass PyScriptEncConverterConfig
	{
		[default] interface IEncConverterConfig;
	};
};
