# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "webonary.box"
  config.vm.box_url = "https://googledrive.com/host/0BwTQrVjXe5wbYWZJd0dLMmZhVGs/precise_64_webonary_zend.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # increase memory and cpu settings
  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
	v.cpus = 2
	# Uncomment the v.gui line to gain access to this box through VirtualBox
#	v.gui = true
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../../sil-dictionary-webonary/trunk", "/var/www/wp-content/plugins/sil-dictionary-webonary"

end
