//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool - however, it has been heavily massaged, since the tool is kind of broken -NaylorJ
//     Runtime Version:2.0.50727.5446
//
//     Should it become necessary to regenerate this file be aware of the following changes:
//	   1. The namespace needs to be added to allow compilation
//     2. The xsd.exe tool doesn't always properly handle sequences of unbounded objects, several fields were generated as 2 dimensional arrays
//         when they should have been normal arrays. Those members and their annotations need to be modified by hand.
//     3. The knownItemTypes enumeration was pulled from an earlier version of the schema prior to unioning the type with string
//     4. The names have been changed to protect the innocent developers who wouldn't like the looooong generated type names.
//         mostly all the unnecessary prefixing of type names have been removed, and document was changed to BIRDDocument.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=2.0.50727.1432. and modified by Jason Naylor Version=1.0
//

namespace SIL.FieldWorks.IText.FlexInterlinModel
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "document")]
	public partial class BIRDDocument
	{

		private Interlineartext[] interlineartextField;

		private string exportSourceField;

		private string exportTargetField;

		private string versionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("interlinear-text", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Interlineartext[] interlineartext
		{
			get
			{
				return this.interlineartextField;
			}
			set
			{
				this.interlineartextField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string exportSource
		{
			get
			{
				return this.exportSourceField;
			}
			set
			{
				this.exportSourceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string exportTarget
		{
			get
			{
				return this.exportTargetField;
			}
			set
			{
				this.exportTargetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "interlinear-text")]
	public partial class Interlineartext
	{

		private item[] itemField;

		private Paragraph[] paragraphsField;

		private Languages languagesField;

		private MediaFiles mediaFilesField;

		private string guidField;

		private scrSectionTypes scrSectionTypeField;

		private bool scrSectionTypeFieldSpecified;

		private string scrBookField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("item", IsNullable = true)]
		public item[] Items
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("paragraph", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public Paragraph[] paragraphs
		{
			get
			{
				return this.paragraphsField;
			}
			set
			{
				this.paragraphsField = value;
			}
		}
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("languages", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Languages languages
		{
			get
			{
				return this.languagesField;
			}
			set
			{
				this.languagesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("media-files", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public MediaFiles mediafiles
		{
			get
			{
				return this.mediaFilesField;
			}
			set
			{
				this.mediaFilesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid
		{
			get
			{
				return this.guidField;
			}
			set
			{
				this.guidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public scrSectionTypes scrSectionType
		{
			get
			{
				return this.scrSectionTypeField;
			}
			set
			{
				this.scrSectionTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool scrSectionTypeSpecified
		{
			get
			{
				return this.scrSectionTypeFieldSpecified;
			}
			set
			{
				this.scrSectionTypeFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string scrBook
		{
			get
			{
				return this.scrBookField;
			}
			set
			{
				this.scrBookField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
	public partial class item
	{

		private string typeField;

		private string langField;

		private analysisStatusTypes analysisStatusField;

		private bool analysisStatusFieldSpecified;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public analysisStatusTypes analysisStatus
		{
			get
			{
				return this.analysisStatusField;
			}
			set
			{
				this.analysisStatusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool analysisStatusSpecified
		{
			get
			{
				return this.analysisStatusFieldSpecified;
			}
			set
			{
				this.analysisStatusFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	public enum analysisStatusTypes
	{

		/// <remarks/>
		humanApproved,

		/// <remarks/>
		guess,

		/// <remarks/>
		guessByHumanApproved,

		/// <remarks/>
		guessByStatisticalAnalysis,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "paragraph")]
	public partial class Paragraph
	{

		private Phrase[] phrasesField;

		private string guidField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("phrase", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public Phrase[] phrases
		{
			get
			{
				return this.phrasesField;
			}
			set
			{
				this.phrasesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid
		{
			get
			{
				return this.guidField;
			}
			set
			{
				this.guidField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "phrase")]
	public partial class Phrase
	{

		private WordsContent _wordsContentField;

		private item[] itemField;

		[System.Xml.Serialization.XmlAttributeAttribute("begin-time-offset")]
		public string beginTimeOffset;

		[System.Xml.Serialization.XmlAttributeAttribute("end-time-offset")]
		public string endTimeOffset;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string speaker;

		[System.Xml.Serialization.XmlAttributeAttribute("media-file")]
		public string mediaFile;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid;

		/// <remarks/>		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("item", IsNullable = true)]
		public item[] Items
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("words", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public WordsContent WordsContent
		{
			get
			{
				return this._wordsContentField;
			}
			set
			{
				this._wordsContentField = value;
			}
		}


	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "words")]
	public partial class WordsContent
	{
		private ScrMilestone[] scrMilestoneField;

		private Word[] wordField;


		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("scrMilestone", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ScrMilestone[] scrMilestone
		{
			get
			{
				return this.scrMilestoneField;
			}
			set
			{
				this.scrMilestoneField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("word", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Word[] Words
		{
			get
			{
				return this.wordField;
			}
			set
			{
				this.wordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ScrMilestone
	{

		private string chapterField;

		private string verseField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string chapter
		{
			get
			{
				return this.chapterField;
			}
			set
			{
				this.chapterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
		public string verse
		{
			get
			{
				return this.verseField;
			}
			set
			{
				this.verseField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "word")]
	public partial class Word
	{

		private item[] itemField;

		private Morphemes morphemesField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid;

		private string typeField;

		public Word()
		{
			this.typeField = "phrase";
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("item", IsNullable = true)]
		public item[] Items
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("morphemes", typeof(Morphemes), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Morphemes morphemes
		{
			get
			{
				return this.morphemesField;
			}
			set
			{
				this.morphemesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class Morphemes
	{

		private Morph[] morphField;

		private analysisStatusTypes analysisStatusField;

		private bool analysisStatusFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("morph", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Morph[] morphs
		{
			get
			{
				return this.morphField;
			}
			set
			{
				this.morphField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public analysisStatusTypes analysisStatus
		{
			get
			{
				return this.analysisStatusField;
			}
			set
			{
				this.analysisStatusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool analysisStatusSpecified
		{
			get
			{
				return this.analysisStatusFieldSpecified;
			}
			set
			{
				this.analysisStatusFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class Morph
	{

		private item[] itemField;

		private morphTypes typeField;

		private bool typeFieldSpecified;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public item[] items
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public morphTypes type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool typeSpecified
		{
			get
			{
				return this.typeFieldSpecified;
			}
			set
			{
				this.typeFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	public enum morphTypes
	{

		/// <remarks/>
		particle,

		/// <remarks/>
		infix,

		/// <remarks/>
		prefix,

		/// <remarks/>
		simulfix,

		/// <remarks/>
		suffix,

		/// <remarks/>
		suprafix,

		/// <remarks/>
		circumfix,

		/// <remarks/>
		clitic,

		/// <remarks/>
		enclitic,

		/// <remarks/>
		proclitic,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("bound root")]
		boundroot,

		/// <remarks/>
		root,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("bound stem")]
		boundstem,

		/// <remarks/>
		stem,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("infixing interfix")]
		infixinginterfix,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("prefixing interfix")]
		prefixinginterfix,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("suffixing interfix")]
		suffixinginterfix,

		/// <remarks/>
		phrase,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("discontiguous phrase")]
		discontiguousphrase,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class Language
	{

		private string langField;

		private string encodingField;

		private string fontField;

		private bool vernacularField;

		private bool vernacularFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string encoding
		{
			get
			{
				return this.encodingField;
			}
			set
			{
				this.encodingField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string font
		{
			get
			{
				return this.fontField;
			}
			set
			{
				this.fontField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool vernacular
		{
			get
			{
				return this.vernacularField;
			}
			set
			{
				this.vernacularField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vernacularSpecified
		{
			get
			{
				return this.vernacularFieldSpecified;
			}
			set
			{
				this.vernacularFieldSpecified = value;
			}
		}
	}

	[System.SerializableAttribute()]
	//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "media-files")]
	public partial class MediaFiles
	{
		private MediaFile[] mediaField;

		private string offsetTypeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public MediaFile[] media
		{
			get
			{
				return this.mediaField;
			}
			set
			{
				this.mediaField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string offsetType
		{
			get
			{
				return this.offsetTypeField;
			}
			set
			{
				this.offsetTypeField = value;
			}
		}
	}

	[System.SerializableAttribute()]
	//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, TypeName = "media")]
	public partial class MediaFile
	{
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string guid;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string location;
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	public enum scrSectionTypes
	{

		/// <remarks/>
		title,

		/// <remarks/>
		heading,

		/// <remarks/>
		verseText,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
	[System.SerializableAttribute()]
	//	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class Languages
	{

		private Language[] languageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Language[] language
		{
			get
			{
				return this.languageField;
			}
			set
			{
				this.languageField = value;
			}
		}
	}


	/// <remarks>
	/// This enumeration is just for convenience and not actually generated by the schema.
	///
	/// </remarks>
	public enum KnownItemTypes
	{

		/// <remarks/>
		txt,

		/// <remarks/>
		cf,

		/// <remarks/>
		hn,

		/// <remarks/>
		variantTypes,

		/// <remarks/>
		gls,

		/// <remarks/>
		msa,

		/// <remarks/>
		pos,

		/// <remarks/>
		title,

		/// <remarks/>
		description,

		/// <remarks/>
		punct,
	}
}