//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILConvertersOffice.Properties {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Specialized.StringCollection RecentFindWhat {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["RecentFindWhat"]));
			}
			set {
				this["RecentFindWhat"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Specialized.StringCollection RecentReplaceWith {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["RecentReplaceWith"]));
			}
			set {
				this["RecentReplaceWith"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Specialized.StringCollection ConverterMappingRecentFiles {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["ConverterMappingRecentFiles"]));
			}
			set {
				this["ConverterMappingRecentFiles"] = value;
			}
		}
	}
}
