//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.CoreImpl {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class CoreImplStrings {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal CoreImplStrings() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.CoreImpl.CoreImplStrings", typeof(CoreImplStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks is unable to save some writing system settings because access to {0} is not authorized. This may cause unexpected behavior, and may be indicative of a wider problem with access permissions that could cause program crashes..
		/// </summary>
		internal static string ksCannotWriteWritingSystemInfo {
			get {
				return ResourceManager.GetString("ksCannotWriteWritingSystemInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The value is too long to store, so it has been truncated to the first {0} characters..
		/// </summary>
		internal static string ksTruncatedToXXXCharacters {
			get {
				return ResourceManager.GetString("ksTruncatedToXXXCharacters", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning.
		/// </summary>
		internal static string ksWarning {
			get {
				return ResourceManager.GetString("ksWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to # List of all regions in the IANA language subtag registry as of 2010-03-25
		///# Obtained from langtag.net
		///
		///AA	2005-10-16	Private use
		///AC	2009-07-29	Ascension Island
		///AD	2005-10-16	Andorra
		///AE	2005-10-16	United Arab Emirates
		///AF	2005-10-16	Afghanistan
		///AG	2005-10-16	Antigua and Barbuda
		///AI	2005-10-16	Anguilla
		///AL	2005-10-16	Albania
		///AM	2005-10-16	Armenia
		///AN	2005-10-16	Netherlands Antilles
		///AO	2005-10-16	Angola
		///AQ	2005-10-16	Antarctica
		///AR	2005-10-16	Argentina
		///AS	2005-10-16	American Samoa
		///AT	2005-10-16	A [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string regions {
			get {
				return ResourceManager.GetString("regions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to # List of all variants in the IANA language subtag registry as of 2010-03-25
		///# Obtained from langtag.net
		///# Plus x-AUDIO for FLEx and WeSay
		///
		///1606nict	2007-03-20	Late Middle French (to 1606)	frm
		///1694acad	2007-03-20	Early Modern French	fr
		///1901	2005-10-16	Traditional German orthography	de
		///1959acad	2008-09-30	&quot;Academic&quot; (&quot;governmental&quot;) variant of Belarusian as  codified in 1959	be
		///1994	2007-07-28	Standardized Resian orthography	sl-rozaj / sl-rozaj-biske / sl-rozaj-njiva / sl-rozaj-osojs / sl-rozaj-solba [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string variants {
			get {
				return ResourceManager.GetString("variants", resourceCulture);
			}
		}
	}
}
