<?xml version="1.0" encoding="UTF-8"?>
<!--
	xml2LaTeX.xsl

	Converts the flextext intermediate XML produced by FLEx's interlinear
	export into a standalone LaTeX document using the gb4e package's
	\ea / \gll / \glt / \z interlinear-example macros.

	This is XSLT 1.0 only (run through System.Xml.Xsl.XslCompiledTransform,
	the same engine FLEx uses). No replace(), no XPath 2.0/3.0 constructs.
-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output method="text" encoding="UTF-8"/>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		Root: emit a compilable document wrapper, then walk every text.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template match="/">
		<xsl:text>% Generated by FieldWorks' LaTeX (gb4e) interlinear export.
% Everything between a \ea and its matching \z is a self-contained
% gb4e interlinear example; copy just those blocks into an existing
% paper if you don't need this file's own preamble.
% Zero-width spaces (not representable under inputenc) were removed
% during export; a '?' marks a character that was already corrupt in
% the source project's data, not something lost by this export.
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{gb4e}
\begin{document}
</xsl:text>
		<xsl:apply-templates select="document/interlinear-text"/>
		<xsl:text>\end{document}
</xsl:text>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		One interlinear-text: a title comment, then its phrases.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template match="interlinear-text">
		<xsl:if test="string-length(normalize-space(item[@type='title'][1])) &gt; 0">
			<xsl:text>
% ===== </xsl:text>
			<xsl:call-template name="escape-only">
				<xsl:with-param name="text" select="normalize-space(item[@type='title'][1])"/>
			</xsl:call-template>
			<xsl:text> =====
</xsl:text>
		</xsl:if>
		<xsl:apply-templates select="paragraphs/paragraph/phrases/phrase"/>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		One phrase: \ea ... \z block.

		Template (literal, do not embellish):
			\ea
			<baseline> \\
			\gll <morphemes> \\
			<lex glosses> \\
			\glt <free translation>
			\z
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template match="phrase">
		<xsl:text>\ea
</xsl:text>
		<xsl:choose>
			<xsl:when test="string-length(normalize-space(item[@type='txt'][1])) &gt; 0">
				<xsl:call-template name="escape-only">
					<xsl:with-param name="text" select="normalize-space(item[@type='txt'][1])"/>
				</xsl:call-template>
			</xsl:when>
			<xsl:otherwise>
				<xsl:call-template name="baseline-line"/>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:text> \\
\gll </xsl:text>
		<xsl:call-template name="morph-line"/>
		<xsl:text> \\
</xsl:text>
		<xsl:call-template name="gloss-line"/>
		<xsl:text> \\
\glt </xsl:text>
		<xsl:call-template name="escape-only">
			<xsl:with-param name="text" select="normalize-space(item[@type='gls'][1])"/>
		</xsl:call-template>
		<xsl:text>
\z
</xsl:text>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		morph-line: first \gll line: one token per word, in document
		order. A word's token is its morphemes' txt values concatenated
		in order (affix/clitic markers are already embedded in each
		morph's txt, so plain concatenation is correct); an unanalyzed
		word's token is its own txt. If a word has neither morphemes
		nor its own txt (a gloss-only "ghost" word), that concatenation
		is empty, and "{}" stands in for it (the mirror image of
		gloss-line's own missing-gloss placeholder) so that every
		non-punctuation word still contributes exactly one token here,
		keeping this line's token count aligned with gloss-line's. A
		punctuation pseudo-word has no token of its own; its (escaped)
		text is appended directly to whichever token precedes it, with
		no space, or, if it is the very first word(s) in the phrase,
		prepended to the first real word's token, again with no space.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="morph-line">
		<xsl:for-each select="words/word">
			<xsl:choose>
				<xsl:when test="item[@type='punct']">
					<xsl:call-template name="escape-token">
						<xsl:with-param name="text" select="normalize-space(item[@type='punct'][1])"/>
					</xsl:call-template>
				</xsl:when>
				<xsl:otherwise>
					<xsl:variable name="token">
						<xsl:choose>
							<xsl:when test="morphemes/morph">
								<xsl:for-each select="morphemes/morph">
									<xsl:call-template name="escape-token">
										<xsl:with-param name="text" select="normalize-space(item[@type='txt'][1])"/>
									</xsl:call-template>
								</xsl:for-each>
							</xsl:when>
							<xsl:otherwise>
								<xsl:call-template name="escape-token">
									<xsl:with-param name="text" select="normalize-space(item[@type='txt'][1])"/>
								</xsl:call-template>
							</xsl:otherwise>
						</xsl:choose>
					</xsl:variable>
					<xsl:if test="count(preceding-sibling::word[not(item[@type='punct'])]) &gt; 0">
						<xsl:text> </xsl:text>
					</xsl:if>
					<xsl:choose>
						<xsl:when test="string-length($token) = 0">
							<xsl:text>{}</xsl:text>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="$token"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:for-each>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		baseline-line: assembled fallback for the phrase's own baseline
		prose line, used only when the phrase has no phrase-level
		item[@type='txt'] (the normal case for real FLEx exports). Each
		word contributes its own txt (a punctuation pseudo-word
		contributes its punct text instead), escaped via escape-only
		(prose, not a \gll token: no brace-grouping). Adjacency is the
		same rule morph-line uses: a single space separates consecutive
		non-punctuation words, and punctuation attaches directly to
		whichever side has no intervening space, whether it precedes or
		follows the first real word.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="baseline-line">
		<xsl:for-each select="words/word">
			<xsl:choose>
				<xsl:when test="item[@type='punct']">
					<xsl:call-template name="escape-only">
						<xsl:with-param name="text" select="normalize-space(item[@type='punct'][1])"/>
					</xsl:call-template>
				</xsl:when>
				<xsl:otherwise>
					<xsl:if test="count(preceding-sibling::word[not(item[@type='punct'])]) &gt; 0">
						<xsl:text> </xsl:text>
					</xsl:if>
					<xsl:call-template name="escape-only">
						<xsl:with-param name="text" select="normalize-space(item[@type='txt'][1])"/>
					</xsl:call-template>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:for-each>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		gloss-line: second \gll line: one token per non-punctuation
		word, aligned 1:1 with morph-line's tokens. A word's token is
		its morphemes' gls values joined by the boundary marker implied
		by the *following* morph's txt ("=" if that txt starts with
		"=", otherwise "-"); an unanalyzed word's token is its own gls.
		A missing gls anywhere becomes "{}" so the column survives.
		Punctuation pseudo-words contribute no token at all.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="gloss-line">
		<xsl:for-each select="words/word[not(item[@type='punct'])]">
			<xsl:if test="position() != 1">
				<xsl:text> </xsl:text>
			</xsl:if>
			<xsl:choose>
				<xsl:when test="morphemes/morph">
					<xsl:for-each select="morphemes/morph">
						<xsl:if test="position() != 1">
							<xsl:choose>
								<xsl:when test="starts-with(normalize-space(item[@type='txt'][1]), '=')">
									<xsl:text>=</xsl:text>
								</xsl:when>
								<xsl:otherwise>
									<xsl:text>-</xsl:text>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:if>
						<xsl:call-template name="emit-gloss-or-placeholder">
							<xsl:with-param name="gls" select="item[@type='gls'][1]"/>
						</xsl:call-template>
					</xsl:for-each>
				</xsl:when>
				<xsl:otherwise>
					<xsl:call-template name="emit-gloss-or-placeholder">
						<xsl:with-param name="gls" select="item[@type='gls'][1]"/>
					</xsl:call-template>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:for-each>
	</xsl:template>
	<!--
		emit-gloss-or-placeholder: "{}" for a missing/blank gloss,
		otherwise the escaped (and, if it contains a space, brace-
		grouped) gloss text.
	-->
	<xsl:template name="emit-gloss-or-placeholder">
		<xsl:param name="gls"/>
		<xsl:choose>
			<xsl:when test="string-length(normalize-space($gls)) = 0">
				<xsl:text>{}</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:call-template name="escape-token">
					<xsl:with-param name="text" select="normalize-space($gls)"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		clean-source: strip characters inputenc/pdflatex cannot represent,
		before any LaTeX escaping happens. Both escape-only and
		escape-token route through this first, so it covers every emitted
		value (baseline, morpheme line, gloss line, free translation,
		title). U+200B (zero width space) renders as nothing and can sit
		inside a word, so it is deleted outright rather than escaped.
		U+FFFD (replacement character) marks pre-existing corruption in
		the source project's data (curly quotes/apostrophes lost in an
		earlier import), not something this export produces, so it is
		normalized to a plain '?' instead of erroring pdflatex out.

		translate() maps by POSITION, and a source character with no
		counterpart in the shorter replacement string is deleted. So
		U+FFFD must come FIRST to receive the '?', leaving U+200B
		without a counterpart and therefore dropped. Reversing these two
		silently does the opposite: it stamps a visible '?' into the
		vernacular wherever a zero width space occurred.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="clean-source">
		<xsl:param name="text"/>
		<xsl:value-of select="translate($text, '&#xFFFD;&#x200B;', '?')"/>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		escape-only: LaTeX-escape a value that stands on its own line
		(baseline, free translation, title). No brace-grouping; these
		are ordinary prose, not \gll-aligned tokens.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="escape-only">
		<xsl:param name="text"/>
		<xsl:variable name="cleaned">
			<xsl:call-template name="clean-source">
				<xsl:with-param name="text" select="$text"/>
			</xsl:call-template>
		</xsl:variable>
		<xsl:call-template name="escape-latex">
			<xsl:with-param name="text" select="$cleaned"/>
		</xsl:call-template>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		escape-token: LaTeX-escape a value that will become (part of) a
		\gll-line token, then brace-group it if it still contains a
		space: gb4e's \getwords splits on spaces, and a braced group
		is opaque to that split (cgloss4e.sty), so "{go up}" survives
		as one token where a bare "go up" would not.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="escape-token">
		<xsl:param name="text"/>
		<xsl:variable name="cleaned">
			<xsl:call-template name="clean-source">
				<xsl:with-param name="text" select="$text"/>
			</xsl:call-template>
		</xsl:variable>
		<xsl:variable name="escaped">
			<xsl:call-template name="escape-latex">
				<xsl:with-param name="text" select="$cleaned"/>
			</xsl:call-template>
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="contains($escaped, ' ')">
				<xsl:text>{</xsl:text>
				<xsl:value-of select="$escaped"/>
				<xsl:text>}</xsl:text>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$escaped"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		escape-latex: recursive, single character-by-character pass so
		that a character's own replacement text (e.g. the braces in
		"\textbackslash{}") is never rescanned and re-escaped. Order is
		irrelevant to correctness here (each input character is
		classified exactly once), but backslash is listed first to
		match the source rule it implements.
		- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	-->
	<xsl:template name="escape-latex">
		<xsl:param name="text"/>
		<xsl:if test="string-length($text) &gt; 0">
			<xsl:variable name="ch" select="substring($text, 1, 1)"/>
			<xsl:choose>
				<xsl:when test="$ch = '\'">
					<xsl:text>\textbackslash{}</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '{'">
					<xsl:text>\{</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '}'">
					<xsl:text>\}</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '&amp;'">
					<xsl:text>\&amp;</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '%'">
					<xsl:text>\%</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '$'">
					<xsl:text>\$</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '#'">
					<xsl:text>\#</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '_'">
					<xsl:text>\_</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '~'">
					<xsl:text>\textasciitilde{}</xsl:text>
				</xsl:when>
				<xsl:when test="$ch = '^'">
					<xsl:text>\textasciicircum{}</xsl:text>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$ch"/>
				</xsl:otherwise>
			</xsl:choose>
			<xsl:call-template name="escape-latex">
				<xsl:with-param name="text" select="substring($text, 2)"/>
			</xsl:call-template>
		</xsl:if>
	</xsl:template>
</xsl:stylesheet>
