//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.Common.Controls {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class FwControls {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal FwControls() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.Common.Controls.FwControls", typeof(FwControls).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap CheckBox {
			get {
				object obj = ResourceManager.GetObject("CheckBox", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap CheckBoxCheck {
			get {
				object obj = ResourceManager.GetObject("CheckBoxCheck", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized string similar to OK will create an empty text.
		/// </summary>
		internal static string kOkbtnEmptySelection {
			get {
				return ResourceManager.GetString("kOkbtnEmptySelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to OK will create an empty text assigned to these genres.
		/// </summary>
		internal static string kOkbtnGenreSelection {
			get {
				return ResourceManager.GetString("kOkbtnGenreSelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No texts are selected.
		/// </summary>
		internal static string kOkbtnNoTextSelection {
			get {
				return ResourceManager.GetString("kOkbtnNoTextSelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Bible.
		/// </summary>
		internal static string kstidBibleNode {
			get {
				return ResourceManager.GetString("kstidBibleNode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to None of the above.
		/// </summary>
		internal static string kstidLangNoneAbove {
			get {
				return ResourceManager.GetString("kstidLangNoneAbove", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No matches were found.{0}You may wish to try a different spelling or word order, or a less specific name.{0}If you are searching for countries, note that USA is used rather than United States, United Kingdom rather than UK or Britain..
		/// </summary>
		internal static string kstidLangNotFound {
			get {
				return ResourceManager.GetString("kstidLangNotFound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No matches.
		/// </summary>
		internal static string kstidLangNotFoundCaption {
			get {
				return ResourceManager.GetString("kstidLangNotFoundCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Testament.
		/// </summary>
		internal static string kstidNtNode {
			get {
				return ResourceManager.GetString("kstidNtNode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Old Testament.
		/// </summary>
		internal static string kstidOtNode {
			get {
				return ResourceManager.GetString("kstidOtNode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Step 1.
		/// </summary>
		internal static string kstidStep1 {
			get {
				return ResourceManager.GetString("kstidStep1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Step 2.
		/// </summary>
		internal static string kstidStep2 {
			get {
				return ResourceManager.GetString("kstidStep2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Step 3.
		/// </summary>
		internal static string kstidStep3 {
			get {
				return ResourceManager.GetString("kstidStep3", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Fi&amp;nish.
		/// </summary>
		internal static string kstidWizFinishButtonText {
			get {
				return ResourceManager.GetString("kstidWizFinishButtonText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Next &gt;.
		/// </summary>
		internal static string kstidWizForwardButtonText {
			get {
				return ResourceManager.GetString("kstidWizForwardButtonText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Step {0} of {1}.
		/// </summary>
		internal static string kstidWizStepLabel {
			get {
				return ResourceManager.GetString("kstidWizStepLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Pg. {0}.
		/// </summary>
		internal static string kstidWizTabPage {
			get {
				return ResourceManager.GetString("kstidWizTabPage", resourceCulture);
			}
		}
	}
}
