#!/bin/bash
set -xueo pipefail
cd "$(dirname "$0")"

XDG_CACHE_HOME="${XDG_CACHE_HOME-"${HOME}/.cache"}"
LOG_DIR="${XDG_CACHE_HOME}/flatpak-build-logs"
mkdir -p "${LOG_DIR}"
# Duplicate output to a log file
exec &> >(tee "${LOG_DIR}/flatpak-build-$(date +"%F-%H%M%S").log")

# Delete the build dirs from last time. But then --keep-build-dirs, not
# --delete-build-dirs so that the build dirs from this time are left in place
# for optional inspection.
rm -rf .flatpak-builder/build

# Build HEAD commit.
perl -pi -e \
  "s/(\s*).*FW-Auto-Head.*/\$1commit: $(git rev-parse HEAD) # FW-Auto-Head: Generated line. See build script./" \
  org.sil.FieldWorks.yml

# Clean generated commit line.
(sleep 10s && perl -pi -e \
  "s/(\s*).*FW-Auto-Head.*/\$1commit: # FW-Auto-Head: Generated line. See build script./" \
  org.sil.FieldWorks.yml)&

# Using --no-shallow-clone for flexbridge for GitVersion.
flatpak-builder --user --repo=local-repo --keep-build-dirs --no-shallow-clone \
  --force-clean build-dir org.sil.FieldWorks.yml "$@"
flatpak --user remote-add --no-gpg-verify --if-not-exists \
  local-repo ./local-repo
# If a FieldWorks flatpak is already installed, such as from a downloaded
# .flatpak file, remove it so we don't fail to install what we just built.
flatpak remove --assumeyes \
  org.sil.FieldWorks org.sil.FieldWorks.Debug org.sil.FieldWorks.Locale ||
    echo "flatpak packages were not already installed."
flatpak --user install --or-update --noninteractive local-repo \
  org.sil.FieldWorks org.sil.FieldWorks.Debug
