#!/bin/bash

# Copyright (c) 2021 SIL International. MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -xueo pipefail
cd "$(dirname "$0")"

XDG_CACHE_HOME="${XDG_CACHE_HOME-"${HOME}/.cache"}"
BUILD_CACHE_DIR="${XDG_CACHE_HOME}/flatpak-build-cache"
LOG_DIR="${BUILD_CACHE_DIR}/logs"
mkdir -pv "${LOG_DIR}"
# Duplicate output to a log file
exec &> >(tee "${LOG_DIR}/build-$(date +"%F-%H%M%S").log")

STATE_DIR="${BUILD_CACHE_DIR}/flatpak-builder"
REPO_DIR="${BUILD_CACHE_DIR}/local-repo"
BUILD_DIR="${BUILD_CACHE_DIR}/build-dir"
# Delete the build dirs from last time. But then --keep-build-dirs, not
# --delete-build-dirs so that the build dirs from this time are left in place
# for optional inspection.
rm -rf "${STATE_DIR}/build"

# Build HEAD commit.
perl -pi -e \
  "s/(\s*).*FW-Auto-Head.*/\$1commit: $(git rev-parse HEAD) # FW-Auto-Head: Generated line. See build script./" \
  org.sil.FieldWorks.yml

# Clean generated commit line.
(sleep 10s && perl -pi -e \
  "s/(\s*).*FW-Auto-Head.*/\$1commit: # FW-Auto-Head: Generated line. See build script./" \
  org.sil.FieldWorks.yml)&

# Using --no-shallow-clone for flexbridge for GitVersion.
flatpak run org.flatpak.Builder --user --state-dir="${STATE_DIR}" \
  --repo="${REPO_DIR}" --keep-build-dirs --no-shallow-clone \
  --force-clean "${BUILD_DIR}" org.sil.FieldWorks.yml "$@"
flatpak --user remote-add --no-gpg-verify --if-not-exists \
  local-repo "${REPO_DIR}"
# If a FieldWorks flatpak is already installed, such as from a downloaded
# .flatpak file, remove it so we don't fail to install what we just built.
flatpak remove --assumeyes \
  org.sil.FieldWorks org.sil.FieldWorks.Debug org.sil.FieldWorks.Locale ||
    echo "flatpak packages were not already installed."
flatpak --user install --or-update --noninteractive local-repo \
  org.sil.FieldWorks org.sil.FieldWorks.Debug
