#!/bin/bash

# Copyright (c) 2022 SIL International. MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -xueo pipefail
cd "$(dirname "$0")"

XDG_CACHE_HOME="${XDG_CACHE_HOME-"${HOME}/.cache"}"
BUILD_CACHE_DIR="${XDG_CACHE_HOME}/flatpak-build-cache"
REPO_DIR="${BUILD_CACHE_DIR}/local-repo"
OUT_DIR="artifacts"

mkdir -vp "${OUT_DIR}"
base_package_name="fieldworks-${VERSION-$(date +"%F-%H%M%S")}"
flatpak build-bundle "${REPO_DIR}" \
  "${OUT_DIR}/${base_package_name}.flatpak" org.sil.FieldWorks
flatpak build-bundle --runtime "${REPO_DIR}" \
  "${OUT_DIR}/${base_package_name}-Debug.flatpak" org.sil.FieldWorks.Debug
flatpak build-bundle --runtime "${REPO_DIR}" \
  "${OUT_DIR}/${base_package_name}-Locale.flatpak" org.sil.FieldWorks.Locale
