//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AppTest.rc
//
#define IDD_DIALOG1                     101
#define IDB_BITMAP1                     103
#define IDB_VIEWBAR_IMAGES_SMALL        116
#define IDB_VIEWBAR_IMAGES_LARGE        117
#define IDR_ACCELERATOR1                118

#define IDD_BP                          121
#define IDD_BT                          122
#define IDB_NONE                        123
#define IDB_NONE_S                      124
#define IDB_ALL                         125
#define IDB_ALL_S                       126
#define IDB_BOX                         127
#define IDB_BOX_S                       128
#define IDB_GRID                        129
#define IDB_GRID_S                      130
#define IDB_NONET                       131
#define IDB_NONET_S                     132

#define IDR_TOOLBAR_STANDARD            990
#define IDR_TOOLBAR_FORMATTING          991
#define IDR_TOOLBAR_DATA                992
#define IDR_TOOLBAR_VIEW                993
#define IDR_TOOLBAR_INSERT              994
#define IDR_TOOLBAR_TOOLS               995
#define IDR_TOOLBAR_WINDOW              996

#define IDR_APPNMENU                    1000

#define IDC_COLOR                       1001
#define IDC_BOX                         1002
#define IDC_GRID                        1016
#define IDC_NONE                        1017
#define IDC_ALL                         1018
#define IDC_OK                          1019
#define IDC_CANCEL                      1020
#define IDC_DIAGRAM                     1024
#define IDC_WIDTH                       1025
#define IDC_LEFT                        1026
#define IDC_TOP                         1027
#define IDC_RIGHT                       1028
#define IDC_BOTTOM                      1029
#define IDC_NONET                       1032
#define IDC_COLS                        1033
#define IDC_ROWS                        1034

#define FILE_CLOSE_WINDOW               1150
#define FILE_SAVE_PROJECT               1151
#define FILE_SAVE_SPECIAL               1152
#define FILE_PAGE_SETUP                 1153
#define FILE_PRINT_PREVIEW              1154
#define FILE_PRINT                      1155
#define FILE_BACKUP                     1156
#define FILE_IMPORT                     1157
#define FILE_EXPORT                     1158
#define FILE_PROPERTIES                 1159
#define FILE_EXIT_FIELDWORKS            1160
#define EDIT_UNDO                       1250
#define EDIT_REDO                       1251
#define EDIT_CUT                        1252
#define EDIT_COPY                       1253
#define EDIT_PASTE                      1254
#define EDIT_PASTE_SPECIAL              1255
#define EDIT_SELECT_ALL                 1256
#define EDIT_DELETE                     1257
#define VIEW_DATA_ENTRY                 1351
#define VIEW_BROWSE                     1352
#define VIEW_DOCUMENT                   1353
#define VIEW_OUTLINE                    1354
#define VIEW_TOOLBARS                   1360
#define VIEW_TOOLBARS_STANDARD          1361
#define VIEW_TOOLBARS_FORMATTING        1362
#define VIEW_TOOLBARS_DATA              1363
#define VIEW_TOOLBARS_VIEW              1364
#define VIEW_TOOLBARS_INSERT            1365
#define VIEW_TOOLBARS_TOOLS             1366
#define VIEW_TOOLBARS_WINDOW            1367
#define VIEW_VIEWBAR                    1370
#define VIEW_STATUS_BAR                 1371
#define VIEW_SYNCHRONIZE                1380
#define VIEW_SYNCHRONIZE_SEND           1381
#define VIEW_SYNCHRONIZE_RECEIVE        1382
#define VIEW_SYNCHRONIZE_CONFIGURE      1383
#define DATA_FIRST                      1450
#define DATA_PREVIOUS                   1451
#define DATA_NEXT                       1452
#define DATA_LAST                       1453
#define DATA_HISTORY                    1454
#define DATA_FAVORITES                  1455
#define DATA_ORGANIZE_FAVORITES         1456
#define DATA_SEARCH_QUICK               1457
#define DATA_SEARCH                     1458
#define DATA_NEXT_MATCH                 1459
#define DATA_PREVIOUS_MATCH             1460
#define DATA_REPLACE                    1461
#define DATA_SORT                       1462
#define DATA_CONVERT                    1463
#define INSERT_ENTRY                    1550
#define INSERT_SUBENTRY                 1551
#define INSERT_LINK                     1552
#define INSERT_TABLE                    1553
#define INSERT_SOUND                    1554
#define INSERT_VIDEO                    1555
#define INSERT_PICTURE                  1556
#define INSERT_OBJECT                   1557
#define INSERT_ENTRY_OBSERVATION        1560
#define INSERT_ENTRY_FORMAL_INTERVIEW   1561
#define INSERT_ENTRY_CONVERSATION       1562
#define INSERT_ENTRY_PERFORMANCE        1563
#define INSERT_ENTRY_MAP_ENTRY          1564
#define INSERT_ENTRY_ALMANAC_RECORD     1565
#define INSERT_ENTRY_LITERATURE_SUMMARY 1566
#define INSERT_ENTRY_TAGGED_TEXT        1567
#define INSERT_ENTRY_HYPOTHESIS         1568
#define INSERT_SUBENTRY_OBSERVATION     1570
#define INSERT_SUBENTRY_FORMAL_INTERVIEW 1571
#define INSERT_SUBENTRY_CONVERSATION    1572
#define INSERT_SUBENTRY_PERFORMANCE     1573
#define INSERT_SUBENTRY_MAP_ENTRY       1574
#define INSERT_SUBENTRY_ALMANAC_RECORD  1575
#define INSERT_SUBENTRY_LITERATURE_SUMMARY 1576
#define INSERT_SUBENTRY_TAGGED_TEXT     1577
#define INSERT_SUBENTRY_HYPOTHESIS      1578
#define FORMAT_FONT                     1600
#define FORMAT_PARAGRAPH                1601
#define FORMAT_LIST                     1602
#define FORMAT_WRITING_SYSTEM           1651
#define FORMAT_BORDER                   1654
#define FORMAT_TABLE                    1655
#define FORMAT_STYLES                   1656
#define FORMATTB_STYLE                  1670
#define FORMATTB_WRITING_SYSTEM         1671
#define FORMATTB_FONT                   1672
#define FORMATTB_FONT_SIZE              1673
#define FORMATTB_BOLD                   1674
#define FORMATTB_ITALIC                 1675
#define FORMATTB_ALIGN_LEFT             1676
#define FORMATTB_ALIGN_CENTER           1677
#define FORMATTB_ALIGN_RIGHT            1678
#define FORMATTB_LIST_NUMBER            1679
#define FORMATTB_LIST_BULLET            1680
#define FORMATTB_UNINDENT               1681
#define FORMATTB_INDENT                 1682
#define FORMATTB_APPLY_BORDER           1683
#define FORMATTB_APPLY_BACKGROUND_COLOR 1684
#define FORMATTB_APPLY_FOREGROUND_COLOR 1685
#define TOOLS_REMINDERS                 1750
#define TOOLS_AUTO_TAGGING              1751
#define TOOLS_SPELLING                  1752
#define TOOLS_VERSION_HISTORY           1753
#define TOOLS_REPORTS                   1760
#define TOOLS_REPORTS_OUTLINES_AND_CATEGORIES 1761
#define TOOLS_REPORTS_SUMMARY_INFORMATION 1762
#define TOOLS_REPORTS_ANNUAL_CYCLE      1763
#define TOOLS_LISTS                     1770
#define TOOLS_EXPLORER                  1771
#define TOOLS_SHOW_SELECTION_USING      1772
#define TOOLS_OPTIONS                   1773
#define TOOLS_CUSTOMIZE                 1774
#define WINDOW_NEW                      1850
#define WINDOW_SPLIT                    1851
#define HELP_FIELDWORKS_CONTENTS        1901
#define HELP_FIELDWORKS_INDEX           1902
#define HELP_FIELDWORKS_FIND            1903
#define HELP_APPLICATION                1904
#define HELP_HOW_DO_I                   1905
#define HELP_WHATS_THIS                 1906
#define HELP_TUTORIALS                  1907
#define HELP_ABOUT_APPLICATION          1908
#define HELP_CONTEXTBALOON              1909
#define IDCR_BLACK                      15000
#define IDCR_BROWN                      15001
#define IDCR_DARK_OLIVE_GREEN           15002
#define IDCR_DARK_GREEN                 15003
#define IDCR_DARK_TEAL                  15004
#define IDCR_DARK_BLUE                  15005
#define IDCR_INDIGO                     15006
#define IDCR_DARK_GREY                  15007
#define IDCR_DARK_RED                   15010
#define IDCR_ORANGE                     15011
#define IDCR_DARK_YELLOW                15012
#define IDCR_GREEN                      15013
#define IDCR_TEAL                       15014
#define IDCR_BLUE                       15015
#define IDCR_BLUE_GREY                  15016
#define IDCR_GREY_40                    15017
#define IDCR_RED                        15020
#define IDCR_LIGHT_ORANGE               15021
#define IDCR_LIME                       15022
#define IDCR_SEA_GREEN                  15023
#define IDCR_AQUA                       15024
#define IDCR_LIGHT_BLUE                 15025
#define IDCR_VIOLET                     15026
#define IDCR_GREY_50                    15027
#define IDCR_PINK                       15030
#define IDCR_GOLD                       15031
#define IDCR_YELLOW                     15032
#define IDCR_BRIGHT_GREEN               15033
#define IDCR_TURQUOISE                  15034
#define IDCR_SKY_BLUE                   15035
#define IDCR_PLUM                       15036
#define IDCR_LIGHT_GREY                 15037
#define IDCR_ROSE                       15040
#define IDCR_TAN                        15041
#define IDCR_LIGHT_YELLOW               15042
#define IDCR_PALE_GREEN                 15043
#define IDCR_PALE_TURQUOISE             15044
#define IDCR_PALE_BLUE                  15045
#define IDCR_LAVENDER                   15046
#define IDCR_WHITE                      15047
#define IDST_PT                         15050

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
