/*----------------------------------------------------------------------------------------------
Copyright 1999, SIL International. All rights reserved.

File: FwCellarTlb.idl
Responsibility: Shon Katzenberger
Last reviewed:

	Cellar type library definitions.
----------------------------------------------------------------------------------------------*/
import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";

#include "common.idh"


DeclareLibrary(FwCellarLib, 1.0, "FieldWorks Cellar", 2F0FCCC0-C160-11d3-8DA2-005004DEFEC4)
{
	#include "Cellar.idh"
};
