/*******************************************************************************
* AppCompat$ table
*
* Description:
*   Creates the AppCompat$ table
*
* Dependencies:
*   spx_Drop_Table
*
* Revision History:
*  22 June, 2007, Yves Blouin: Created
*   7 May 2008, Steve Miller: Added this header; some minor changes.
*******************************************************************************/

EXECUTE PROCEDURE spx_Drop_Table('AppCompat$');
COMMIT;

CREATE TABLE AppCompat$
(
  "APPGUID"            CHAR(16) CHARACTER SET OCTETS NOT NULL,
  "APPNAME"            VARCHAR(200) CHARACTER SET UTF8,
  "EARLIESTCOMPATVER"  INTEGER NOT NULL,
  "LASTKNOWNCOMPATVER" INTEGER NOT NULL
);
COMMIT;

ALTER TABLE AppCompat$ ADD CONSTRAINT PK_APPCOMPAT$ PRIMARY KEY ("APPGUID");
COMMIT;

INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('39886581-4DD5-11D4-8078-0000C0FB81B5' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'FwNotebook', 500, 500);
INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('5EA62D01-7A78-11D4-8078-0000C0FB81B5' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'FwChoicesListEditor', 500, 500);
INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('A7D421E1-1DD3-11D5-B720-0010A4B54856' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'TE', 500, 500);
INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('8645FA4B-EE90-11D2-A9B8-0080C87B6086' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'FwMorphologyModelEditor', 500, 500);
INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('8645FA4D-EE90-11D2-A9B8-0080C87B6086' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'FwLexEd', 500, 500);
INSERT INTO APPCOMPAT$("APPGUID", "APPNAME", "EARLIESTCOMPATVER", "LASTKNOWNCOMPATVER")
  VALUES(udf_Varchar_To_GUID(CAST('76230C21-7084-11D5-83CD-0050BA78F57C' AS VARCHAR(36) CHARACTER SET OCTETS)),
	'FwExplorer', 500, 500);
COMMIT;
