/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (c) 1999-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: ViewsTlb.idl
Responsibility: John Thomson
Last reviewed:

	Defines Views Type Library.
-------------------------------------------------------------------------------*//*:End Ignore*/
// This file will be processed by the MIDL tool to
// produce the type library (Views.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";

#include "common.idh" // DeclareInterface and similar

DeclareLibrary(Views, 1.0, "Views 1.0 Type Library",
	f6d10640-c00c-11d2-8078-0000c0fb81b5)
{
	// for definition of ITsString.
	importlib("FwKernelTlb.tlb");	// Includes DbAccess, DbServices, and Language as well.

	#include "Views.idh"

};
