/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (c) 1999-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: ViewsPs.idl
Responsibility: Shon Katzenberger
Last reviewed:

	Defines Text Services Interfaces for proxy / stub generation.
-------------------------------------------------------------------------------*//*:End Ignore*/
import "oaidl.idl";
import "ocidl.idl";
import "FwKernelPs.idl";	// includes Language

#include "Common.idh"

#define NO_COCLASSES

#include "Views.idh"
