// IcuEC.idl : IDL source for IcuEC
//

// This file will be processed by the MIDL tool to
// produce the type library (IcuEC40.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6E560CF3-4FCB-4f1f-B686-273F5999F855),
	version(3.0),
	helpstring("Icu 4.0 Encoding Converters Plug-in 3.0 Type Library")
]
library IcuECLib
{
	importlib("stdole2.tlb");
	importlib("ECInterfaces.tlb");

	[
		uuid(E670379F-BF3C-4082-B607-36740C5050D8)
		, helpstring("Icu Transliterator Class")
		, hidden
	]
	coclass IcuECTransliterator
	{
		[default] interface IEncConverter;
	};

	[
		uuid(DECD4196-AB92-40cf-B885-600A5CA90C70)
		, helpstring("IcuTrans IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECTransConfig
	{
		[default] interface IEncConverterConfig;
	};

	[
		uuid(3998D0AF-887F-4724-A7A1-ACCBBD69652B)
		, helpstring("Icu Encoding Converter Class")
		, hidden
	]
	coclass IcuECConverter
	{
		[default] interface IEncConverter;
	};

	[
		uuid(341D73FD-B7ED-4103-856C-F3792F764187)
		, helpstring("IcuConv IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECConvConfig
	{
		[default] interface IEncConverterConfig;
	};

	[
		uuid(D203A130-8B82-47be-8E0C-A5119C8D243C)
		, helpstring("Icu Regex Class")
		, hidden
	]
	coclass IcuECRegex
	{
		[default] interface IEncConverter;
	};

	[
		uuid(19CD5989-296C-45ce-8856-3600648D3B1C)
		, helpstring("IcuRegex IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECRegexConfig
	{
		[default] interface IEncConverterConfig;
	};
};
