// IcuEC.idl : IDL source for IcuEC
//

// This file will be processed by the MIDL tool to
// produce the type library (IcuEC40.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6748E0F4-4B1B-4AF2-81F5-F0DF0E175C8C),
	version(4.0),
	helpstring("Icu 4.0 Encoding Converters Plug-in 4.0 Type Library")
]
library IcuECLib
{
	importlib("stdole2.tlb");
	importlib("ECInterfaces.tlb");

	[
		uuid(2F5B5C9B-1DB8-4E6F-B63B-CA17581D28BA)
		, helpstring("Icu Transliterator Class")
		, hidden
	]
	coclass IcuECTransliterator
	{
		[default] interface IEncConverter;
	};

	[
		uuid(479EA52E-B011-4681-BC8E-991C39633129)
		, helpstring("IcuTrans IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECTransConfig
	{
		[default] interface IEncConverterConfig;
	};

	[
		uuid(7C995BB3-B618-43EC-A8FC-4DA2B2BC4014)
		, helpstring("Icu Encoding Converter Class")
		, hidden
	]
	coclass IcuECConverter
	{
		[default] interface IEncConverter;
	};

	[
		uuid(752A8F02-DDE3-4B52-9305-42B21C19F21F)
		, helpstring("IcuConv IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECConvConfig
	{
		[default] interface IEncConverterConfig;
	};

	[
		uuid(6D8AD639-67C9-4379-BADA-8CE2D5E7B19A)
		, helpstring("Icu Regex Class")
		, hidden
	]
	coclass IcuECRegex
	{
		[default] interface IEncConverter;
	};

	[
		uuid(B0F99E0B-80F7-4C0D-94ED-5D9C7C58C21A)
		, helpstring("IcuRegex IEncConverterConfig implementation class")
		, hidden
	]
	coclass IcuECRegexConfig
	{
		[default] interface IEncConverterConfig;
	};
};
