<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="4.0" encoding="utf-8"/>
	<!-- ===========================================================
	  Version of this stylesheet
	  =========================================================== -->
	<xsl:variable name="sVersion">1.9.0</xsl:variable>
	<xsl:variable name="sExampleCellPadding">padding-left: .25em</xsl:variable>
	<xsl:variable name="sLdquo">&#8220;</xsl:variable>
	<xsl:variable name="sRdquo">&#8221;</xsl:variable>
	<!-- ===========================================================
	  MAIN BODY
	  =========================================================== -->
	<xsl:template match="/lingPaper">
		<html>
			<head>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
				<xsl:comment> generated by XLingPap1.xsl Version <xsl:value-of select="$sVersion"/>&#x20;</xsl:comment>
				<title>
					<xsl:value-of select="frontMatter/title"/>
				</title>
				<xsl:choose>
					<xsl:when test="/lingPaper/styles">
						<style type="text/css">
							<xsl:value-of select="/lingPaper/styles"/>
						</style>
					</xsl:when>
					<xsl:otherwise>
						<xsl:element name="link">
							<xsl:attribute name="rel">stylesheet</xsl:attribute>
							<xsl:attribute name="href"><xsl:if test="not(@css)">XLingPap1.css</xsl:if><xsl:if test="@css"><xsl:value-of select="@css"/></xsl:if></xsl:attribute>
						</xsl:element>
					</xsl:otherwise>
				</xsl:choose>
			</head>
			<body>
				<xsl:apply-templates/>
			</body>
		</html>
	</xsl:template>
	<!-- ===========================================================
	  FRONTMATTER
	  =========================================================== -->
	<!--
	  title
	  -->
	<xsl:template match="title">
		<center>
			<b>
				<big>
					<big>
						<big>
							<!--              <xsl:value-of select="."/> -->
							<xsl:apply-templates/>
						</big>
					</big>
				</big>
			</b>
		</center>
	</xsl:template>
	<!--
	  author
	  -->
	<xsl:template match="author">
		<xsl:if test="position()=1">
			<br/>
		</xsl:if>
		<center>
			<i>
				<xsl:value-of select="."/>
			</i>
		</center>
	</xsl:template>
	<!--
	  affiliation
	  -->
	<xsl:template match="affiliation">
		<xsl:if test="position()=1">
			<br/>
		</xsl:if>
		<center>
			<i>
				<xsl:value-of select="."/>
			</i>
		</center>
	</xsl:template>
	<!--
	  date or presentedAt
	  -->
	<xsl:template match="date | presentedAt">
		<br/>
		<center>
			<small>
				<xsl:apply-templates/>
			</small>
		</center>
	</xsl:template>
	<!--
	  version
	  -->
	<xsl:template match="version">
		<center>
			<small>Version: <xsl:value-of select="."/>
			</small>
		</center>
	</xsl:template>
	<!--
	  contents
	  -->
	<xsl:template match="contents">
		<hr/>
		<div>
			<center>
				<big>
					<big>
						<b>
							<xsl:call-template name="OutputContentsLabel"/>
						</b>
					</big>
				</big>
			</center>
			<xsl:variable name="nLevel">
				<xsl:value-of select="number(@showLevel)"/>
			</xsl:variable>
			<ul>
				<xsl:if test="//acknowledgements">
					<li>
						<a href="#rXLingPapAcknowledgements">
							<xsl:call-template name="OutputAcknowledgementsLabel"/>
						</a>
					</li>
				</xsl:if>
				<xsl:if test="//abstract">
					<li>
						<a href="#rXLingPapAbstract">
							<xsl:call-template name="OutputAbstractLabel"/>
						</a>
					</li>
				</xsl:if>
				<xsl:if test="//part">
					<xsl:for-each select="//part">
						<xsl:if test="position()=1">
							<xsl:for-each select="preceding-sibling::*[name()='chapter']">
								<xsl:call-template name="OutputAllChapterTOC">
									<xsl:with-param name="nLevel">
										<xsl:value-of select="$nLevel"/>
									</xsl:with-param>
								</xsl:call-template>
							</xsl:for-each>
						</xsl:if>
						<li>
							<xsl:element name="a">
								<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
								<xsl:apply-templates select="." mode="numberPart"/>
								<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
								<xsl:apply-templates select="secTitle"/>
							</xsl:element>
						</li>
						<ul>
							<xsl:for-each select="chapter">
								<xsl:call-template name="OutputAllChapterTOC">
									<xsl:with-param name="nLevel">
										<xsl:value-of select="$nLevel"/>
									</xsl:with-param>
								</xsl:call-template>
							</xsl:for-each>
						</ul>
					</xsl:for-each>
				</xsl:if>
				<!-- part -->
				<xsl:if test="not(//part) and //chapter">
					<xsl:for-each select="//chapter">
						<li>
							<xsl:element name="a">
								<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
								<xsl:apply-templates select="." mode="numberChapter"/>
								<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
								<xsl:apply-templates select="secTitle"/>
							</xsl:element>
							<ul>
								<xsl:call-template name="OutputAllSectionTOC">
									<xsl:with-param name="nLevel">
										<xsl:value-of select="$nLevel"/>
									</xsl:with-param>
									<xsl:with-param name="nodesSection1" select="section1"/>
								</xsl:call-template>
							</ul>
						</li>
					</xsl:for-each>
				</xsl:if>
				<!-- chapter -->
				<xsl:if test="not(//part) and not(//chapter)">
					<xsl:call-template name="OutputAllSectionTOC">
						<xsl:with-param name="nLevel">
							<xsl:value-of select="$nLevel"/>
						</xsl:with-param>
						<xsl:with-param name="nodesSection1" select="//section1[not(parent::appendix)]"/>
					</xsl:call-template>
				</xsl:if>
				<xsl:for-each select="//appendix">
					<li>
						<xsl:element name="a">
							<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
							<xsl:apply-templates select="." mode="numberAppendix"/>
							<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
							<xsl:apply-templates select="secTitle"/>
						</xsl:element>
						<xsl:call-template name="OutputAllSectionTOC">
							<xsl:with-param name="nLevel">
								<xsl:value-of select="$nLevel"/>
							</xsl:with-param>
							<xsl:with-param name="nodesSection1" select="section1"/>
						</xsl:call-template>
					</li>
				</xsl:for-each>
				<xsl:if test="//endnote">
					<li>
						<a href="#rXLingPapEndnotes">
							<xsl:call-template name="OutputEndnotesLabel"/>
						</a>
					</li>
				</xsl:if>
				<xsl:if test="//references">
					<li>
						<a href="#rXLingPapReferences">
							<xsl:call-template name="OutputReferencesLabel"/>
						</a>
					</li>
				</xsl:if>
			</ul>
		</div>
	</xsl:template>
	<!--
	  abstract and acknowledgements
	  -->
	<xsl:template match="abstract | acknowledgements">
		<br/>
		<xsl:if test="not(name(preceding-sibling::*) = 'contents')">
			<hr/>
		</xsl:if>
		<center>
			<b>
				<big>
					<big>
						<xsl:choose>
							<xsl:when test="name(.)='abstract'">
								<a name="rXLingPapAbstract">
									<xsl:call-template name="OutputAbstractLabel"/>
								</a>
							</xsl:when>
							<xsl:otherwise>
								<a name="rXLingPapAcknowledgements">
									<xsl:call-template name="OutputAcknowledgementsLabel"/>
								</a>
							</xsl:otherwise>
						</xsl:choose>
					</big>
				</big>
			</b>
		</center>
		<div style="margin-left: 0.5in; margin-right: 0.5in">
			<xsl:apply-templates/>
		</div>
		<xsl:if test="not(//part)">
			<hr/>
		</xsl:if>
	</xsl:template>
	<!-- ===========================================================
	  PARTS, CHAPTERS, SECTIONS, and APPENDICES
	  =========================================================== -->
	<!--
	  Part
	  -->
	<xsl:template match="part">
		<hr size="3"/>
		<p>
			<center>
				<big>
					<big>
						<big>
							<big>
								<big>
									<b>
										<xsl:element name="a">
											<xsl:attribute name="name"><xsl:value-of select="@id"/></xsl:attribute>
											<xsl:apply-templates select="." mode="numberPart"/>
											<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
											<xsl:apply-templates select="secTitle"/>
										</xsl:element>
									</b>
								</big>
							</big>
						</big>
					</big>
				</big>
			</center>
		</p>
		<hr size="3"/>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<!--
	  Chapter
	  -->
	<xsl:template match="chapter">
		<xsl:call-template name="OutputChapTitle">
			<xsl:with-param name="sTitle">
				<xsl:apply-templates select="." mode="numberChapter"/>
				<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
				<xsl:apply-templates select="secTitle"/>
			</xsl:with-param>
		</xsl:call-template>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<!--
	  Sections
	  -->
	<xsl:template match="section1">
		<h1>
			<xsl:call-template name="OutputSection"/>
		</h1>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<xsl:template match="section2">
		<h2>
			<xsl:call-template name="OutputSection"/>
		</h2>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<xsl:template match="section3">
		<h3>
			<xsl:call-template name="OutputSection"/>
		</h3>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<xsl:template match="section4">
		<h4>
			<xsl:call-template name="OutputSection"/>
		</h4>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<xsl:template match="section5">
		<h5 style="font-size:100%">
			<xsl:call-template name="OutputSection"/>
		</h5>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<xsl:template match="section6">
		<h6 style="font-size:100%">
			<xsl:call-template name="OutputSection"/>
		</h6>
		<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
	</xsl:template>
	<!--
	  Appendix
	  -->
	<xsl:template match="appendix">
		<hr size="3"/>
		<xsl:choose>
			<xsl:when test="//chapter">
				<xsl:call-template name="OutputChapTitle">
					<xsl:with-param name="sTitle">
						<xsl:apply-templates select="." mode="numberAppendix"/>
					</xsl:with-param>
				</xsl:call-template>
				<xsl:apply-templates select="secTitle"/>
				<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
			</xsl:when>
			<xsl:otherwise>
				<h1>
					<xsl:apply-templates select="." mode="numberAppendix"/>
					<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
					<xsl:call-template name="OutputSection"/>
				</h1>
				<xsl:apply-templates select="child::node()[name()!='secTitle']"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
	  secTitle
	  -->
	<xsl:template match="secTitle">
		<xsl:apply-templates/>
	</xsl:template>
	<!--
	  sectionRef
	  -->
	<xsl:template match="sectionRef">
		<xsl:element name="a">
			<xsl:attribute name="href">#<xsl:value-of select="@sec"/></xsl:attribute>
			<xsl:apply-templates select="id(@sec)" mode="number"/>
		</xsl:element>
	</xsl:template>
	<!--
	  appendixRef
	  -->
	<xsl:template match="appendixRef">
		<xsl:element name="a">
			<xsl:attribute name="href">#<xsl:value-of select="@app"/></xsl:attribute>
			<xsl:apply-templates select="id(@app)" mode="numberAppendix"/>
		</xsl:element>
	</xsl:template>
	<!--
	  genericRef
	  -->
	<xsl:template match="genericRef">
		<xsl:element name="a">
			<xsl:attribute name="href">#<xsl:value-of select="@ref"/></xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!--
	  link
	  -->
	<xsl:template match="link">
		<xsl:element name="a">
			<xsl:attribute name="href"><xsl:value-of select="@href"/></xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!-- ===========================================================
	  PARAGRAPH
	  =========================================================== -->
	<xsl:template match="p | pc">
		<!--    <xsl:if test="parent::endnote and not(position()=1)">
	  <tr>
		<td/>
		<td>
		  <p>
			<xsl:apply-templates/>
		  </p>
		</td>
	  </tr>
	</xsl:if>
	<xsl:if test="not(parent::endnote) or position()=1">
	-->
		<p>
			<xsl:if test="name(.)='pc'">
				<xsl:attribute name="class">pc</xsl:attribute>
			</xsl:if>
			<xsl:apply-templates/>
		</p>
		<!--    </xsl:if> -->
	</xsl:template>
	<!-- ===========================================================
	  QUOTES
	  =========================================================== -->
	<xsl:template match="q">"<xsl:apply-templates/>"</xsl:template>
	<xsl:template match="blockquote">
		<div style="margin-left:.5in;margin-right:.5in">
			<xsl:apply-templates/>
		</div>
	</xsl:template>
	<!-- ===========================================================
	  LISTS
	  =========================================================== -->
	<xsl:template match="ol">
		<xsl:variable name="NestingLevel">
			<xsl:value-of select="count(ancestor::ol)"/>
		</xsl:variable>
		<xsl:element name="ol">
			<xsl:attribute name="style">
			<xsl:text>list-style-type:</xsl:text>
			<xsl:choose>
				<xsl:when test="($NestingLevel mod 3)=0"><xsl:text>decimal</xsl:text></xsl:when>
				<xsl:when test="($NestingLevel mod 3)=1"><xsl:text>lower-alpha</xsl:text></xsl:when>
				<xsl:when test="($NestingLevel mod 3)=2"><xsl:text>lower-roman</xsl:text></xsl:when>
			</xsl:choose>
			</xsl:attribute>
			<xsl:if test="@class">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			</xsl:if>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<xsl:template match="ul">
		<ul>
			<xsl:apply-templates/>
		</ul>
	</xsl:template>
	<xsl:template match="li">
		<li>
			<xsl:apply-templates/>
		</li>
	</xsl:template>
	<xsl:template match="dl">
		<dl>
			<xsl:apply-templates/>
		</dl>
	</xsl:template>
	<xsl:template match="dt">
		<dt>
			<xsl:apply-templates/>
		</dt>
	</xsl:template>
	<xsl:template match="dd">
		<dd>
			<xsl:apply-templates/>
		</dd>
	</xsl:template>
	<!-- ===========================================================
	  EXAMPLES
	  =========================================================== -->
	<xsl:template match="example">
		<div style="margin-left: 0.25in; margin-right: 0.25in">
			<table>
				<tr>
					<td valign="top">
						<xsl:element name="a">
							<xsl:attribute name="name"><xsl:value-of select="@num"/></xsl:attribute>
							<xsl:call-template name="exampleNumber"/>
						</xsl:element>
					</td>
					<td>
						<xsl:variable name="myFirstChild" select="child::*[position()=1]"/>
						<xsl:choose>
							<xsl:when test="substring(name($myFirstChild), 1, 4)='list'">
								<table cellpadding="0pt" cellspacing="0pt">
									<xsl:apply-templates/>
								</table>
							</xsl:when>
							<xsl:otherwise>
								<xsl:apply-templates/>
							</xsl:otherwise>
						</xsl:choose>
					</td>
				</tr>
			</table>
		</div>
	</xsl:template>
	<!--
	  word
	  -->
	<xsl:template match="word">
		<table cellpadding="0pt" cellspacing="0pt">
			<tr>
				<xsl:for-each select="(langData | gloss)">
					<td>
						<xsl:apply-templates select="."/>
					</td>
				</xsl:for-each>
			</tr>
		</table>
	</xsl:template>
	<!--
	  listWord
	  -->
	<xsl:template match="listWord">
		<!--    <table> -->
		<tr>
			<td>
				<xsl:element name="a">
					<xsl:attribute name="name"><xsl:value-of select="@letter"/></xsl:attribute>
					<xsl:apply-templates select="." mode="letter"/>.</xsl:element>
			</td>
			<xsl:for-each select="(langData | gloss)">
				<td>
					<xsl:attribute name="style"><xsl:value-of select="$sExampleCellPadding"/></xsl:attribute>
					<xsl:apply-templates select="."/>
				</td>
			</xsl:for-each>
		</tr>
		<!--    </table> -->
	</xsl:template>
	<!--
	  single
	  -->
	<xsl:template match="single">
		<table cellpadding="0pt" cellspacing="0pt">
			<tr>
				<td>
					<xsl:apply-templates/>
				</td>
			</tr>
		</table>
	</xsl:template>
	<!--
	  listSingle
	  -->
	<xsl:template match="listSingle">
		<table cellpadding="0pt" cellspacing="0pt">
			<tr>
				<td valign="top">
					<xsl:element name="a">
						<xsl:attribute name="name"><xsl:value-of select="@letter"/></xsl:attribute>
						<xsl:apply-templates select="." mode="letter"/>.</xsl:element>
				</td>
				<td>
					<xsl:attribute name="style"><xsl:value-of select="$sExampleCellPadding"/></xsl:attribute>
					<xsl:apply-templates/>
				</td>
			</tr>
		</table>
	</xsl:template>
	<!--
	  interlinear
	  -->
	<xsl:template match="interlinear">
		<xsl:choose>
			<xsl:when test="lineSet">
				<xsl:for-each select="lineSet | conflation">
					<xsl:apply-templates/>
				</xsl:for-each>
			</xsl:when>
			<xsl:otherwise>
				<xsl:apply-templates/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
	  lineGroup
	  -->
	<xsl:template match="lineGroup">
		<table cellpadding="0pt" cellspacing="0pt">
			<xsl:if test="name(../..)='interlinear' or name(../..)='listInterlinear'">
				<xsl:attribute name="style"><xsl:text>margin-left: 0.1in</xsl:text></xsl:attribute>
			</xsl:if>
			<xsl:apply-templates/>
		</table>
	</xsl:template>
	<!--
	  line
	  -->
	<xsl:template match="line">
		<!--    <tr style="line-height:87.5%"> -->
		<tr>
			<xsl:choose>
				<xsl:when test="wrd">
					<xsl:for-each select="wrd">
						<xsl:element name="td">
							<xsl:attribute name="class"><xsl:value-of select="id(@lang)"/></xsl:attribute>
							<xsl:attribute name="style"><xsl:value-of select="$sExampleCellPadding"/></xsl:attribute>
							<xsl:apply-templates/>
						</xsl:element>
					</xsl:for-each>
				</xsl:when>
				<xsl:otherwise>
					<xsl:variable name="class">
						<xsl:if test="langData">
							<xsl:value-of select="id(langData/@lang)"/>
						</xsl:if>
						<xsl:if test="gloss">
							<xsl:value-of select="id(gloss/@lang)"/>
						</xsl:if>
					</xsl:variable>
					<xsl:variable name="sContents">
						<xsl:apply-templates/>
					</xsl:variable>
					<xsl:call-template name="OutputTableCells">
						<xsl:with-param name="sList" select="$sContents"/>
						<xsl:with-param name="class" select="$class"/>
					</xsl:call-template>
				</xsl:otherwise>
			</xsl:choose>
		</tr>
	</xsl:template>
	<!--
	  conflatedLine
	  -->
	<xsl:template match="conflatedLine">
		<tr style="line-height:87.5%">
			<td valign="top">
				<xsl:if test="name(..)='interlinear' and position()=1">
					<xsl:call-template name="OutputExampleNumber"/>
				</xsl:if>
			</td>
			<xsl:apply-templates/>
		</tr>
	</xsl:template>
	<!--
	  lineSet
	  -->
	<xsl:template match="lineSet">
		<xsl:choose>
			<xsl:when test="name(..)='conflation'">
				<tr>
					<xsl:if test="@letter">
						<td valign="top">
							<xsl:element name="a">
								<xsl:attribute name="name"><xsl:value-of select="@letter"/></xsl:attribute>
								<xsl:apply-templates select="." mode="letter"/>.</xsl:element>
						</td>
					</xsl:if>
					<td>
						<table>
							<xsl:apply-templates/>
						</table>
					</td>
				</tr>
			</xsl:when>
			<xsl:otherwise>
				<td>
					<table>
						<xsl:apply-templates/>
					</table>
				</td>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
	  conflation
	  -->
	<xsl:template match="conflation">
		<xsl:variable name="sCount" select="count(descendant::*[lineSetRow])"/>
<!--  sCount = <xsl:value-of select="$sCount"/> -->
		<td>
			<img align="middle">
				<xsl:attribute name="src"><xsl:text>LeftBrace</xsl:text><xsl:value-of select="$sCount"/><xsl:text>.png</xsl:text></xsl:attribute>
			</img>
		</td>
		<td>
			<table>
				<xsl:apply-templates/>
			</table>
		</td>
		<td>
			<img align="middle">
				<xsl:attribute name="src"><xsl:text>RightBrace</xsl:text><xsl:value-of select="$sCount"/><xsl:text>.png</xsl:text></xsl:attribute>
			</img>
		</td>
	</xsl:template>
	<!--
	  lineSetRow
	  -->
	<xsl:template match="lineSetRow">
		<tr style="line-height:87.5%">
			<xsl:for-each select="wrd">
				<xsl:element name="td">
					<xsl:attribute name="class"><xsl:value-of select="@lang"/></xsl:attribute>
					<xsl:apply-templates/>
				</xsl:element>
			</xsl:for-each>
		</tr>
	</xsl:template>
	<!--
	  free
	  -->
	<xsl:template match="free">
		<table>
			<xsl:variable name="sGrandParent">
				<xsl:value-of select="name(../..)"/>
			</xsl:variable>
			<xsl:if test="preceding-sibling::free[position()=1] or $sGrandParent='interlinear' or $sGrandParent='listInterlinear'">
				<xsl:attribute name="style"><xsl:text>margin-left: 0.1in</xsl:text></xsl:attribute>
			</xsl:if>
			<!-- ### -->
			<tr style="line-height:125%">
				<xsl:element name="td">
					<xsl:attribute name="colspan">30</xsl:attribute>
					<xsl:attribute name="class"><xsl:value-of select="id(gloss/@lang)"/></xsl:attribute>
					<xsl:apply-templates/>
				</xsl:element>
			</tr>
		</table>
	</xsl:template>
	<!--
	  listInterlinear
	  -->
	<xsl:template match="listInterlinear">
		<table cellpadding="0pt" cellspacing="0pt">
			<tr>
				<td valign="top">
					<xsl:element name="a">
						<xsl:attribute name="name"><xsl:value-of select="@letter"/></xsl:attribute>
						<xsl:apply-templates select="." mode="letter"/>.</xsl:element>
				</td>
				<td>
					<xsl:apply-templates/>
				</td>
			</tr>
		</table>
	</xsl:template>
	<!--
	  chart
	  -->
	<xsl:template match="chart">
		<xsl:if test="name(..)='example'">
			<table>
				<tr>
					<td>
						<xsl:choose>
							<xsl:when test="@class">
								<xsl:element name="div">
									<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
									<xsl:choose>
										<xsl:when test="child::ol | child::ul | child::dl">
											<xsl:apply-templates/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="." disable-output-escaping="yes"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:element>
							</xsl:when>
							<xsl:otherwise>
								<xsl:apply-templates/>
								<!--                <xsl:value-of select="." disable-output-escaping="yes"/> -->
							</xsl:otherwise>
						</xsl:choose>
					</td>
				</tr>
			</table>
		</xsl:if>
		<xsl:if test="name(..)!='example'">
			<xsl:if test="parent::endnote and not(position()=1)">
				<table>
					<tr>
						<tr>
							<td/>
							<td>
								<div>
									<xsl:value-of select="." disable-output-escaping="yes"/>
								</div>
							</td>
						</tr>
					</tr>
				</table>
			</xsl:if>
			<xsl:if test="not(parent::endnote) or position()=1">
				<div>
					<xsl:if test="@class">
						<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
					</xsl:if>
					<xsl:apply-templates/>
				</div>
			</xsl:if>
		</xsl:if>
	</xsl:template>
	<!--
	  tree
	  -->
	<xsl:template match="tree">
		<xsl:choose>
			<xsl:when test="img">
				<xsl:choose>
					<xsl:when test="name(..)='example'">
						<table>
							<tr>
								<td valign="top">
									<xsl:apply-templates/>
								</td>
							</tr>
						</table>
					</xsl:when>
					<xsl:otherwise>
						<p style="margin-left: 0.25in">
							<xsl:apply-templates/>
						</p>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<div>
					<xsl:value-of select="." disable-output-escaping="yes"/>
				</div>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
	  table
	  -->
	<xsl:template match="table">
		<xsl:choose>
			<xsl:when test="name(..)='example'">
				<td>
					<xsl:attribute name="style"><xsl:value-of select="$sExampleCellPadding"/></xsl:attribute>
					<xsl:call-template name="OutputTable"/>
				</td>
			</xsl:when>
			<xsl:otherwise>
				<div>
					<xsl:call-template name="OutputTable"/>
				</div>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
		  headerRow for a table
	  -->
	<xsl:template match="headerRow">
		<xsl:if test="@class">
			<xsl:element name="tr">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
				<xsl:apply-templates/>
			</xsl:element>
		</xsl:if>
		<xsl:if test="not(@class)">
			<tr>
				<xsl:apply-templates/>
			</tr>
		</xsl:if>
	</xsl:template>
	<!--
		  headerCol for a table
	  -->
	<xsl:template match="headerCol | th">
		<xsl:element name="th">
			<xsl:call-template name="DoCellAttributes"/>
			<xsl:if test="not(@align)">
				<xsl:attribute name="align">left</xsl:attribute>
			</xsl:if>
			<xsl:if test="not(@valign)">
				<xsl:attribute name="valign">top</xsl:attribute>
			</xsl:if>
			<xsl:if test="@class">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			</xsl:if>
			<xsl:attribute name="style">padding-left:.2em</xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!--
		  row for a table
	  -->
	<xsl:template match="row | tr">
		<xsl:if test="@class">
			<xsl:element name="tr">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
				<xsl:apply-templates/>
			</xsl:element>
		</xsl:if>
		<xsl:if test="not(@class)">
			<tr>
				<xsl:apply-templates/>
			</tr>
		</xsl:if>
	</xsl:template>
	<!--
		  col for a table
	  -->
	<xsl:template match="col | td">
		<xsl:element name="td">
			<xsl:call-template name="DoCellAttributes"/>
			<xsl:attribute name="style">padding-left:.2em</xsl:attribute>
			<xsl:if test="@class">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			</xsl:if>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!--
		  caption for a table
	  -->
	<xsl:template match="caption">
		<xsl:element name="tr">
			<xsl:if test="@class">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			</xsl:if>
			<td colspan="30">
				<xsl:call-template name="DoCellAttributes"/>
				<b>
					<!-- default is bold -->
					<xsl:apply-templates/>
				</b>
			</td>
		</xsl:element>
	</xsl:template>
	<!--
	  exampleRef
	  -->
	<xsl:template match="exampleRef">
		<xsl:if test="@letter">
			<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@letter"/></xsl:attribute>
				<xsl:if test="not(@paren) or @paren='both' or @paren='initial'">(</xsl:if>
				<xsl:if test="@equal='yes'">=</xsl:if>
				<xsl:if test="not(@letterOnly='yes')">
					<xsl:apply-templates select="id(@letter)" mode="example"/>
				</xsl:if>
				<xsl:apply-templates select="id(@letter)" mode="letter"/>
				<xsl:if test="@punct">
					<xsl:value-of select="@punct"/>
				</xsl:if>
				<xsl:if test="not(@paren) or @paren='both' or @paren='final'">)</xsl:if>
			</xsl:element>
		</xsl:if>
		<xsl:if test="@num">
			<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@num"/></xsl:attribute>
				<xsl:if test="not(@paren) or @paren='both' or @paren='initial'">(</xsl:if>
				<xsl:if test="@equal='yes'">=</xsl:if>
				<xsl:apply-templates select="id(@num)" mode="example"/>
				<xsl:if test="@punct">
					<xsl:value-of select="@punct"/>
				</xsl:if>
				<xsl:if test="not(@paren) or @paren='both' or @paren='final'">)</xsl:if>
			</xsl:element>
		</xsl:if>
	</xsl:template>
	<!-- ===========================================================
	  ENDNOTES and ENDNOTEREFS
	  =========================================================== -->
	<!--
	  endnotes
	  -->
	<xsl:template match="endnotes">
		<xsl:if test="//endnote">
			<hr size="3"/>
			<a name="rXLingPapEndnotes">
				<xsl:call-template name="OutputChapTitle">
					<xsl:with-param name="sTitle">
						<xsl:call-template name="OutputEndnotesLabel"/>
					</xsl:with-param>
				</xsl:call-template>
			</a>
			<table>
				<xsl:apply-templates select="//endnote" mode="backMatter"/>
			</table>
		</xsl:if>
	</xsl:template>
	<!--
	  endnote in flow of text
	  -->
	<xsl:template match="endnote">
		<span class="super">[<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
				<xsl:apply-templates select="." mode="endnote"/>
			</xsl:element>]</span>
	</xsl:template>
	<!--
	  endnote in back matter
	  -->
	<xsl:template match="endnote" mode="backMatter">
		<tr>
			<td valign="top">
				<xsl:element name="a">
					<xsl:attribute name="name"><xsl:value-of select="@id"/></xsl:attribute>[<xsl:apply-templates select="." mode="endnote"/>]</xsl:element>
			</td>
			<td>
				<xsl:apply-templates/>
			</td>
		</tr>
	</xsl:template>
	<!--
	  endnoteRef
	  -->
	<xsl:template match="endnoteRef">
		<span class="super">[<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@ref"/></xsl:attribute>
				<xsl:apply-templates select="id(@ref)" mode="endnote"/>
			</xsl:element>]</span>
	</xsl:template>
	<!-- ===========================================================
	  CITATIONS and REFERENCES
	  =========================================================== -->
	<!--
	  citation
	  -->
	<xsl:template match="//citation">
		<xsl:variable name="refer" select="id(@ref)"/>
		<xsl:element name="a">
			<xsl:attribute name="href">#<xsl:value-of select="@ref"/></xsl:attribute>
			<xsl:if test="@author='yes'">
				<xsl:value-of select="$refer/../@citename"/>
				<xsl:text>&#x20;</xsl:text>
			</xsl:if>
			<xsl:if test="not(@paren) or @paren='both' or @paren='initial'">(</xsl:if>
			<xsl:variable name="works" select="//refWork[../@name=$refer/../@name and @id=//citation/@ref]"/>
			<xsl:variable name="date">
				<xsl:value-of select="$refer/refDate"/>
			</xsl:variable>
			<xsl:if test="@author='yes' and not(not(@paren) or @paren='both' or @paren='initial')">
				<xsl:text>&#x20;</xsl:text>
			</xsl:if>
			<xsl:value-of select="$date"/>
			<xsl:if test="count($works[refDate=$date])>1">
				<xsl:apply-templates select="$refer" mode="dateLetter"/>
			</xsl:if>
			<xsl:if test="@page">:<xsl:value-of select="@page"/>
			</xsl:if>
			<xsl:if test="not(@paren) or @paren='both' or @paren='final'">)</xsl:if>
		</xsl:element>
	</xsl:template>
	<!--
	  references
	  -->
	<xsl:template match="references">
		<hr size="3"/>
		<a name="rXLingPapReferences">
			<xsl:call-template name="OutputChapTitle">
				<xsl:with-param name="sTitle">
					<xsl:call-template name="OutputReferencesLabel"/>
				</xsl:with-param>
			</xsl:call-template>
		</a>
		<div style="margin-left:0.25in">
			<xsl:for-each select="//refAuthor[refWork/@id=//citation/@ref]">
				<xsl:variable name="works" select="refWork[@id=//citation/@ref]"/>
				<xsl:for-each select="$works">
					<p style="text-indent:-0.25in;margin-bottom:0in;margin-top:0in">
						<xsl:variable name="author">
							<xsl:value-of select="normalize-space(../@name)"/>
						</xsl:variable>
						<xsl:element name="a">
							<xsl:attribute name="name"><xsl:value-of select="@id"/></xsl:attribute>
							<xsl:value-of select="$author"/>
						</xsl:element>
						<xsl:if test="substring($author,string-length($author),string-length($author))!='.'">.</xsl:if>&#x20;  <xsl:variable name="date">
							<xsl:value-of select="refDate"/>
						</xsl:variable>
						<xsl:value-of select="$date"/>
						<xsl:if test="count($works[refDate=$date])>1">
							<xsl:apply-templates select="." mode="dateLetter"/>
						</xsl:if>.
<!--
							   book
 -->
						<xsl:if test="book">
							<i>
								<xsl:apply-templates select="refTitle"/>.  </i>
							<xsl:if test="book/series">
								<xsl:value-of select="book/series"/>
								<xsl:call-template name="OutputPeriodIfNeeded">
									<xsl:with-param name="sText" select="book/series"/>
								</xsl:call-template>
								<xsl:text>&#x20;</xsl:text>
							</xsl:if>
							<xsl:value-of select="book/publisher"/>
							<xsl:call-template name="OutputPeriodIfNeeded">
								<xsl:with-param name="sText" select="book/publisher"/>
							</xsl:call-template>
							<xsl:text>&#x20;</xsl:text>
							<xsl:value-of select="book/location"/>
						</xsl:if>
						<!--
							   collection
 -->
						<xsl:if test="collection">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text> In </xsl:text>
							<xsl:value-of select="collection/collEd"/>
							<xsl:text>, ed</xsl:text>
							<xsl:if test="collection/collEd/@plural='yes'">
								<xsl:text>s</xsl:text>
							</xsl:if>
							<xsl:text>. </xsl:text>
							<i>
								<xsl:value-of select="collection/collTitle"/>
							</i>
							<xsl:choose>
								<xsl:when test="collection/collVol">
									<xsl:text>&#x20;</xsl:text>
									<xsl:value-of select="collection/collVol"/>
									<xsl:text>:</xsl:text>
									<xsl:value-of select="collection/collPage"/>
									<xsl:text>. </xsl:text>
								</xsl:when>
								<xsl:when test="collection/collPage">
									<xsl:text>, </xsl:text>
									<xsl:value-of select="collection/collPage"/>
									<xsl:text>. </xsl:text>
								</xsl:when>
								<xsl:otherwise>
									<xsl:text>.</xsl:text>
								</xsl:otherwise>
							</xsl:choose>
							<xsl:value-of select="collection/publisher"/>
							<xsl:if test="collection/location">, <xsl:value-of select="collection/location"/>
							</xsl:if>
						</xsl:if>
						<!--
							   dissertation
 -->
						<xsl:if test="dissertation">
							<i>
								<xsl:apply-templates select="refTitle"/>.  </i>
							<xsl:value-of select="dissertation/location"/>: <xsl:value-of select="dissertation/institution"/> Ph.D. dissertation.<xsl:if test="dissertation/published">  Published by <xsl:value-of select="dissertation/published/publisher"/>, <xsl:value-of select="dissertation/published/location"/>, <xsl:value-of select="dissertation/published/pubDate"/>
							</xsl:if>
						</xsl:if>
						<!--
							   journal article
 -->
						<xsl:if test="article">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text>&#x20;</xsl:text>
							<i>
								<xsl:value-of select="article/jTitle"/>
								<xsl:text>&#x20;</xsl:text>
								<xsl:value-of select="article/jVol"/>:<xsl:value-of select="article/jPages"/>
							</i>
						</xsl:if>
						<!--
							   ms (manuscript)
 -->
						<xsl:if test="ms">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text>&#x20;</xsl:text>
							<xsl:value-of select="ms/institution"/>
							<xsl:text> ms</xsl:text>
						</xsl:if>
						<!--
							   paper
 -->
						<xsl:if test="paper">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text>  Paper presented at the </xsl:text>
							<xsl:value-of select="paper/conference"/>
							<xsl:if test="paper/location">, <xsl:value-of select="paper/location"/>
							</xsl:if>
						</xsl:if>
						<!--
							   proceedings
 -->
						<xsl:if test="proceedings">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text>  In </xsl:text>
							<xsl:value-of select="proceedings/procEd"/>
							<xsl:text>, ed</xsl:text>
							<xsl:if test="proceedings/procEd/@plural='yes'">
								<xsl:text>s</xsl:text>
							</xsl:if>
							<xsl:text>. </xsl:text>
							<i>
								<xsl:value-of select="proceedings/procTitle"/>
							</i>
							<xsl:choose>
								<xsl:when test="proceedings/procVol">
									<xsl:text>&#x20;</xsl:text>
									<xsl:value-of select="proceedings/procVol"/>
									<xsl:text>:</xsl:text>
									<xsl:value-of select="proceedings/procPage"/>
									<xsl:text>. </xsl:text>
								</xsl:when>
								<xsl:when test="proceedings/procPage">
									<xsl:text>, </xsl:text>
									<xsl:value-of select="proceedings/procPage"/>
									<xsl:text>. </xsl:text>
								</xsl:when>
								<xsl:otherwise>
									<xsl:text>. </xsl:text>
								</xsl:otherwise>
							</xsl:choose>
							<xsl:value-of select="proceedings/publisher"/>
							<xsl:text>, </xsl:text>
							<xsl:value-of select="proceedings/location"/>
						</xsl:if>
						<!--
							   thesis
 -->
						<xsl:if test="thesis">
							<i>
								<xsl:apply-templates select="refTitle"/>.  </i>
							<xsl:value-of select="thesis/location"/>: <xsl:value-of select="thesis/institution"/> M.A. thesis<xsl:if test="thesis/published">  Published by <xsl:value-of select="thesis/published/publisher"/>, <xsl:value-of select="thesis/published/location"/>, <xsl:value-of select="thesis/published/pubDate"/>
							</xsl:if>
						</xsl:if>
						<!--
							   webPage
 -->
						<xsl:if test="webPage">
							<xsl:value-of select="$sLdquo"/>
							<xsl:apply-templates select="refTitle"/>
							<xsl:text>.</xsl:text>
							<xsl:value-of select="$sRdquo"/>
							<xsl:text>&#x20;</xsl:text>
							<xsl:if test="webPage/institution">
								<xsl:value-of select="webPage/institution"/>
							</xsl:if>
							<xsl:if test="webPage/publisher">
								<xsl:value-of select="webPage/publisher"/>
							</xsl:if>
							<xsl:if test="webPage/location">
								<xsl:text>, </xsl:text>
								<xsl:value-of select="webPage/location"/>
							</xsl:if>
							<xsl:text> (</xsl:text>
							<xsl:element name="a">
								<xsl:attribute name="href"><xsl:value-of select="webPage/url"/></xsl:attribute>
								<xsl:value-of select="webPage/url"/>
							</xsl:element>
							<xsl:text>)</xsl:text>
						</xsl:if>
						<xsl:text>.</xsl:text>
					</p>
				</xsl:for-each>
			</xsl:for-each>
		</div>
	</xsl:template>
	<!--
	  refTitle
	  -->
	<xsl:template match="refTitle">
		<xsl:apply-templates/>
	</xsl:template>
	<!-- ===========================================================
	  BR
	  =========================================================== -->
	<xsl:template match="br">
		<br/>
	</xsl:template>
	<!-- ===========================================================
	  GLOSS
	  =========================================================== -->
	<xsl:template match="gloss">
		<xsl:element name="span">
			<xsl:attribute name="class"><xsl:value-of select="id(@lang)"/></xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!-- ===========================================================
	  LANGDATA
	  =========================================================== -->
	<xsl:template match="langData">
		<xsl:element name="span">
			<xsl:attribute name="class"><xsl:value-of select="id(@lang)"/></xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!-- ===========================================================
	  OBJECT
	  =========================================================== -->
	<xsl:template match="object">
		<xsl:element name="span">
			<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!-- ===========================================================
	  IMG
	  =========================================================== -->
	<xsl:template match="img">
		<xsl:element name="img">
			<xsl:attribute name="src"><xsl:value-of select="@src"/></xsl:attribute>
			<xsl:value-of select="."/>
		</xsl:element>
	</xsl:template>
	<!-- ===========================================================
	  NUMBERING PROCESSING
	  =========================================================== -->
	<!--
				  sections
-->
	<xsl:template mode="number" match="*">
		<xsl:if test="//chapter">
			<xsl:apply-templates select="." mode="numberChapter"/>.</xsl:if>
		<xsl:number level="multiple" count="section1 | section2 | section3 | section4 | section5 | section6" format="1.1"/>
	</xsl:template>
	<!--
				  appendix
-->
	<xsl:template mode="numberAppendix" match="*">
		<xsl:number level="multiple" count="appendix | section1 | section2 | section3 | section4 | section5 | section6" format="A.1"/>
	</xsl:template>
	<!--
				  chapter
-->
	<xsl:template mode="numberChapter" match="*">
		<xsl:number level="any" count="chapter" format="1"/>
	</xsl:template>
	<!--
				  part
-->
	<xsl:template mode="numberPart" match="*">
		<xsl:number level="multiple" count="part" format="I"/>
	</xsl:template>
	<!--
				  endnote
-->
	<xsl:template mode="endnote" match="*">
		<xsl:number level="any" count="endnote" format="1"/>
	</xsl:template>
	<!--
				  example
-->
	<xsl:template mode="example" match="*">
		<xsl:number level="any" count="example" format="1"/>
	</xsl:template>
	<!--
				  letter
-->
	<xsl:template mode="letter" match="*">
		<xsl:number level="single" count="listWord | listSingle | listInterlinear | lineSet" format="a"/>
	</xsl:template>
	<!--
				  dateLetter
-->
	<xsl:template mode="dateLetter" match="*">
		<xsl:number level="single" count="refWork[@id=//citation/@ref]" format="a"/>
	</xsl:template>
	<!-- ===========================================================
	  NAMED TEMPLATES
	  =========================================================== -->
	<!--
				  DoCellAttributes
				  -->
	<xsl:template name="DoCellAttributes">
		<xsl:if test="@align">
			<xsl:attribute name="align"><xsl:value-of select="@align"/></xsl:attribute>
		</xsl:if>
		<xsl:if test="@colspan">
			<xsl:attribute name="colspan"><xsl:value-of select="@colspan"/></xsl:attribute>
		</xsl:if>
		<xsl:if test="@rowspan">
			<xsl:attribute name="rowspan"><xsl:value-of select="@rowspan"/></xsl:attribute>
		</xsl:if>
		<xsl:if test="@valign">
			<xsl:attribute name="valign"><xsl:value-of select="@valign"/></xsl:attribute>
		</xsl:if>
		<xsl:if test="@width">
			<xsl:attribute name="width"><xsl:value-of select="@width"/></xsl:attribute>
		</xsl:if>
	</xsl:template>
	<!--
				  exampleNumber
-->
	<xsl:template name="exampleNumber">(<xsl:apply-templates select="." mode="example"/>)</xsl:template>
	<!--
				   OutputAbstractLabel
-->
	<xsl:template name="OutputAbstractLabel">
		<xsl:call-template name="OutputLabel">
			<xsl:with-param name="sDefault">Abstract</xsl:with-param>
			<xsl:with-param name="pLabel" select="//abstract/@label"/>
		</xsl:call-template>
	</xsl:template>
	<!--
				   OutputAcknowledgementsLabel
-->
	<xsl:template name="OutputAcknowledgementsLabel">
		<xsl:call-template name="OutputLabel">
			<xsl:with-param name="sDefault">Acknowledgements</xsl:with-param>
			<xsl:with-param name="pLabel" select="//acknowledgements/@label"/>
		</xsl:call-template>
	</xsl:template>
	<!--
				  OutputChapTitle
-->
	<xsl:template name="OutputChapTitle">
		<xsl:param name="sTitle"/>
		<p>
			<big>
				<big>
					<big>
						<b>
							<xsl:element name="a">
								<xsl:attribute name="name"><xsl:value-of select="@id"/></xsl:attribute>
								<xsl:value-of select="$sTitle"/>
							</xsl:element>
						</b>
					</big>
				</big>
			</big>
		</p>
	</xsl:template>
	<!--
				   OutputContentsLabel
-->
	<xsl:template name="OutputContentsLabel">
		<xsl:call-template name="OutputLabel">
			<xsl:with-param name="sDefault">Contents</xsl:with-param>
			<xsl:with-param name="pLabel" select="//contents/@label"/>
		</xsl:call-template>
	</xsl:template>
	<!--
				   OutputEndnotesLabel
-->
	<xsl:template name="OutputEndnotesLabel">
		<xsl:call-template name="OutputLabel">
			<xsl:with-param name="sDefault">Endnotes</xsl:with-param>
			<xsl:with-param name="pLabel" select="//endnotes/@label"/>
		</xsl:call-template>
	</xsl:template>
	<!--
				  OutputExampleNumber
-->
	<xsl:template name="OutputExampleNumber">
		<xsl:element name="a">
			<xsl:attribute name="name"><xsl:value-of select="../../@num"/></xsl:attribute>
			<xsl:call-template name="exampleNumber"/>
		</xsl:element>
	</xsl:template>
	<!--
				  OutputLabel
-->
	<xsl:template name="OutputLabel">
		<xsl:param name="sDefault"/>
		<xsl:param name="pLabel"/>
		<xsl:choose>
			<xsl:when test="$pLabel">
				<xsl:value-of select="$pLabel"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$sDefault"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<!--
				  OutputPeriodIfNeeded
-->
	<xsl:template name="OutputPeriodIfNeeded">
		<xsl:param name="sText"/>
		<xsl:variable name="sString">
			<xsl:value-of select="normalize-space($sText)"/>
		</xsl:variable>
		<xsl:if test="substring($sString, string-length($sString))!='.'">
			<xsl:text>.</xsl:text>
		</xsl:if>
	</xsl:template>
	<!--
				   OutputReferencesLabel
-->
	<xsl:template name="OutputReferencesLabel">
		<xsl:call-template name="OutputLabel">
			<xsl:with-param name="sDefault">References</xsl:with-param>
			<xsl:with-param name="pLabel" select="//references/@label"/>
		</xsl:call-template>
	</xsl:template>
	<!--
				  OutputSection
-->
	<xsl:template name="OutputSection">
		<xsl:element name="a">
			<xsl:attribute name="name"><xsl:value-of select="@id"/></xsl:attribute>
			<xsl:call-template name="OutputSectionNumberAndTitle"/>
		</xsl:element>
	</xsl:template>
	<!--
				  OutputSectionNumberAndTitle
-->
	<xsl:template name="OutputSectionNumberAndTitle">
		<xsl:variable name="bAppendix">
			<xsl:for-each select="ancestor::*">
				<xsl:if test="name(.)='appendix'">Y</xsl:if>
			</xsl:for-each>
		</xsl:variable>
		<xsl:if test="$bAppendix='Y'">
			<xsl:apply-templates select="." mode="numberAppendix"/>
		</xsl:if>
		<xsl:if test="not($bAppendix='Y')">
			<xsl:apply-templates select="." mode="number"/>
		</xsl:if>
		<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
		<xsl:apply-templates select="secTitle"/>
	</xsl:template>
	<!--
				  OutputAllSectionTOC
-->
	<xsl:template name="OutputAllChapterTOC">
		<xsl:param name="nLevel" select="3"/>
		<li>
			<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
				<xsl:apply-templates select="." mode="numberChapter"/>
				<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
				<xsl:apply-templates select="secTitle"/>
			</xsl:element>
			<ul>
				<xsl:call-template name="OutputAllSectionTOC">
					<xsl:with-param name="nLevel">
						<xsl:value-of select="$nLevel"/>
					</xsl:with-param>
					<xsl:with-param name="nodesSection1" select="section1"/>
				</xsl:call-template>
			</ul>
		</li>
	</xsl:template>
	<!--
				  OutputAllSectionTOC
-->
	<xsl:template name="OutputAllSectionTOC">
		<xsl:param name="nLevel" select="3"/>
		<xsl:param name="nodesSection1"/>
		<xsl:for-each select="$nodesSection1">
			<xsl:call-template name="OutputSectionTOC"/>
			<xsl:if test="section2 and $nLevel>=2">
				<ul>
					<xsl:for-each select="section2">
						<xsl:call-template name="OutputSectionTOC"/>
						<xsl:if test="section3 and $nLevel>=3">
							<ul>
								<xsl:for-each select="section3">
									<xsl:call-template name="OutputSectionTOC"/>
									<xsl:if test="section4 and $nLevel>=4">
										<ul>
											<xsl:for-each select="section4">
												<xsl:call-template name="OutputSectionTOC"/>
												<xsl:if test="section5 and $nLevel>=5">
													<ul>
														<xsl:for-each select="section5">
															<xsl:call-template name="OutputSectionTOC"/>
															<xsl:if test="section6 and $nLevel>=6">
																<ul>
																	<xsl:for-each select="section6">
																		<xsl:call-template name="OutputSectionTOC"/>
																	</xsl:for-each>
																</ul>
															</xsl:if>
														</xsl:for-each>
													</ul>
												</xsl:if>
											</xsl:for-each>
										</ul>
									</xsl:if>
								</xsl:for-each>
							</ul>
						</xsl:if>
					</xsl:for-each>
				</ul>
			</xsl:if>
		</xsl:for-each>
	</xsl:template>
	<!--
				  OutputSectionTOC
-->
	<xsl:template name="OutputSectionTOC">
		<li>
			<xsl:element name="a">
				<xsl:attribute name="href">#<xsl:value-of select="@id"/></xsl:attribute>
				<xsl:call-template name="OutputSectionNumberAndTitle"/>
			</xsl:element>
		</li>
	</xsl:template>
	<!--
				  OutputTable
-->
	<xsl:template name="OutputTable">
		<xsl:element name="table">
			<xsl:if test="@class">
				<xsl:attribute name="class"><xsl:value-of select="@class"/></xsl:attribute>
			</xsl:if>
			<xsl:if test="@border">
				<xsl:attribute name="border"><xsl:value-of select="@border"/></xsl:attribute>
			</xsl:if>
			<xsl:if test="@cellpadding">
				<xsl:attribute name="cellpadding"><xsl:value-of select="@cellpadding"/></xsl:attribute>
			</xsl:if>
			<xsl:if test="@cellspacing">
				<xsl:attribute name="cellspacing"><xsl:value-of select="@cellspacing"/></xsl:attribute>
			</xsl:if>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>
	<!--
				  OutputTableCells
-->
	<xsl:template name="OutputTableCells">
		<xsl:param name="sList"/>
		<xsl:param name="class"/>
		<xsl:variable name="sNewList" select="concat(normalize-space($sList),' ')"/>
		<xsl:variable name="sFirst" select="substring-before($sNewList,' ')"/>
		<xsl:variable name="sRest" select="substring-after($sNewList,' ')"/>
		<xsl:element name="td">
			<xsl:attribute name="class"><xsl:value-of select="$class"/></xsl:attribute>
			<xsl:attribute name="style"><xsl:value-of select="$sExampleCellPadding"/></xsl:attribute>
			<xsl:value-of select="$sFirst"/>
		</xsl:element>
		<xsl:if test="$sRest">
			<xsl:call-template name="OutputTableCells">
				<xsl:with-param name="sList" select="$sRest"/>
				<xsl:with-param name="class" select="$class"/>
			</xsl:call-template>
		</xsl:if>
	</xsl:template>
	<!-- ===========================================================
	  ELEMENTS TO IGNORE
	  =========================================================== -->
	<xsl:template match="language"/>
	<xsl:template match="comment"/>
	<xsl:template match="styles"/>
</xsl:stylesheet>
<!-- ===========================================================
	  REVISION HISTORY
	  ===========================================================
1.9.0 Andy Black 19-Apr-2006  Modifications to make it easier to edit with XMLmind.
1.8.1 Andy Black 06-Apr-2005  Output as xml (i.e.xhtml which is what it already was) and use utf-8 encoding.
												   Remove newlines between some elements (not really needed).
												   Fix output of non-breaking space so never get "splat" with MSXML2 transformer
												   Fix outputing of extraneous <ul/> elements in Appendix portion of table of contents
												   Instead of using an external object to create date, use a parameter.
1.8.0 Andy Black 29-Nov-2004  Add styles element
1.7.1 14-Oct-2004  Andy Black  Allow width elements on columns and also include section2 elements of appendices in the toc.
1.7.0 Andy Black 03-Jun-2004  Add link element (for media)
1.6.7 Andy Black 26-May-2004  Have Appendix be section1 if there are no chapters.
1.6.6 Andy Black 18-Dec-2003  Fix reference quotes and other puncutation.
1.6.5 Andy Black 16-Dec-2003  Increase font size of section5 and section6 titles
1.6.4 Andy Black 09-Dec-2003  Fix space before date in other citations
1.6.3 Andy Black 01-Dec-2003  Fix space before date in citations; Fix extra period if publisher or series ends with period.
1.6.2 Andy Black 01-Dec-2003  Allow chart to have lists
1.6.1 Andy Black 25-Nov-2003  Fixed listWord, single, and word to align better with example number
1.6.0 Andy Black 25-Sept-2003  Various improvements from Mexico web site version:
												   Get interlinear example lines to lines up with example number and letter.
												   Get class attrs to work better with table header columns and columns
												   Add space between author and date where needed in citations
1.5.0 Andy Black 13-Jan-2003  Allow chart to have class attr and to use no table if neither example nor endnote
												   Add genericRef element
1.4.4 Andy Black 03-Dec-2002 change <xsl:output> attributes per John Edwards' suggestions
1.4.3 Andy Black 16-Oct-2002 Refactored some label attribute handling.
1.4.2 Andy Black 16-Oct-2002 Added label to endnotes and references
1.4.1 Andy Black 07-Oct-2002 Added appendixRef; made p and pc work with css
1.4  Andy Black  04-Oct-2002  Remove unwanted gaps in examples by adding lineGroup around lines.
1.3  Andy Black  03-Oct-2002  Many changes per Cheri's needs;  Includes
													Allow <tree><p>stuff</p><img src="" alt=""/></ing></tree>
1.2  Andy Black  03-Jul-2002    Added <wrd/> and conflated lines (first pass)
1.1  Andy Black  08-May-2002  Changed some spaces to non-breaking spaces so there would be a space between
													section numbers and section titles.
1.0  Andy Black  21-Jun-2001  Initial version.
 -->
