// COMAddInShim.idl : IDL source for stshim
//

// This file will be processed by the MIDL tool to
// produce the type library (COMAddInShim.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(33C0D0E2-6756-4d81-8C23-2FC5F6884962),
	version(1.0),
	helpstring("SEC_COMAddInShim 1.0 Type Library")
]
library SEC_COMAddInShimLib
{
	importlib("stdole2.tlb");
	[
		uuid(1FC71CD2-ABBE-4cf1-8DC5-278B4C9EB7F2),
		helpstring("ConnectProxy Class")
	]
	coclass ConnectProxy
	{
		[default] interface IUnknown;
	};
};
