// PerlEC.idl : IDL source for PerlEC
//

// This file will be processed by the MIDL tool to
// produce the type library (PerlEC.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(82391711-76EE-4266-8BC2-66615BAB2437),
	version(4.0),
	helpstring("Perl IEncConverter implementation 4.0 Type Library")
]
library PerlECLib
{
	importlib("stdole2.tlb");
	importlib("ECInterfaces.tlb");

	[
		uuid(78F6933B-BEB4-4CAF-9E51-45BE4860BA07)
		, helpstring("Perl Expression IEncConverter implementation class")
		, hidden
	]
	coclass PerlExpressionEncConverter
	{
		[default] interface IEncConverter;
	};

	[
		uuid(0EED2654-90A6-4CED-84EE-7C0F93B60250)
		, helpstring("Perl Expression IEncConverterConfig implementation class")
		, hidden
	]
	coclass PerlExpressionEncConverterConfig
	{
		[default] interface IEncConverterConfig;
	};
};
