// PerlEC.idl : IDL source for PerlEC
//

// This file will be processed by the MIDL tool to
// produce the type library (PerlEC.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(85811A3D-27F5-4141-9A24-50914E87A964),
	version(3.1),
	helpstring("Perl IEncConverter implementation 3.1 Type Library")
]
library PerlECLib
{
	importlib("stdole2.tlb");
	importlib("ECInterfaces.tlb");

	[
		uuid(4830EC45-B4E7-4554-AE3C-F4E87484B18A)
		, helpstring("Perl Expression IEncConverter implementation class")
		, hidden
	]
	coclass PerlExpressionEncConverter
	{
		[default] interface IEncConverter;
	};

	[
		uuid(C027C2C5-D99C-47d0-A1C4-2CDC851C30EC)
		, helpstring("Perl Expression IEncConverterConfig implementation class")
		, hidden
	]
	coclass PerlExpressionEncConverterConfig
	{
		[default] interface IEncConverterConfig;
	};
};
