#!/bin/sh

# Perform an action on files governed by CPOL
#
# CPOL is the Code Project Open License

FILES="SilSidePane.dll"

cd "$(dirname "$0")"

case $1 in
	pack)
		for F in $FILES
		do
			if [ -f $F -a ! -f $F.gz ]
			then
				gzip -f $F
			fi
		done
	;;
	unpack)
		for F in $FILES
		do
			if [ -f $F.gz -a ! -f $F ]
			then
				gunzip -f $F.gz
			fi
		done
	;;
	check)
		for F in $FILES
		do
			[ -f $F ] || exit 1
		done
	;;
	*)
		echo >&2 "$0: Unknown action: $1"
		exit 1
	;;
esac
