#!/bin/bash
# Launch xchm after translating from chmsee style arguments:
#     chmsee help_file.chm::/sub/page.html
# to xchm compatible arguments:
#     xchm file:help_file.chm#xchm:/sub/page.html

CHMPATH="$(awk -F:: '{print $1}' <<< ${1})"
PAGEPATH="$(awk -F:: '{print $2}' <<< ${1})"

# LD_LIBRARY_PATH may have something unhelpful in the way (LT-20483).
unset LD_LIBRARY_PATH LD_PRELOAD

if [ "$PAGEPATH" = "" ]
then
	xchm "${CHMPATH}"
else
	xchm "file:${CHMPATH}#xchm:${PAGEPATH}"
fi
