#!/bin/bash
#
# Copyright (c) 2010-2021 SIL International
# This software is licensed under the LGPL, version 2.1 or later
# (http://www.gnu.org/licenses/lgpl-2.1.html)
#
# Prepare user configuration for running FieldWorks.
#
# See http://standards.freedesktop.org/basedir-spec/basedir-spec-0.6.html for
# standard locations and environment variables.

set -ueo pipefail

[[ -z ${FW_DEBUG_BASH_TRACE-} ]] || set -x
debugVerboseFlag=""
[[ -z ${FW_DEBUG-} ]] || debugVerboseFlag="-v"

scriptdir="$(dirname "$0")"
prefix=$(cd "$scriptdir/../.."; /bin/pwd)

FW_LIB=$prefix/lib/fieldworks
FW_SHARE=$prefix/share/fieldworks

WRITEKEY="${FW_LIB}/WriteKey.exe"
READKEY="${FW_LIB}/ReadKey.exe"

# Usage: Debug "blah blah" "blah"
Debug()
{
	[[ -z ${FW_DEBUG-} ]] || echo -e "$(date +'%F %T') setup-user[$$]: " "$@" || : "Do not fail from write error Broken pipe"
}

Debug "FW_DATA_DIR: ${FW_DATA_DIR}"
Debug "FW_CONFIG_DIR: ${FW_CONFIG_DIR}"
Debug "prefix: ${prefix}"

WriteKey()
{
	Debug "Writing" "$@"
	mono "${WRITEKEY}" "$@"
}

ReadKey()
{
	# MONO_DEBUG seems to trigger warnings being printed to stdout for
	# bad values in MONO_PATH. While correcting the occasional bad value
	# that creeps into MONO_PATH is good, just unsetting MONO_DEBUG here
	# will prevent surprise registry corruption when migrating registry
	# keys from old to new FW versions. This is LT-18815.
	(unset MONO_DEBUG
	mono "${READKEY}" "$@")
}

# For example:
#   CopyRegistryKey LM "Software/SIL/FieldWorks/7.0" "ProjectsDir" LM "Software/SIL/FieldWorks/8" "ProjectsDir"
CopyRegistryKey()
{
	SOURCE_ROOT="$1"
	SOURCE_LOCATION="$2"
	SOURCE_KEY="$3"

	DESTINATION_ROOT="$4"
	DESTINATION_LOCATION="$5"
	DESTINATION_KEY="$6"

	WriteKey "$DESTINATION_ROOT" "$DESTINATION_LOCATION" "$DESTINATION_KEY" \
		"$(ReadKey "$SOURCE_ROOT" "$SOURCE_LOCATION" "$SOURCE_KEY")"
}

(
	if [ ! -d "${FW_CONFIG_DIR}/Icu54/" ]; then
		echo "# Copying ICU data"
		mkdir -p "${FW_CONFIG_DIR}"
		cp ${debugVerboseFlag} -a "${FW_SHARE}/Icu54" "${FW_CONFIG_DIR}/"
	fi

	if [[ -z ${FLATPAK_ID-} ]]; then
		if [ ! -d "${FW_CONFIG_DIR}/SIL/" ]; then
			# This stanza goes back to 2013, and may not still be significant.
			echo "# Copying encoding converter registry"
			mkdir -p "${FW_CONFIG_DIR}/"
			cp ${debugVerboseFlag} -a "${FW_SHARE}/SIL" "${FW_CONFIG_DIR}/"
		fi
	fi

	if [ ! -d "${FW_DATA_DIR}/Projects/" ]; then
		echo "# Creating default Project database directory"
		mkdir -p "${FW_DATA_DIR}/Projects/"
	fi

	# Set registry keys

	cd "$FW_LIB"; RUNMODE="INSTALLED" . environ; cd "$OLDPWD"

	# Are there FW 9 registry settings?
	if ReadKey LM "Software/SIL/FieldWorks/9" "ProjectsDir" 2>/dev/null; then
		Debug "There are already FW 9 registry settings."
		# All done!
		:
	else
		# Are there FW 8 registry settings?
		if ReadKey LM "Software/SIL/FieldWorks/8" "ProjectsDir" 2>/dev/null; then
			# Migrate them to FW 9.

			echo "# Migrating from FW 8 registry settings."

			# Write any default settings for keys that are new in version 9.
			# None.

			# Migrate any settings from version 8 to version 9.
			CopyRegistryKey LM "Software/SIL/FieldWorks/8" "RootDataDir" LM "Software/SIL/FieldWorks/9" "RootDataDir"
			CopyRegistryKey LM "Software/SIL/FieldWorks/8" "RootCodeDir" LM "Software/SIL/FieldWorks/9" "RootCodeDir"
			CopyRegistryKey LM "Software/SIL/FieldWorks/8" "ProjectsDir" LM "Software/SIL/FieldWorks/9" "ProjectsDir"
		else
			# Are there FW 7 registry settings?
			if ReadKey LM "Software/SIL/FieldWorks/7.0" "ProjectsDir" 2>/dev/null; then
				# Migrate them to FW 9.

				echo "# Migrating from FW 7 registry settings."

				# Write any default settings for keys that are new in version 8 or 9.
				# None.

				# Migrate any settings from version 7 to version 9.
				CopyRegistryKey LM "Software/SIL/FieldWorks/7.0" "RootDataDir" LM "Software/SIL/FieldWorks/9" "RootDataDir"
				CopyRegistryKey LM "Software/SIL/FieldWorks/7.0" "RootCodeDir" LM "Software/SIL/FieldWorks/9" "RootCodeDir"
				CopyRegistryKey LM "Software/SIL/FieldWorks/7.0" "ProjectsDir" LM "Software/SIL/FieldWorks/9" "ProjectsDir"
			else
				# Create FW 9 registry settings for an empty registry.
				echo "# Creating FW 9 registry settings."

				# Are there SIL/EncodingConverterRepository registry keys?
				if [[ ! -d "${FW_CONFIG_DIR}/registry/LocalMachine/software/sil/encodingconverterrepository" ]]; then
					mkdir -p "${FW_CONFIG_DIR}/SIL/Repository"
					mkdir -p "${FW_CONFIG_DIR}/MoveRepositoryTo"
					# These are used in encoding-converters-core.git EncConverters.cs.
					WriteKey LM "Software/SIL/EncodingConverterRepository" "Registry" "${FW_CONFIG_DIR}/SIL/Repository/mappingRegistry.xml"
					WriteKey LM "Software/SIL/EncodingConverterRepository" "MoveRepositoryTo" "${FW_CONFIG_DIR}/MoveRepositoryTo"
				fi
				# InitIcu is also set by Registry.wxs but it's not clear if anything
				# uses it. And a newer Windows installer doesn't use this key.
				WriteKey LM "Software/SIL" "InitIcu" "1"
				# InstallLanguageUseLog appears to only be used by UnicodeCharEditor.
				WriteKey LM "Software/SIL/FieldWorks" "InstallLanguageUseLog" "False"

				WriteKey LM "Software/SIL/FieldWorks/9" "RootDataDir" "${FW_CONFIG_DIR}/"
				WriteKey LM "Software/SIL/FieldWorks/9" "ProjectsDir" "${FW_DATA_DIR}/Projects"

				WriteKey LM "Software/SIL" "Icu54DataDir" "${FW_CONFIG_DIR}/Icu54"
				WriteKey LM "Software/SIL" "Icu54Dir" "${FW_CONFIG_DIR}/Icu54"
			fi
		fi
	fi

	# Set some values unconditionally. Do this for any values that might begin
	# with PREFIX, such as "/usr", since FieldWorks flatpak will instead need
	# "/app". Since the user may have values with the wrong PREFIX in
	# CurrentUser, also write these settings to CurrentUser (CU) in addition to
	# LocalMachine (LM).

	# TODO: implement a WriteKey option to only set and not overwrite values. See comments in FWNX-1065.
	# TODO: implement batch load/dump in WriteKey similar to dconf

	echo "# Writing required registry settings."

	for registry in LM CU; do
		WriteKey ${registry} "Software/SIL/FieldWorks/9" "RootCodeDir" "${FW_SHARE}"
		WriteKey ${registry} "Software/SIL/SilEncConverters40" "PluginDir" "${FW_LIB}/EC/Plugins"
		WriteKey ${registry} "Software/SIL/SilEncConverters40" "RootDir" "${FW_LIB}"
		# It's not clear if "Primary Interop Assemblies" is being used by anything
		# other than NMock.
		WriteKey ${registry} "Software/Microsoft/.NETFramework/AssemblyFolders" "Primary Interop Assemblies" "${FW_LIB}"
	done

) | zenity --progress \
	--title="User specific setup" \
	--percentage=0 \
	--pulsate \
	--auto-close
