/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (c) 2002-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: CmnFwDlgsTlb.idl
Responsibility: Randy Regnier
Last reviewed: never
Description:
	Interface descriptions for the CmnFWDlgs dll. See CmnFWDlgs.idh for a fuller description.
-------------------------------------------------------------------------------*//*:End Ignore*/
// This file will be processed by the MIDL tool to
// produce the type library (CmnFWDlgs.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "common.idh" // DeclareInterface and similar

DeclareLibrary(CmnFwDlgs, 1.0, "Common FieldWorks Dialogs 1.0 Type Library",
	E6F6FD84-2E27-407e-ADBC-B89612034F7C)
{
	importlib("FwKernelTlb.tlb");
	importlib("LanguageTlb.tlb");
	importlib("ViewsTlb.tlb");
	#include "CmnFwDlgs.idh"
};
