/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (c) 2002-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: CmnFwDlgsPs.idl
Responsibility: Randy Regnier
Last reviewed:

	Defines Common Dialog Interfaces for proxy / stub generation.
-------------------------------------------------------------------------------*//*:End Ignore*/
import "oaidl.idl";
import "ocidl.idl";

import "FwKernelPs.idl";
import "ViewsPs.idl";

#include "Common.idh"

#define NO_COCLASSES 1

#include "CmnFwDlgs.idh"
