call ReplaceLinksGen BackupPasswordDlg.xml
call ReplaceLinksGen BackupReminderDlg.xml
call ReplaceLinksGen BackupRestore.xml
call ReplaceLinksGen BackupRestoreDlg.xml
call ReplaceLinksGen BackupScheduleDlg.xml
call ReplaceLinksGen BarSide.xml
call ReplaceLinksGen BarStatus.xml
call ReplaceLinksGen BrowseView.xml
call ReplaceLinksGen ChcList.xml
call ReplaceLinksGen DataEntryView.xml
call ReplaceLinksGen DataHistory.xml
call ReplaceLinksGen DataNav.xml
call ReplaceLinksGen DatModTemp.xml
call ReplaceLinksGen DatOrgFav.xml
call ReplaceLinksGen DocumentView.xml
call ReplaceLinksGen DragDrop.xml
call ReplaceLinksGen Edtccp.xml
call ReplaceLinksGen EdtDel.xml
call ReplaceLinksGen EdtDelEffDiag.xml
call ReplaceLinksGen EdtFind.xml
call ReplaceLinksGen EdtNxtMat.xml
call ReplaceLinksGen EdtPrvMat.xml
call ReplaceLinksGen EdtRedo.xml
call ReplaceLinksGen EdtReplace.xml
call ReplaceLinksGen EdtSelectAll.xml
call ReplaceLinksGen EdtUndo.xml
call ReplaceLinksGen FileExit.xml
call ReplaceLinksGen FileExport.xml
call ReplaceLinksGen FileImport.xml
call ReplaceLinksGen FileImportStandard.xml
call ReplaceLinksGen FileNewLang.xml
call ReplaceLinksGen FileNewProject.xml
call ReplaceLinksGen FileOpenProject.xml
call ReplaceLinksGen FileProps.xml
call ReplaceLinksGen FilePropsProj.xml
call ReplaceLinksGen FilePrtPrev.xml
call ReplaceLinksGen FileSave.xml
call ReplaceLinksGen FilterUsage.xml
call ReplaceLinksGen FmtBnN.xml
call ReplaceLinksGen FmtBrdr.xml
call ReplaceLinksGen FmtFont.xml
call ReplaceLinksGen FmtPara.xml
call ReplaceLinksGen FmtStyle.xml
call ReplaceLinksGen FmtWS.xml
call ReplaceLinksGen FwBasics.xml
call ReplaceLinksGen FwHelp.xml
call ReplaceLinksGen HlpAbout.xml
call ReplaceLinksGen HlpApp.xml
call ReplaceLinksGen HlpHow.xml
call ReplaceLinksGen HlpTutor.xml
call ReplaceLinksGen InsComment.xml
call ReplaceLinksGen InsExtLink.xml
call ReplaceLinksGen InsObject.xml
call ReplaceLinksGen InsPicture.xml
call ReplaceLinksGen InsSound.xml
call ReplaceLinksGen InsTable.xml
call ReplaceLinksGen Install.xml
call ReplaceLinksGen InsVideo.xml
call ReplaceLinksGen OptCFields.xml
call ReplaceLinksGen OptFilters.xml
call ReplaceLinksGen OptGen.xml
call ReplaceLinksGen OptOverlays.xml
call ReplaceLinksGen OptSortMeth.xml
call ReplaceLinksGen OverlaysUsage.xml
call ReplaceLinksGen PgSetup.xml
call ReplaceLinksGen SortUsage.xml
call ReplaceLinksGen StartUp.xml
call ReplaceLinksGen Sync.xml
call ReplaceLinksGen TbData.xml
call ReplaceLinksGen TbFormat.xml
call ReplaceLinksGen TbInsert.xml
call ReplaceLinksGen TbStandard.xml
call ReplaceLinksGen TbTools.xml
call ReplaceLinksGen TbWindow.xml
call ReplaceLinksGen TlsCustomize.xml
call ReplaceLinksGen TlsExplore.xml
call ReplaceLinksGen TlsList.xml
call ReplaceLinksGen TlsReport.xml
call ReplaceLinksGen TlsShoSelUse.xml
call ReplaceLinksGen TlsSpell.xml
call ReplaceLinksGen VwFilter.xml
call ReplaceLinksGen VwOverlay.xml
call ReplaceLinksGen VwSideBar.xml
call ReplaceLinksGen VwSortM.xml
call ReplaceLinksGen VwStatusBar.xml
call ReplaceLinksGen VwToolbar.xml
call ReplaceLinksGen VwViews.xml
call ReplaceLinksGen Window.xml
call ReplaceLinksGen WritSysProp.xml
