//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.FwCoreDlgs {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class FwCoreDlgs {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal FwCoreDlgs() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.FwCoreDlgs.FwCoreDlgs", typeof(FwCoreDlgs).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Bulk Replace Setup.
		/// </summary>
		internal static string khtpBulkReplaceTitle {
			get {
				return ResourceManager.GetString("khtpBulkReplaceTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Close.
		/// </summary>
		internal static string ks_Close {
			get {
				return ResourceManager.GetString("ks_Close", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} already exists.  Do you want to overwrite it?.
		/// </summary>
		internal static string ksAlreadyExists {
			get {
				return ResourceManager.GetString("ksAlreadyExists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The analysis writing system list was changed in another program before you changed it here.  You need to shut down all FieldWorks programs and restart them..
		/// </summary>
		internal static string ksAnalWsChangedMsg {
			get {
				return ResourceManager.GetString("ksAnalWsChangedMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Available Data for {0}.
		/// </summary>
		internal static string ksAvailDataForX {
			get {
				return ResourceManager.GetString("ksAvailDataForX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Available Features for {0}.
		/// </summary>
		internal static string ksAvailFeatsForX {
			get {
				return ResourceManager.GetString("ksAvailFeatsForX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Bound Stem.
		/// </summary>
		internal static string ksBdStemMenuCmd {
			get {
				return ResourceManager.GetString("ksBdStemMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Browse for file..
		/// </summary>
		internal static string ksBrowseForFile {
			get {
				return ResourceManager.GetString("ksBrowseForFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot Replace Displayed Picture.
		/// </summary>
		internal static string ksCannotReplaceDisplayedPicture {
			get {
				return ResourceManager.GetString("ksCannotReplaceDisplayedPicture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Couldn&apos;t set the focus.
		/// </summary>
		internal static string ksCannotSetFocus {
			get {
				return ResourceManager.GetString("ksCannotSetFocus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot Use Processor.
		/// </summary>
		internal static string ksCannotUseProcessor {
			get {
				return ResourceManager.GetString("ksCannotUseProcessor", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cautions:.
		/// </summary>
		internal static string ksCautions {
			get {
				return ResourceManager.GetString("ksCautions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CC Table.
		/// </summary>
		internal static string ksCCTable {
			get {
				return ResourceManager.GetString("ksCCTable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Changed External Links Root Directory.
		/// </summary>
		internal static string ksChangedExtLinksRootDir {
			get {
				return ResourceManager.GetString("ksChangedExtLinksRootDir", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} [{1}].
		/// </summary>
		internal static string ksCodePageDisplay {
			get {
				return ResourceManager.GetString("ksCodePageDisplay", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Compiled TECkit.
		/// </summary>
		internal static string ksCompiledTECKit {
			get {
				return ResourceManager.GetString("ksCompiledTECKit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Converters.
		/// </summary>
		internal static string ksConverters {
			get {
				return ResourceManager.GetString("ksConverters", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Copy File.
		/// </summary>
		internal static string ksCopyFile {
			get {
				return ResourceManager.GetString("ksCopyFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to If you want to replace a picture file, you must first delete the current picture..
		/// </summary>
		internal static string ksDeletePictureBeforeReplacingFile {
			get {
				return ResourceManager.GetString("ksDeletePictureBeforeReplacingFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		internal static string ksDescription {
			get {
				return ResourceManager.GetString("ksDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Enclitic.
		/// </summary>
		internal static string ksEncliticMenuCmd {
			get {
				return ResourceManager.GetString("ksEncliticMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enter the regular expression.
		/// </summary>
		internal static string ksEnterRE {
			get {
				return ResourceManager.GetString("ksEnterRE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error.
		/// </summary>
		internal static string ksError {
			get {
				return ResourceManager.GetString("ksError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (External links folder: {0}).
		/// </summary>
		internal static string ksExternalLinksFolder {
			get {
				return ResourceManager.GetString("ksExternalLinksFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Find CC Table File.
		/// </summary>
		internal static string ksFindCCTableFile {
			get {
				return ResourceManager.GetString("ksFindCCTableFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Find Conversion Mapping File.
		/// </summary>
		internal static string ksFindConvMappingFile {
			get {
				return ResourceManager.GetString("ksFindConvMappingFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Find Spec file for unknown mapping type.
		/// </summary>
		internal static string ksFindUnknownSpecFile {
			get {
				return ResourceManager.GetString("ksFindUnknownSpecFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks Project Utilities.
		/// </summary>
		internal static string ksFwProjectUtilities {
			get {
				return ResourceManager.GetString("ksFwProjectUtilities", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks Project synchronization problem.
		/// </summary>
		internal static string ksFwWsSyncProblem {
			get {
				return ResourceManager.GetString("ksFwWsSyncProblem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Help.
		/// </summary>
		internal static string ksHelp {
			get {
				return ResourceManager.GetString("ksHelp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Illegal characters.
		/// </summary>
		internal static string ksIllegalChars {
			get {
				return ResourceManager.GetString("ksIllegalChars", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The name cannot contain these characters:
		///{0}.
		/// </summary>
		internal static string ksIllegalNameMsg {
			get {
				return ResourceManager.GetString("ksIllegalNameMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Infix.
		/// </summary>
		internal static string ksInfixMenuCmd {
			get {
				return ResourceManager.GetString("ksInfixMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The sorting specification is not valid. {0} Please correct the error to continue..
		/// </summary>
		internal static string ksInvalidSortSpec {
			get {
				return ResourceManager.GetString("ksInvalidSortSpec", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ERROR: Language Definition File not loaded: m_langDef == null.
		/// </summary>
		internal static string ksLDFNotLoaded {
			get {
				return ResourceManager.GetString("ksLDFNotLoaded", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Leave File.
		/// </summary>
		internal static string ksLeaveFile {
			get {
				return ResourceManager.GetString("ksLeaveFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Morpheme Break Help.
		/// </summary>
		internal static string ksMorphemeBreakHelp {
			get {
				return ResourceManager.GetString("ksMorphemeBreakHelp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Move File.
		/// </summary>
		internal static string ksMoveFile {
			get {
				return ResourceManager.GetString("ksMoveFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Move or Copy File?.
		/// </summary>
		internal static string ksMoveOrCopyFile {
			get {
				return ResourceManager.GetString("ksMoveOrCopyFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The file you have selected is not in the external links folder for this project. Would you like to move or copy the file to that folder to make it easier to share and back up, along with your other project data?.
		/// </summary>
		internal static string ksMoveOrCopyFileToExtDir {
			get {
				return ResourceManager.GetString("ksMoveOrCopyFileToExtDir", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This project links to {0} external files in the previous external links folder. Would you like to move or copy the file to the new folder to make it easier to share and backup, along with your other project data?.
		/// </summary>
		internal static string ksMoveOrCopyToNewDir {
			get {
				return ResourceManager.GetString("ksMoveOrCopyToNewDir", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to A text selection is required for this menu option..
		/// </summary>
		internal static string ksNeedTextSelection {
			get {
				return ResourceManager.GetString("ksNeedTextSelection", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New.
		/// </summary>
		internal static string ksNew {
			get {
				return ResourceManager.GetString("ksNew", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (New folder: {0}).
		/// </summary>
		internal static string ksNewFolder {
			get {
				return ResourceManager.GetString("ksNewFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The Database folder ({0}) is compressed. A new project cannot be created unless the folder is decompressed. To fix this problem, close down this application and any other open FieldWorks applications. When you next launch a FieldWorks application, there will be an opportunity to fix the folder automatically..
		/// </summary>
		internal static string ksNLPFolderCompressed {
			get {
				return ResourceManager.GetString("ksNLPFolderCompressed", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The Database folder ({0}) is encrypted. A new project cannot be created unless the folder is decrypted. To fix this problem, close down this application and any other open FieldWorks applications. When you next launch a FieldWorks application, there will be an opportunity to fix the folder automatically..
		/// </summary>
		internal static string ksNLPFolderEncrypted {
			get {
				return ResourceManager.GetString("ksNLPFolderEncrypted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Database folder problem.
		/// </summary>
		internal static string ksNLPFolderError {
			get {
				return ResourceManager.GetString("ksNLPFolderError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The processor you have created does not perform a Unicode to Unicode conversion;
		///it is for use with a legacy encoding.
		///It cannot be used in Bulk Edit operations..
		/// </summary>
		internal static string ksNoUnicodeToUnicode {
			get {
				return ResourceManager.GetString("ksNoUnicodeToUnicode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Prefix.
		/// </summary>
		internal static string ksPrefixMenuCmd {
			get {
				return ResourceManager.GetString("ksPrefixMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (Previous folder: {0}).
		/// </summary>
		internal static string ksPreviousFolder {
			get {
				return ResourceManager.GetString("ksPreviousFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Proclitic.
		/// </summary>
		internal static string ksProcliticMenuCmd {
			get {
				return ResourceManager.GetString("ksProcliticMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ???.
		/// </summary>
		internal static string ksQuestions {
			get {
				return ResourceManager.GetString("ksQuestions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Alternation.
		/// </summary>
		internal static string ksREAlternation {
			get {
				return ResourceManager.GetString("ksREAlternation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Any single character.
		/// </summary>
		internal static string ksREAnyChar {
			get {
				return ResourceManager.GetString("ksREAnyChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Beginning of line.
		/// </summary>
		internal static string ksREBeginLine {
			get {
				return ResourceManager.GetString("ksREBeginLine", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Boundary.
		/// </summary>
		internal static string ksREBoundaryChar {
			get {
				return ResourceManager.GetString("ksREBoundaryChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Any one character in the set.
		/// </summary>
		internal static string ksRECharFromSet {
			get {
				return ResourceManager.GetString("ksRECharFromSet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Any one character not in the set.
		/// </summary>
		internal static string ksRECharNotFromSet {
			get {
				return ResourceManager.GetString("ksRECharNotFromSet", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Digit.
		/// </summary>
		internal static string ksREDigitChar {
			get {
				return ResourceManager.GetString("ksREDigitChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} End of line.
		/// </summary>
		internal static string ksREEndLine {
			get {
				return ResourceManager.GetString("ksREEndLine", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} First capture.
		/// </summary>
		internal static string ksREFirstCapture {
			get {
				return ResourceManager.GetString("ksREFirstCapture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Grouping.
		/// </summary>
		internal static string ksREGrouping {
			get {
				return ResourceManager.GetString("ksREGrouping", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Regular Expression Help.
		/// </summary>
		internal static string ksREHelp {
			get {
				return ResourceManager.GetString("ksREHelp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Removing Important Writing System.
		/// </summary>
		internal static string ksRemovingEnWs {
			get {
				return ResourceManager.GetString("ksRemovingEnWs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to By removing the English writing system, some of your topics list items, may show &quot;***&quot; instead of their normal contents. For this reason, it is strongly recommended that you keep the English writing system active in your project. However, if you choose to remove English now and encounter problems viewing your topics list items, you may add English back at any time using the Add button.
		///
		///Do you want to remove English now?.
		/// </summary>
		internal static string ksRemovingEnWsMsg {
			get {
				return ResourceManager.GetString("ksRemovingEnWsMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Non-boundary.
		/// </summary>
		internal static string ksRENonboundaryChar {
			get {
				return ResourceManager.GetString("ksRENonboundaryChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Non-digit.
		/// </summary>
		internal static string ksRENondigitChar {
			get {
				return ResourceManager.GetString("ksRENondigitChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Non-space character.
		/// </summary>
		internal static string ksRENonspaceChar {
			get {
				return ResourceManager.GetString("ksRENonspaceChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Non-word character.
		/// </summary>
		internal static string ksRENonwordChar {
			get {
				return ResourceManager.GetString("ksRENonwordChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} nth capture.
		/// </summary>
		internal static string ksRENthCapture {
			get {
				return ResourceManager.GetString("ksRENthCapture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Exactly n times.
		/// </summary>
		internal static string ksRENTimes {
			get {
				return ResourceManager.GetString("ksRENTimes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} One or more times.
		/// </summary>
		internal static string ksREOneOrMore {
			get {
				return ResourceManager.GetString("ksREOneOrMore", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} One or zero times.
		/// </summary>
		internal static string ksREOptional {
			get {
				return ResourceManager.GetString("ksREOptional", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Quote metacharacter.
		/// </summary>
		internal static string ksREQuoteMeta {
			get {
				return ResourceManager.GetString("ksREQuoteMeta", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Second capture.
		/// </summary>
		internal static string ksRESecondCapture {
			get {
				return ResourceManager.GetString("ksRESecondCapture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Space character.
		/// </summary>
		internal static string ksRESpaceChar {
			get {
				return ResourceManager.GetString("ksRESpaceChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Third capture.
		/// </summary>
		internal static string ksREThirdCapture {
			get {
				return ResourceManager.GetString("ksREThirdCapture", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Word character.
		/// </summary>
		internal static string ksREWordChar {
			get {
				return ResourceManager.GetString("ksREWordChar", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Zero or more times.
		/// </summary>
		internal static string ksREZeroOrMore {
			get {
				return ResourceManager.GetString("ksREZeroOrMore", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Run Checked Utilities Now.
		/// </summary>
		internal static string ksRunUtilities {
			get {
				return ResourceManager.GetString("ksRunUtilities", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the features to make available for {0}..
		/// </summary>
		internal static string ksSelectAvailFeatsForX {
			get {
				return ResourceManager.GetString("ksSelectAvailFeatsForX", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Simulfix.
		/// </summary>
		internal static string ksSimulfixMenuCmd {
			get {
				return ResourceManager.GetString("ksSimulfixMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Sort Specification Error.
		/// </summary>
		internal static string ksSortSpecError {
			get {
				return ResourceManager.GetString("ksSortSpecError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specifies the actual encoding converter..
		/// </summary>
		internal static string ksSpecifiesActualEC {
			get {
				return ResourceManager.GetString("ksSpecifiesActualEC", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specifies the CC table to use..
		/// </summary>
		internal static string ksSpecifiesCCTable {
			get {
				return ResourceManager.GetString("ksSpecifiesCCTable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specifies the ICU transducer to use..
		/// </summary>
		internal static string ksSpecifiesICUTrans {
			get {
				return ResourceManager.GetString("ksSpecifiesICUTrans", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specifies the TECkit file to use..
		/// </summary>
		internal static string ksSpecifiesTECkitFile {
			get {
				return ResourceManager.GetString("ksSpecifiesTECkitFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Stem.
		/// </summary>
		internal static string ksStemMenuCmd {
			get {
				return ResourceManager.GetString("ksStemMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Suffix.
		/// </summary>
		internal static string ksSuffixMenuCmd {
			get {
				return ResourceManager.GetString("ksSuffixMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} Suprafix.
		/// </summary>
		internal static string ksSuprafixMenuCmd {
			get {
				return ResourceManager.GetString("ksSuprafixMenuCmd", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to TECkit Mapping.
		/// </summary>
		internal static string ksTECkitMapping {
			get {
				return ResourceManager.GetString("ksTECkitMapping", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add Custom Character.
		/// </summary>
		internal static string kstidAddPuaTitle {
			get {
				return ResourceManager.GetString("kstidAddPuaTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Several built-in lists have content in English only. FieldWorks is additionally creating an English writing system so that you can view the content of these lists..
		/// </summary>
		internal static string kstidAutoAddEnglish {
			get {
				return ResourceManager.GetString("kstidAutoAddEnglish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Built In.
		/// </summary>
		internal static string kstidBuiltIn {
			get {
				return ResourceManager.GetString("kstidBuiltIn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot Install Writing System.
		/// </summary>
		internal static string kstidCannotInstallWS {
			get {
				return ResourceManager.GetString("kstidCannotInstallWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You cannot change the full code &quot;{0}&quot; of the default user writing system..
		/// </summary>
		internal static string kstidCantChangeUserWs {
			get {
				return ResourceManager.GetString("kstidCantChangeUserWs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The &quot;{0}&quot; writing system already exists. To distinguish the new writing system you are creating from &quot;{0}&quot;, add script, region and/or variant information.{1}{1}Alternatively, remove this new writing system and use the existing writing system, &quot;{0}&quot;, if it meets your needs..
		/// </summary>
		internal static string kstidCantCreateDuplicateWs {
			get {
				return ResourceManager.GetString("kstidCantCreateDuplicateWs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The &quot;{0}&quot; writing system already uses the full code &quot;{1}&quot;. To distinguish the new writing system you are creating from &quot;{0}&quot;, add script,  region and/or variant information.{2}{2}Alternatively, cancel the Writing System Wizard and use the existing writing system, &quot;{0}&quot;, if it meets your needs..
		/// </summary>
		internal static string kstidCantOverwriteWsInDb {
			get {
				return ResourceManager.GetString("kstidCantOverwriteWsInDb", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Any changes made in the Styles dialog have been lost due to the change in the tool..
		/// </summary>
		internal static string kstidChangesAreLost {
			get {
				return ResourceManager.GetString("kstidChangesAreLost", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Changing the project name could be slow and will close and reopen the project.  Do you want to do this?.
		/// </summary>
		internal static string kstidChangingProjectName {
			get {
				return ResourceManager.GetString("kstidChangingProjectName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Close.
		/// </summary>
		internal static string kstidClose {
			get {
				return ResourceManager.GetString("kstidClose", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?  If you do, this account will no longer be able to access this language project..
		/// </summary>
		internal static string kstidConfirmDelete {
			get {
				return ResourceManager.GetString("kstidConfirmDelete", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Copy of {0}.
		/// </summary>
		internal static string kstidCopyStyleNameFormat {
			get {
				return ResourceManager.GetString("kstidCopyStyleNameFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Copy {0} of {1}.
		/// </summary>
		internal static string kstidCopyStyleNameFormatNumber {
			get {
				return ResourceManager.GetString("kstidCopyStyleNameFormatNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating {0}.
		/// </summary>
		internal static string kstidCreateLangProjCaption {
			get {
				return ResourceManager.GetString("kstidCreateLangProjCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating new database....
		/// </summary>
		internal static string kstidCreatingDB {
			get {
				return ResourceManager.GetString("kstidCreatingDB", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Creating default writing systems....
		/// </summary>
		internal static string kstidCreatingWS {
			get {
				return ResourceManager.GetString("kstidCreatingWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete User Configuration.
		/// </summary>
		internal static string kstidDeleteLabel {
			get {
				return ResourceManager.GetString("kstidDeleteLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Destination folder must be an existing subfolder of the External Links folder: {0}.
		/// </summary>
		internal static string kstidDestFolderMustBeInExtLinks {
			get {
				return ResourceManager.GetString("kstidDestFolderMustBeInExtLinks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected encoding converter is not installed. Select a different encoding converter or create a new one..
		/// </summary>
		internal static string kstidEncoderNotAvailable {
			get {
				return ResourceManager.GetString("kstidEncoderNotAvailable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Programming error.
		/// </summary>
		internal static string kstidErrApp {
			get {
				return ResourceManager.GetString("kstidErrApp", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The encoding converter repository could not be accessed. A system administrator must either give
		///your account write access to the appropriate directories, or else modify the writing system for you..
		/// </summary>
		internal static string kstidErrorAccessingEncConverters {
			get {
				return ResourceManager.GetString("kstidErrorAccessingEncConverters", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error in &quot;Find what&quot; text: {0}.
		/// </summary>
		internal static string kstidErrorInRegEx {
			get {
				return ResourceManager.GetString("kstidErrorInRegEx", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error in Regular Expression.
		/// </summary>
		internal static string kstidErrorInRegExHeader {
			get {
				return ResourceManager.GetString("kstidErrorInRegExHeader", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The writing system could not be installed. There is a problem in your language definition. See the
		///FieldWorks ReadMe for help in this area..
		/// </summary>
		internal static string kstidErrorInstallingWS {
			get {
				return ResourceManager.GetString("kstidErrorInstallingWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Can&apos;t create new database: {0}.
		/// </summary>
		internal static string kstidErrorNewDb {
			get {
				return ResourceManager.GetString("kstidErrorNewDb", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error saving writing system.
		/// </summary>
		internal static string kstidErrorSavingWs {
			get {
				return ResourceManager.GetString("kstidErrorSavingWs", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The project name is too long. Try making it shorter..
		/// </summary>
		internal static string kstidErrPathToLong {
			get {
				return ResourceManager.GetString("kstidErrPathToLong", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Less.
		/// </summary>
		internal static string kstidFindLessButtonText {
			get {
				return ResourceManager.GetString("kstidFindLessButtonText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The &apos;Find&apos; operation failed. We&apos;ve observed this before and the reasons are mysterious. If you can get it to happen repeatedly, please send the FieldWorks developers a copy of your database and the string you were searching for and tell us where the search started. Usually, the problem goes away if you just try again. That should be safe. .
		/// </summary>
		internal static string kstidFindMystery {
			get {
				return ResourceManager.GetString("kstidFindMystery", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Initializing new database....
		/// </summary>
		internal static string kstidInitializingDB {
			get {
				return ResourceManager.GetString("kstidInitializingDB", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose Picture.
		/// </summary>
		internal static string kstidInsertPictureChooseFileCaption {
			get {
				return ResourceManager.GetString("kstidInsertPictureChooseFileCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The selected file is not a supported image format..
		/// </summary>
		internal static string kstidInsertPictureReadError {
			get {
				return ResourceManager.GetString("kstidInsertPictureReadError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unsupported Image Format.
		/// </summary>
		internal static string kstidInsertPictureReadErrorCaption {
			get {
				return ResourceManager.GetString("kstidInsertPictureReadErrorCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Can&apos;t read XML file for &apos;{0}&apos; - invalid XML?.
		/// </summary>
		internal static string kstidInvalidXMlFile {
			get {
				return ResourceManager.GetString("kstidInvalidXMlFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This writing system named &quot;{0}&quot; with full code &quot;{1}&quot; is new to this project, but it exists in other projects. Only one definition for a given code is allowed for all projects on your computer.{2}Do you want to install the definition used by other projects?{2}Choose No to change the full code (language, script,  region, and/or variant) to something that is unique..
		/// </summary>
		internal static string kstidLocaleAlreadyInLanguages {
			get {
				return ResourceManager.GetString("kstidLocaleAlreadyInLanguages", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Combining marks (e.g. diacritics) cannot be added independently as valid characters. They must be combined with valid base characters..
		/// </summary>
		internal static string kstidLoneDiacriticNotValid {
			get {
				return ResourceManager.GetString("kstidLoneDiacriticNotValid", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Please select the appropriate custom character information..
		/// </summary>
		internal static string kstidMessageIntro {
			get {
				return ResourceManager.GetString("kstidMessageIntro", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning, you must select &quot;false&quot; (why do we even have a button???).
		/// </summary>
		internal static string kstidMessageWarning {
			get {
				return ResourceManager.GetString("kstidMessageWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Modify Custom Character.
		/// </summary>
		internal static string kstidModifyPuaTitle {
			get {
				return ResourceManager.GetString("kstidModifyPuaTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Multiple Styles.
		/// </summary>
		internal static string kstidMultipleStyles {
			get {
				return ResourceManager.GetString("kstidMultipleStyles", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Multiple Styles, Multiple Writing Systems.
		/// </summary>
		internal static string kstidMultipleStylesMultipleWS {
			get {
				return ResourceManager.GetString("kstidMultipleStylesMultipleWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Multiple Styles, {0}.
		/// </summary>
		internal static string kstidMultipleStylesOneWS {
			get {
				return ResourceManager.GetString("kstidMultipleStylesOneWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Multiple Writing Systems.
		/// </summary>
		internal static string kstidMultipleWritingSystems {
			get {
				return ResourceManager.GetString("kstidMultipleWritingSystems", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Character Style.
		/// </summary>
		internal static string kstidNewCharacterStyle {
			get {
				return ResourceManager.GetString("kstidNewCharacterStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Character Style {0}.
		/// </summary>
		internal static string kstidNewCharacterStyleWithNumber {
			get {
				return ResourceManager.GetString("kstidNewCharacterStyleWithNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Paragraph Style.
		/// </summary>
		internal static string kstidNewParagraphStyle {
			get {
				return ResourceManager.GetString("kstidNewParagraphStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New Paragraph Style {0}.
		/// </summary>
		internal static string kstidNewParagraphStyleWithNumber {
			get {
				return ResourceManager.GetString("kstidNewParagraphStyleWithNumber", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New User.
		/// </summary>
		internal static string kstidNewUser {
			get {
				return ResourceManager.GetString("kstidNewUser", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Can&apos;t find the language definition file for &apos;{0}&apos;..
		/// </summary>
		internal static string kstidNoLanguageDefinition {
			get {
				return ResourceManager.GetString("kstidNoLanguageDefinition", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finished searching the document. The search item was not found..
		/// </summary>
		internal static string kstidNoMatchMsg {
			get {
				return ResourceManager.GetString("kstidNoMatchMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finished searching the document..
		/// </summary>
		internal static string kstidNoMoreMatchesMsg {
			get {
				return ResourceManager.GetString("kstidNoMoreMatchesMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;None&gt;.
		/// </summary>
		internal static string kstidNone {
			get {
				return ResourceManager.GetString("kstidNone", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The specified file could not be read or interpreted as Unicode text.
		///
		///{0}.
		/// </summary>
		internal static string kstidNonUnicodeFileError {
			get {
				return ResourceManager.GetString("kstidNonUnicodeFileError", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;no style&gt;.
		/// </summary>
		internal static string kstidNoStyle {
			get {
				return ResourceManager.GetString("kstidNoStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Help is not available for this Tab..
		/// </summary>
		internal static string kstidNotAvailable {
			get {
				return ResourceManager.GetString("kstidNotAvailable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  - Not Installed.
		/// </summary>
		internal static string kstidNotInstalled {
			get {
				return ResourceManager.GetString("kstidNotInstalled", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No {0} found in the current Scripture project.
		/// </summary>
		internal static string kstidNoTokensFoundInCurrentScriptureProj {
			get {
				return ResourceManager.GetString("kstidNoTokensFoundInCurrentScriptureProj", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No {0} found in &apos;{1}&apos;..
		/// </summary>
		internal static string kstidNoTokensFoundInFile {
			get {
				return ResourceManager.GetString("kstidNoTokensFoundInFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Distinguish New Writing System.
		/// </summary>
		internal static string kstidNwsCaption {
			get {
				return ResourceManager.GetString("kstidNwsCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}, Multiple Writing Systems.
		/// </summary>
		internal static string kstidOneStyleMultipleWS {
			get {
				return ResourceManager.GetString("kstidOneStyleMultipleWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}, {1}.
		/// </summary>
		internal static string kstidOneStyleOneWS {
			get {
				return ResourceManager.GetString("kstidOneStyleOneWS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to .
		/// </summary>
		internal static string kstidOpen {
			get {
				return ResourceManager.GetString("kstidOpen", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Do you want to overwrite the existing collation rules (sorting)?.
		/// </summary>
		internal static string kstidOverwriteRules {
			get {
				return ResourceManager.GetString("kstidOverwriteRules", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Selecting similar writing system.
		/// </summary>
		internal static string kstidOverwriteRulesCaption {
			get {
				return ResourceManager.GetString("kstidOverwriteRulesCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning: Do not overwrite this Unicode definition unless you know what you are doing!.
		/// </summary>
		internal static string kstidOverwriteUnicode {
			get {
				return ResourceManager.GetString("kstidOverwriteUnicode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning: You are changing a definition of a custom character you&apos;ve already defined..
		/// </summary>
		internal static string kstidOverwriteUserCode {
			get {
				return ResourceManager.GetString("kstidOverwriteUserCode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} (original file does not exist).
		/// </summary>
		internal static string kstidPictureUnavailable {
			get {
				return ResourceManager.GetString("kstidPictureUnavailable", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Finished searching the document and made {0} replacements..
		/// </summary>
		internal static string kstidReplaceAllDone {
			get {
				return ResourceManager.GetString("kstidReplaceAllDone", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Search stopped by user before it finished searching the document; still made {0} replacements..
		/// </summary>
		internal static string kstidReplaceAllStopped {
			get {
				return ResourceManager.GetString("kstidReplaceAllStopped", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select a location within the External Links folder ({0}) for the picture file..
		/// </summary>
		internal static string kstidSelectExternalLinksSubFolder {
			get {
				return ResourceManager.GetString("kstidSelectExternalLinksSubFolder", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Stop.
		/// </summary>
		internal static string kstidStop {
			get {
				return ResourceManager.GetString("kstidStop", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This project already has a writing system named &quot;{0}&quot; that uses the full code &quot;{1}&quot;. This program cannot modify the original &quot;{2}&quot; writing system due to this conflict..
		/// </summary>
		internal static string kstidTooBadWsAlreadyInDb {
			get {
				return ResourceManager.GetString("kstidTooBadWsAlreadyInDb", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unregistered.
		/// </summary>
		internal static string kstidUnregistered {
			get {
				return ResourceManager.GetString("kstidUnregistered", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning.
		/// </summary>
		internal static string kstidWarning {
			get {
				return ResourceManager.GetString("kstidWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This project already has a writing system named &quot;{0}&quot; that uses the full code &quot;{1}&quot;. Do you want to remove the original writing system named &quot;{3}&quot; that uses the full code &quot;{2}&quot; and merge all data using it into the &quot;{1}&quot; writing system?{4}{4}Choose OK to merge all existing data or Cancel to change the full code (language, script, region, and/or variant) to something that is unique.{4}{4}Merging the data using this writing system could cause extensive changes to your data.  We recommend that you back up your  [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string kstidWsAlreadyInDb {
			get {
				return ResourceManager.GetString("kstidWsAlreadyInDb", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writing System Properties.
		/// </summary>
		internal static string kstidWspLabel {
			get {
				return ResourceManager.GetString("kstidWspLabel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Close.
		/// </summary>
		internal static string kstidWsPropsCloseAdvancedButtonText {
			get {
				return ResourceManager.GetString("kstidWsPropsCloseAdvancedButtonText", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Utilities.
		/// </summary>
		internal static string ksUtilities {
			get {
				return ResourceManager.GetString("ksUtilities", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The vernacular writing system list was changed in another program before you changed it here.  You need to shut down all FieldWorks programs and restart them..
		/// </summary>
		internal static string ksVernWsChangedMsg {
			get {
				return ResourceManager.GetString("ksVernWsChangedMsg", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to What it does:.
		/// </summary>
		internal static string ksWhatItDoes {
			get {
				return ResourceManager.GetString("ksWhatItDoes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to When to use:.
		/// </summary>
		internal static string ksWhenToUse {
			get {
				return ResourceManager.GetString("ksWhenToUse", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writing System Already Exists.
		/// </summary>
		internal static string ksWsAlreadyExists {
			get {
				return ResourceManager.GetString("ksWsAlreadyExists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Define New....
		/// </summary>
		internal static string ksWsDefineNew {
			get {
				return ResourceManager.GetString("ksWsDefineNew", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;New....
		/// </summary>
		internal static string ksWsNew {
			get {
				return ResourceManager.GetString("ksWsNew", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &amp;Writing System for {0}....
		/// </summary>
		internal static string ksWsNewFromExisting {
			get {
				return ResourceManager.GetString("ksWsNewFromExisting", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to  &lt;NONE SELECTED&gt;.
		/// </summary>
		internal static string ksWsNoDictionaryMatches {
			get {
				return ResourceManager.GetString("ksWsNoDictionaryMatches", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Encoding converter for importing {0}:.
		/// </summary>
		internal static string ksWSPropEncodingConverter {
			get {
				return ResourceManager.GetString("ksWSPropEncodingConverter", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ethnologue entry for {0}.
		/// </summary>
		internal static string ksWSPropEthnologueEntryFor {
			get {
				return ResourceManager.GetString("ksWSPropEthnologueEntryFor", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to This writing system for {0} is for:.
		/// </summary>
		internal static string ksWSPropGeneralWSname {
			get {
				return ResourceManager.GetString("ksWSPropGeneralWSname", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Select the keyboard combination with which to type {0} text..
		/// </summary>
		internal static string ksWSPropKeyboardInstruction {
			get {
				return ResourceManager.GetString("ksWSPropKeyboardInstruction", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Test the {0} writing system:.
		/// </summary>
		internal static string ksWSPropKeyboardTest {
			get {
				return ResourceManager.GetString("ksWSPropKeyboardTest", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify any custom Unicode characters needed for {0}:.
		/// </summary>
		internal static string ksWSPropPUAChars {
			get {
				return ResourceManager.GetString("ksWSPropPUAChars", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify punctuation usage for {0}..
		/// </summary>
		internal static string ksWSPropPunctuation {
			get {
				return ResourceManager.GetString("ksWSPropPunctuation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Specify the set of valid characters for {0}..
		/// </summary>
		internal static string ksWSPropValidChars {
			get {
				return ResourceManager.GetString("ksWSPropValidChars", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The most recent scan found no new punctuation patterns..
		/// </summary>
		internal static string PunctuationPatternsScanResultsNone {
			get {
				return ResourceManager.GetString("PunctuationPatternsScanResultsNone", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The most recent scan found {0} punctuation patterns which are not specified as either valid or invalid..
		/// </summary>
		internal static string PunctuationPatternsScanResultsPlural {
			get {
				return ResourceManager.GetString("PunctuationPatternsScanResultsPlural", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The most recent scan found 1 punctuation pattern which is not specified as either valid or invalid..
		/// </summary>
		internal static string PunctuationPatternsScanResultsSingular {
			get {
				return ResourceManager.GetString("PunctuationPatternsScanResultsSingular", resourceCulture);
			}
		}
	}
}
