/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (C) 2000, 2001 SIL International. All rights reserved.

Distributable under the terms of either the Common Public License or the
GNU Lesser General Public License, as specified in the LICENSING.txt file.

File: WorldPadPs.idl
Responsibility: Sharon Correll
Last reviewed: never

	Defines WorldPad interfaces for proxy / stub generation.
----------------------------------------------------------------------------------------------*/
import "oaidl.idl";
import "ocidl.idl";
import "FwKernelPs.idl";

#include "Common.idh"

#define NO_COCLASSES 1
#include "WorldPad.idh"
