openapi: 3.0.1
info:
  title: PlatformTarget Convergence API (conceptual CLI contract)
  version: 1.0.0
servers:
  - url: local://convergence.py
    description: Conceptual representation of the CLI entry points
paths:
  /convergence/platform-target/audit:
    post:
      summary: Scan all SDK-style projects for explicit PlatformTarget settings
      operationId: auditPlatformTargets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repoRoot:
                  type: string
                  description: Absolute path to the FieldWorks repository
                outputCsv:
                  type: string
                  description: Path to write platform_target_audit.csv
              required: [repoRoot]
      responses:
        "200":
          description: Audit completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalProjects:
                    type: integer
                  explicitCount:
                    type: integer
                  exceptionsDetected:
                    type: integer
                  csvPath:
                    type: string
  /convergence/platform-target/convert:
    post:
      summary: Apply removal/retention actions from decisions file
      operationId: convertPlatformTargets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repoRoot:
                  type: string
                decisionsCsv:
                  type: string
                dryRun:
                  type: boolean
                  default: false
              required: [repoRoot, decisionsCsv]
      responses:
        "200":
          description: Conversion succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  removedCount:
                    type: integer
                  keptCount:
                    type: integer
                  modifiedProjects:
                    type: array
                    items:
                      type: string
  /convergence/platform-target/validate:
    post:
      summary: Ensure no redundant PlatformTarget entries remain and AnyCPU exceptions are documented
      operationId: validatePlatformTargets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repoRoot:
                  type: string
                auditCsv:
                  type: string
                decisionsCsv:
                  type: string
      responses:
        "200":
          description: Validation passed
          content:
            application/json:
              schema:
                type: object
                properties:
                  redundantCount:
                    type: integer
                    description: Must be 0 for success
                  warnings:
                    type: array
                    items:
                      type: string
        "422":
          description: Validation failed due to remaining redundant entries
