openapi: 3.0.3
info:
  title: GenerateAssemblyInfo Compliance Service
  version: 1.0.0
  description: |
    Hypothetical REST façade that mirrors the responsibilities of the audit, conversion,
    and validation scripts for FieldWorks GenerateAssemblyInfo convergence.
servers:
  - url: https://fieldworks.local/api/assembly-info
paths:
  /audit:
    post:
      summary: Run repository-wide audit
      description: Scan every managed project and emit a compliance report.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                branch:
                  type: string
                  description: Git branch to audit.
                includeDeletedHistory:
                  type: boolean
                  default: true
                  description: Whether to search git history for deleted AssemblyInfo files.
              required: [branch]
      responses:
        "200":
          description: Audit completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  findings:
                    type: array
                    items:
                      $ref: "#/components/schemas/ValidationFinding"
                  generatedAt:
                    type: string
                    format: date-time
        "422":
          description: Audit aborted due to repository errors
  /convert:
    post:
      summary: Apply remediation actions
      description: Insert template links, flip GenerateAssemblyInfo, and restore missing AssemblyInfo files based on audit decisions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                decisions:
                  type: array
                  items:
                    $ref: "#/components/schemas/RemediationDecision"
                restoreMap:
                  type: array
                  items:
                    $ref: "#/components/schemas/RestoreInstruction"
              required: [decisions]
      responses:
        "200":
          description: Remediation succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  updatedProjects:
                    type: array
                    items:
                      $ref: "#/components/schemas/ManagedProject"
        "409":
          description: Merge conflicts or write failures encountered
  /validate:
    post:
      summary: Verify repository state after remediation
      description: Ensures every project links the template, `GenerateAssemblyInfo` is false, and no CS0579 warnings are produced.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                runBuild:
                  type: boolean
                  default: true
                  description: Whether to execute Debug/Release builds as part of validation.
                maxWarnings:
                  type: integer
                  default: 0
                  description: Allowed MSBuild warning budget for CS0579-related issues.
      responses:
        "200":
          description: Validation passed
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                  remainingFindings:
                    type: array
                    items:
                      $ref: "#/components/schemas/ValidationFinding"
        "400":
          description: Validation failed; see returned findings
components:
  schemas:
    ManagedProject:
      type: object
      properties:
        id:
          type: string
        category:
          type: string
          enum: [T, C, G]
        templateImported:
          type: boolean
        hasCustomAssemblyInfo:
          type: boolean
        generateAssemblyInfoValue:
          type: string
          enum: [true, false, missing]
        remediationState:
          type: string
          enum: [AuditPending, NeedsRemediation, Remediated, Validated]
        notes:
          type: string
    ValidationFinding:
      type: object
      properties:
        projectId:
          type: string
        findingCode:
          type: string
          enum:
            [
              MissingTemplateImport,
              GenerateAssemblyInfoTrue,
              MissingAssemblyInfoFile,
              DuplicateCompileEntry,
            ]
        severity:
          type: string
          enum: [Error, Warning, Info]
        details:
          type: string
    RemediationDecision:
      type: object
      properties:
        projectId:
          type: string
        action:
          type: string
          enum: [LinkTemplate, RestoreAssemblyInfo, ToggleGenerateFalse]
        justification:
          type: string
    RestoreInstruction:
      type: object
      properties:
        projectId:
          type: string
        path:
          type: string
        commitSha:
          type: string
      required: [projectId, path, commitSha]
