//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FieldWorks.Common.Framework {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class FrameworkStrings {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal FrameworkStrings() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FieldWorks.Common.Framework.FrameworkStrings", typeof(FrameworkStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to FieldWorks cannot automatically create a shortcut to a project with this file name, due to a bug in Windows. You can however manually create a shortcut. It should have the target {0}.
		/// </summary>
		internal static string ksCannotCreateShortcut {
			get {
				return ResourceManager.GetString("ksCannotCreateShortcut", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot create shortcut.
		/// </summary>
		internal static string ksCannotCreateShortcutCaption {
			get {
				return ResourceManager.GetString("ksCannotCreateShortcutCaption", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to File {0} could not be loaded.
		///{1}.
		/// </summary>
		internal static string ksCannotLoadFile {
			get {
				return ResourceManager.GetString("ksCannotLoadFile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cannot redefine factory style {0} to have a different Type, Context, Structure, or Function in {1}.
		/// </summary>
		internal static string ksCannotRedefineFactoryStyle {
			get {
				return ResourceManager.GetString("ksCannotRedefineFactoryStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Style {0} cannot be replaced with {1} because their contexts are incompatible. Error in &lt;replacements&gt; tag in {2}..
		/// </summary>
		internal static string ksCannotReplaceXwithY {
			get {
				return ResourceManager.GetString("ksCannotReplaceXwithY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} - {1}.
		/// </summary>
		internal static string ksInfoBarBtnToolTipFmt {
			get {
				return ResourceManager.GetString("ksInfoBarBtnToolTipFmt", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Illegal specification of both &apos;firstLine&apos; and &apos;hanging&apos; attributes for {0} style in {1}.
		/// </summary>
		internal static string ksInvalidFirstLineHanging {
			get {
				return ResourceManager.GetString("ksInvalidFirstLineHanging", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid version attribute in {0}.
		/// </summary>
		internal static string ksInvalidResourceFileVersion {
			get {
				return ResourceManager.GetString("ksInvalidResourceFileVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The basedOn style for {0} style must be specified in {1}.
		/// </summary>
		internal static string ksMissingBasedOnStyle {
			get {
				return ResourceManager.GetString("ksMissingBasedOnStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Paragraph style {0} must have a paragraph node in {1}.
		/// </summary>
		internal static string ksMissingParagraphNode {
			get {
				return ResourceManager.GetString("ksMissingParagraphNode", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Negative value is not valid for paragraph &apos;lineSpacing&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksNegativeLineSpacing {
			get {
				return ResourceManager.GetString("ksNegativeLineSpacing", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Style {0} cannot be based on itself (as defined in {1})..
		/// </summary>
		internal static string ksNoBasedOnSelf {
			get {
				return ResourceManager.GetString("ksNoBasedOnSelf", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Redo Insert Link.
		/// </summary>
		internal static string ksRedoInsertLink {
			get {
				return ResourceManager.GetString("ksRedoInsertLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} conforms to a DTD which is incompatible with this version of the program.
		///This version of the program requires version {1}..
		/// </summary>
		internal static string kstidIncompatibleDTDVersion {
			get {
				return ResourceManager.GetString("kstidIncompatibleDTDVersion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The new name differs only in letter case -- this is insufficient to change the database name..
		/// </summary>
		internal static string kstidNameDiffersOnlyInCase {
			get {
				return ResourceManager.GetString("kstidNameDiffersOnlyInCase", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Project Properties.
		/// </summary>
		internal static string kstidUndoRedoProjectProperties {
			get {
				return ResourceManager.GetString("kstidUndoRedoProjectProperties", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Warning.
		/// </summary>
		internal static string kstidWarning {
			get {
				return ResourceManager.GetString("kstidWarning", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Undo Insert Link.
		/// </summary>
		internal static string ksUndoInsertLink {
			get {
				return ResourceManager.GetString("ksUndoInsertLink", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;alignment&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownAlignmentValue {
			get {
				return ResourceManager.GetString("ksUnknownAlignmentValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized units specified for &apos;{0}&apos; attribute of {1} style in {2}.
		/// </summary>
		internal static string ksUnknownAttrUnits {
			get {
				return ResourceManager.GetString("ksUnknownAttrUnits", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;background&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownBackgroundValue {
			get {
				return ResourceManager.GetString("ksUnknownBackgroundValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized basedOn style for {0} style in {2}: {1}.
		/// </summary>
		internal static string ksUnknownBasedOnStyle {
			get {
				return ResourceManager.GetString("ksUnknownBasedOnStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;border&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownBorderValue {
			get {
				return ResourceManager.GetString("ksUnknownBorderValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;bulNumScheme&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownBulNumSchemeValue {
			get {
				return ResourceManager.GetString("ksUnknownBulNumSchemeValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;bulNumStartAt&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownBulNumStartAtValue {
			get {
				return ResourceManager.GetString("ksUnknownBulNumStartAtValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for font &apos;type&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownFontType {
			get {
				return ResourceManager.GetString("ksUnknownFontType", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for paragraph &apos;lineSpacingType&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownLineSpacingValue {
			get {
				return ResourceManager.GetString("ksUnknownLineSpacingValue", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized next style for {0} style in {2}: {1}.
		/// </summary>
		internal static string ksUnknownNextStyle {
			get {
				return ResourceManager.GetString("ksUnknownNextStyle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized &apos;{0}&apos; attribute for style {1} in {2}.
		/// </summary>
		internal static string ksUnknownStyleAttribute {
			get {
				return ResourceManager.GetString("ksUnknownStyleAttribute", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Unrecognized value for &apos;underlineColor&apos; attribute of {0} style in {1}.
		/// </summary>
		internal static string ksUnknownUnderlineColor {
			get {
				return ResourceManager.GetString("ksUnknownUnderlineColor", resourceCulture);
			}
		}
	}
}
