/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (C) 1999, 2001 SIL International. All rights reserved.

Distributable under the terms of either the Common Public License or the
GNU Lesser General Public License, as specified in the LICENSING.txt file.

File: LanguageTlb.idl
Responsibility: John Thomson
Last reviewed: Not yet. (previous main contents, now language.idh, reviewed mid June 99)

Description:
	Interface descriptions for the Language server. See Language.idh for a fuller description.
-------------------------------------------------------------------------------*//*:End Ignore*/

/***********************************************************************************************
	Include files
***********************************************************************************************/
import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";

#include "Common.idh" // DeclareInterface and similar

DeclareLibrary(LanguageLib, 1.0, "Language 1.0 Type Library",
	b80ee180-c0f1-11d2-8078-0000c0fb81b5)
{
	interface IOleDbEncap;

	#include "FwKernel.idh"
	#include "TextServ.idh"

	#include "render.idh"
	#include "language.idh"
	#include "DbAccess.idh"
};
