/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (C) 1999, 2001 SIL International. All rights reserved.

Distributable under the terms of either the Common Public License or the
GNU Lesser General Public License, as specified in the LICENSING.txt file.

File: LanguagePs.idl
Responsibility: John Thomson
Last reviewed:

	Defines Language Services Interfaces for proxy / stub generation.
-------------------------------------------------------------------------------*//*:End Ignore*/
import "oaidl.idl";
import "ocidl.idl";
//import "FwKernelPs.idl";
//import "DbAccessPs.idl";

#include "Common.idh"

#define NO_COCLASSES

#include "FwKernel.idh"
#include "TextServ.idh"

#include "DbAccess.idh"
#include "Render.idh"
#include "Language.idh"
