/*--------------------------------------------------------------------*//*:Ignore this sentence.
Copyright (c) 1999-2013 SIL International
This software is licensed under the LGPL, version 2.1 or later
(http://www.gnu.org/licenses/lgpl-2.1.html)

File: LanguageTlb.idl
Responsibility: John Thomson
Last reviewed: Not yet. (previous main contents, now language.idh, reviewed mid June 99)

Description:
	Interface descriptions for the Language server. See Language.idh for a fuller description.
-------------------------------------------------------------------------------*//*:End Ignore*/

/***********************************************************************************************
	Include files
***********************************************************************************************/
import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";

#include "common.idh" // DeclareInterface and similar

DeclareLibrary(LanguageLib, 1.0, "Language 1.0 Type Library",
	b80ee180-c0f1-11d2-8078-0000c0fb81b5)
{
	interface IOleDbEncap;

	#include "FwKernel.idh"
	#include "TextServ.idh"

	#include "Render.idh"
	#include "Language.idh"
};
