import "oaidl.idl";
import "ocidl.idl";

#include "common.idh" // DeclareInterface and similar

// This idl file was written based upon LangInstaller.cs definition of the interface.
// Its is used by linux as linux can't use #import on a tlb
// This idl file could be run through idlimp and replace the C# definition of the interface.

DeclareLibrary(LangInstaller, 1.0, "InstallLang", C13F5F35-1FD2-4388-B905-394D18D28EFB)
{
	DeclareInterface(LangInstaller, Unknown, EB5B7CFA-6EC8-4641-97D2-5FE338FF5434)
	{
		HRESULT Install(
				[in] BSTR locale,
				[in] VARIANT_BOOL fNewLang,
				[in] VARIANT_BOOL fAddPUA,
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT AddPUAChars(
				[in] BSTR locale,
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT Uninstall(
				[in] BSTR locale,
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT ShowCustomLocales(
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT ShowCustomLanguages(
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT RestoreOriginalSettings(
				[in] VARIANT_BOOL fNewLang,
				[out, retval] VARIANT_BOOL *pfSuccess);

		HRESULT get_ErrorCode(
				[out, retval] long *pErrorCode);

		HRESULT Cleanup();
	};

	DeclareCoClass(LangInstaller, 5EDF610A-F38F-4034-8714-76B95FDF70EC)
	{
		interface ILangInstaller;
	};
}
